(* Generated by scripts/generate_cubies.py. Do not edit: run the script.
   The tables are checked inside Rocq: paint_quarter_cube in Cubie.v proves they
   agree with the sticker tables, move for move. *)

From Stdlib Require Import List.
From Rubik Require Export Cube.CubieDefs.
Import ListNotations.

(** * Cubie tables

    Which piece a turn moves into each slot and how far it rotates there, and
    which colour each slot shows. *)

(** The colors a corner shows when solved, read around its own facelets. *)
Definition corner_colors (x : corner) (i : corner_facet) : color :=
  match x, i with
  | URF, C0 => Up
  | URF, C1 => Right
  | URF, C2 => Front
  | UFL, C0 => Up
  | UFL, C1 => Front
  | UFL, C2 => Left
  | ULB, C0 => Up
  | ULB, C1 => Left
  | ULB, C2 => Back
  | UBR, C0 => Up
  | UBR, C1 => Back
  | UBR, C2 => Right
  | DFR, C0 => Down
  | DFR, C1 => Front
  | DFR, C2 => Right
  | DLF, C0 => Down
  | DLF, C1 => Left
  | DLF, C2 => Front
  | DBL, C0 => Down
  | DBL, C1 => Back
  | DBL, C2 => Left
  | DRB, C0 => Down
  | DRB, C1 => Right
  | DRB, C2 => Back
  end.

(** The colors an edge shows when solved. *)
Definition edge_colors (x : edge) (i : edge_facet) : color :=
  match x, i with
  | UR, E0 => Up
  | UR, E1 => Right
  | UF, E0 => Up
  | UF, E1 => Front
  | UL, E0 => Up
  | UL, E1 => Left
  | UB, E0 => Up
  | UB, E1 => Back
  | DR, E0 => Down
  | DR, E1 => Right
  | DF, E0 => Down
  | DF, E1 => Front
  | DL, E0 => Down
  | DL, E1 => Left
  | DB, E0 => Down
  | DB, E1 => Back
  | FR, E0 => Front
  | FR, E1 => Right
  | FL, E0 => Front
  | FL, E1 => Left
  | BL, E0 => Back
  | BL, E1 => Left
  | BR, E0 => Back
  | BR, E1 => Right
  end.

(** The color a slot shows at one of its facelet positions. *)
Definition corner_color (x : corner_slot) (i : corner_facet) : color :=
  let (X, t) := x in corner_colors X (corner_facet_before i t).

(** And the colour an edge slot shows. *)
Definition edge_color (y : edge_slot) (i : edge_facet) : color :=
  let (Y, f) := y in edge_colors Y (edge_facet_before i f).

(** Paint the 54 stickers from the cubies occupying the 20 slots. *)
Definition paint (c : cube) : state :=
  match c with
  | Cube xURF xUFL xULB xUBR xDFR xDLF xDBL xDRB
           yUR yUF yUL yUB yDR yDF yDL yDB yFR yFL yBL yBR =>
    (Triple
    (Triple
      (Triple (corner_color xULB C0) (edge_color yUB E0) (corner_color xUBR C0))
      (Triple (edge_color yUL E0) (Up) (edge_color yUR E0))
      (Triple (corner_color xUFL C0) (edge_color yUF E0) (corner_color xURF C0)))
    (Triple
      (Triple (corner_color xURF C1) (edge_color yUR E1) (corner_color xUBR C2))
      (Triple (edge_color yFR E1) (Right) (edge_color yBR E1))
      (Triple (corner_color xDFR C2) (edge_color yDR E1) (corner_color xDRB C1)))
    (Triple
      (Triple (corner_color xUFL C1) (edge_color yUF E1) (corner_color xURF C2))
      (Triple (edge_color yFL E0) (Front) (edge_color yFR E0))
      (Triple (corner_color xDLF C2) (edge_color yDF E1) (corner_color xDFR C1))),
     Triple
    (Triple
      (Triple (corner_color xDLF C0) (edge_color yDF E0) (corner_color xDFR C0))
      (Triple (edge_color yDL E0) (Down) (edge_color yDR E0))
      (Triple (corner_color xDBL C0) (edge_color yDB E0) (corner_color xDRB C0)))
    (Triple
      (Triple (corner_color xULB C1) (edge_color yUL E1) (corner_color xUFL C2))
      (Triple (edge_color yBL E1) (Left) (edge_color yFL E1))
      (Triple (corner_color xDBL C2) (edge_color yDL E1) (corner_color xDLF C1)))
    (Triple
      (Triple (corner_color xUBR C1) (edge_color yUB E1) (corner_color xULB C2))
      (Triple (edge_color yBR E0) (Back) (edge_color yBL E0))
      (Triple (corner_color xDRB C2) (edge_color yDB E1) (corner_color xDBL C1))))
  end.

(** A clockwise turn moves cubies between slots and rotates them there. *)
Definition quarter_cube (f : face) (c : cube) : cube :=
  match c with
  | Cube xURF xUFL xULB xUBR xDFR xDLF xDBL xDRB
           yUR yUF yUL yUB yDR yDF yDL yDB yFR yFL yBL yBR =>
    match f with
    | Up =>
      Cube (shift_corner T0 xUBR) (shift_corner T0 xURF) (shift_corner T0 xUFL) (shift_corner T0 xULB)
           (shift_corner T0 xDFR) (shift_corner T0 xDLF) (shift_corner T0 xDBL) (shift_corner T0 xDRB)
           (shift_edge F0 yUB) (shift_edge F0 yUR) (shift_edge F0 yUF) (shift_edge F0 yUL) (shift_edge F0 yDR) (shift_edge F0 yDF)
           (shift_edge F0 yDL) (shift_edge F0 yDB) (shift_edge F0 yFR) (shift_edge F0 yFL) (shift_edge F0 yBL) (shift_edge F0 yBR)
    | Right =>
      Cube (shift_corner T2 xDFR) (shift_corner T0 xUFL) (shift_corner T0 xULB) (shift_corner T1 xURF)
           (shift_corner T1 xDRB) (shift_corner T0 xDLF) (shift_corner T0 xDBL) (shift_corner T2 xUBR)
           (shift_edge F0 yFR) (shift_edge F0 yUF) (shift_edge F0 yUL) (shift_edge F0 yUB) (shift_edge F0 yBR) (shift_edge F0 yDF)
           (shift_edge F0 yDL) (shift_edge F0 yDB) (shift_edge F0 yDR) (shift_edge F0 yFL) (shift_edge F0 yBL) (shift_edge F0 yUR)
    | Front =>
      Cube (shift_corner T1 xUFL) (shift_corner T2 xDLF) (shift_corner T0 xULB) (shift_corner T0 xUBR)
           (shift_corner T2 xURF) (shift_corner T1 xDFR) (shift_corner T0 xDBL) (shift_corner T0 xDRB)
           (shift_edge F0 yUR) (shift_edge F1 yFL) (shift_edge F0 yUL) (shift_edge F0 yUB) (shift_edge F0 yDR) (shift_edge F1 yFR)
           (shift_edge F0 yDL) (shift_edge F0 yDB) (shift_edge F1 yUF) (shift_edge F1 yDF) (shift_edge F0 yBL) (shift_edge F0 yBR)
    | Down =>
      Cube (shift_corner T0 xURF) (shift_corner T0 xUFL) (shift_corner T0 xULB) (shift_corner T0 xUBR)
           (shift_corner T0 xDLF) (shift_corner T0 xDBL) (shift_corner T0 xDRB) (shift_corner T0 xDFR)
           (shift_edge F0 yUR) (shift_edge F0 yUF) (shift_edge F0 yUL) (shift_edge F0 yUB) (shift_edge F0 yDF) (shift_edge F0 yDL)
           (shift_edge F0 yDB) (shift_edge F0 yDR) (shift_edge F0 yFR) (shift_edge F0 yFL) (shift_edge F0 yBL) (shift_edge F0 yBR)
    | Left =>
      Cube (shift_corner T0 xURF) (shift_corner T1 xULB) (shift_corner T2 xDBL) (shift_corner T0 xUBR)
           (shift_corner T0 xDFR) (shift_corner T2 xUFL) (shift_corner T1 xDLF) (shift_corner T0 xDRB)
           (shift_edge F0 yUR) (shift_edge F0 yUF) (shift_edge F0 yBL) (shift_edge F0 yUB) (shift_edge F0 yDR) (shift_edge F0 yDF)
           (shift_edge F0 yFL) (shift_edge F0 yDB) (shift_edge F0 yFR) (shift_edge F0 yUL) (shift_edge F0 yDL) (shift_edge F0 yBR)
    | Back =>
      Cube (shift_corner T0 xURF) (shift_corner T0 xUFL) (shift_corner T1 xUBR) (shift_corner T2 xDRB)
           (shift_corner T0 xDFR) (shift_corner T0 xDLF) (shift_corner T2 xULB) (shift_corner T1 xDBL)
           (shift_edge F0 yUR) (shift_edge F0 yUF) (shift_edge F0 yUL) (shift_edge F1 yBR) (shift_edge F0 yDR) (shift_edge F0 yDF)
           (shift_edge F0 yDL) (shift_edge F1 yBL) (shift_edge F0 yFR) (shift_edge F0 yFL) (shift_edge F1 yUB) (shift_edge F1 yDB)
    end
  end.

(** Which corner shows these three colors, and how far it is turned. A
    color triple that belongs to no corner cannot arise from a cube, so
    the default there is never read. *)
Definition corner_of (a : color) (b : color) (c : color) : corner_slot :=
  match a, b, c with
  | Up, Right, Front => (URF, T0)
  | Front, Up, Right => (URF, T1)
  | Right, Front, Up => (URF, T2)
  | Up, Front, Left => (UFL, T0)
  | Left, Up, Front => (UFL, T1)
  | Front, Left, Up => (UFL, T2)
  | Up, Left, Back => (ULB, T0)
  | Back, Up, Left => (ULB, T1)
  | Left, Back, Up => (ULB, T2)
  | Up, Back, Right => (UBR, T0)
  | Right, Up, Back => (UBR, T1)
  | Back, Right, Up => (UBR, T2)
  | Down, Front, Right => (DFR, T0)
  | Right, Down, Front => (DFR, T1)
  | Front, Right, Down => (DFR, T2)
  | Down, Left, Front => (DLF, T0)
  | Front, Down, Left => (DLF, T1)
  | Left, Front, Down => (DLF, T2)
  | Down, Back, Left => (DBL, T0)
  | Left, Down, Back => (DBL, T1)
  | Back, Left, Down => (DBL, T2)
  | Down, Right, Back => (DRB, T0)
  | Back, Down, Right => (DRB, T1)
  | Right, Back, Down => (DRB, T2)
  | _, _, _ => (URF, T0)
  end.

(** The same for an edge. *)
Definition edge_of (a : color) (b : color) : edge_slot :=
  match a, b with
  | Up, Right => (UR, F0)
  | Right, Up => (UR, F1)
  | Up, Front => (UF, F0)
  | Front, Up => (UF, F1)
  | Up, Left => (UL, F0)
  | Left, Up => (UL, F1)
  | Up, Back => (UB, F0)
  | Back, Up => (UB, F1)
  | Down, Right => (DR, F0)
  | Right, Down => (DR, F1)
  | Down, Front => (DF, F0)
  | Front, Down => (DF, F1)
  | Down, Left => (DL, F0)
  | Left, Down => (DL, F1)
  | Down, Back => (DB, F0)
  | Back, Down => (DB, F1)
  | Front, Right => (FR, F0)
  | Right, Front => (FR, F1)
  | Front, Left => (FL, F0)
  | Left, Front => (FL, F1)
  | Back, Left => (BL, F0)
  | Left, Back => (BL, F1)
  | Back, Right => (BR, F0)
  | Right, Back => (BR, F1)
  | _, _ => (UR, F0)
  end.

(** Read all twenty slots off the stickers. *)
Definition to_cubies (s : state) : cube :=
  match s with
  | (Triple
       (Triple (Triple u0 u1 u2) (Triple u3 u4 u5) (Triple u6 u7 u8))
       (Triple (Triple r0 r1 r2) (Triple r3 r4 r5) (Triple r6 r7 r8))
       (Triple (Triple f0 f1 f2) (Triple f3 f4 f5) (Triple f6 f7 f8)),
     Triple
       (Triple (Triple d0 d1 d2) (Triple d3 d4 d5) (Triple d6 d7 d8))
       (Triple (Triple l0 l1 l2) (Triple l3 l4 l5) (Triple l6 l7 l8))
       (Triple (Triple b0 b1 b2) (Triple b3 b4 b5) (Triple b6 b7 b8))) =>
    Cube (corner_of u8 r0 f2) (corner_of u6 f0 l2) (corner_of u0 l0 b2) (corner_of u2 b0 r2)
         (corner_of d2 f8 r6) (corner_of d0 l8 f6) (corner_of d6 b8 l6) (corner_of d8 r8 b6)
         (edge_of u5 r1) (edge_of u7 f1) (edge_of u3 l1) (edge_of u1 b1) (edge_of d5 r7) (edge_of d1 f7)
         (edge_of d3 l7) (edge_of d7 b7) (edge_of f5 r3) (edge_of f3 l5) (edge_of b5 l3) (edge_of b3 r5)
  end.
