(* Generated by scripts/generate_chain.py. Do not edit: run the script.
   The sequences were found by solving cubes with the extracted solver. None
   of that is trusted: every entry is rechecked below by computing what its
   sequence denotes, so a wrong table fails to compile rather than proving
   anything false. *)

From Stdlib Require Import Arith List Lia.
From Rubik Require Export Bounds.Chain.
Import ListNotations.

(** * Tables for solving with all eighteen moves

    One table per slot, in the order the chain finishes them: seven corners,
    then eleven edges. The eighth corner and the twelfth edge have no table;
    what they must hold is forced. *)

(** Finishing the URF slot, with nothing else finished. *)
Definition urf_table : ctable :=
  [((URF, T0), []);
   ((URF, T1), [(Right, Half); (Front, Half); (Down, CW); (Left, Half); (Down, CCW); (Front, Half); (Down, CW); (Left, Half); (Down, CCW); (Front, Half); (Up, CW); (Right, Half); (Right, CCW); (Down, CCW); (Left, Half); (Down, CW); (Right, CCW); (Up, CCW); (Right, Half)]);
   ((URF, T2), [(Up, CW); (Front, Half); (Up, CW); (Left, Half); (Down, CCW); (Back, Half); (Up, CCW); (Back, Half); (Up, CCW); (Front, Half); (Right, Half); (Back, Half); (Up, CCW); (Right, CCW); (Front, CCW); (Left, CW); (Back, Half); (Left, CCW); (Front, CW); (Right, CCW)]);
   ((UFL, T0), [(Left, Half); (Back, Half); (Up, CCW); (Back, Half); (Down, CW); (Left, Half); (Down, CCW); (Left, Half); (Up, CW); (Left, Half); (Up, CCW)]);
   ((UFL, T1), [(Up, Half); (Right, Half); (Back, Half); (Up, CCW); (Back, Half); (Up, Half); (Right, Half); (Up, CCW); (Right, Half); (Front, Half); (Down, Half); (Front, Half); (Up, CCW); (Right, CCW); (Front, CCW); (Left, CW); (Back, Half); (Left, CCW); (Front, CW); (Right, CCW)]);
   ((UFL, T2), [(Up, CW); (Right, Half); (Back, Half); (Up, CW); (Right, Half); (Down, CCW); (Left, Half); (Up, CW); (Front, Half); (Right, Half); (Up, CCW); (Right, Half); (Down, CW); (Right, CCW); (Down, CCW); (Left, Half); (Down, CW); (Right, CCW); (Up, CCW); (Right, Half)]);
   ((ULB, T0), [(Right, Half); (Up, CW); (Right, Half); (Up, CCW); (Back, Half); (Up, CW); (Right, Half); (Up, CW); (Right, Half); (Up, CCW); (Back, Half); (Right, Half); (Up, CCW); (Right, Half); (Up, CCW)]);
   ((ULB, T1), [(Right, Half); (Front, Half); (Up, CW); (Back, Half); (Down, CW); (Back, Half); (Up, Half); (Right, Half); (Down, CCW); (Front, Half); (Up, Half); (Right, Half); (Up, CCW); (Back, Half); (Up, CCW); (Front, CCW); (Down, CW); (Back, Half); (Down, CCW); (Front, CCW)]);
   ((ULB, T2), [(Down, CCW); (Front, Half); (Up, CCW); (Front, Half); (Up, Half); (Left, Half); (Down, CW); (Right, Half); (Up, Half); (Front, Half); (Up, CCW); (Front, Half); (Right, Half); (Up, CCW); (Right, CCW); (Down, CCW); (Left, Half); (Down, CW); (Right, CW)]);
   ((UBR, T0), [(Right, Half); (Down, CW); (Back, Half); (Down, CCW); (Back, Half); (Up, CW); (Back, Half); (Up, CCW); (Back, Half); (Right, Half); (Up, CCW)]);
   ((UBR, T1), [(Front, Half); (Up, CCW); (Right, Half); (Back, Half); (Down, CW); (Left, Half); (Up, CCW); (Front, Half); (Up, CW); (Left, Half); (Back, Half); (Up, Half); (Front, CCW); (Up, CCW); (Right, Half); (Up, CCW); (Right, Half); (Up, CW); (Front, CCW)]);
   ((UBR, T2), [(Down, CW); (Back, Half); (Right, Half); (Up, CCW); (Front, Half); (Up, CW); (Back, Half); (Down, CCW); (Left, Half); (Up, CCW); (Front, Half); (Right, Half); (Up, CCW); (Front, Half); (Up, CW); (Right, CCW); (Up, Half); (Right, CW); (Front, Half); (Right, CCW); (Up, Half); (Right, CCW)]);
   ((DFR, T0), [(Up, Half); (Front, Half); (Up, CCW); (Front, Half); (Down, CW); (Right, Half); (Down, CCW); (Right, Half); (Up, CW); (Right, Half); (Up, CCW); (Right, Half); (Up, Half)]);
   ((DFR, T1), [(Right, Half); (Down, CCW); (Front, Half); (Up, Half); (Front, Half); (Right, Half); (Down, CW); (Back, Half); (Right, Half); (Up, Half); (Right, Half); (Up, CCW); (Back, Half); (Right, Half); (Up, CCW); (Left, CCW); (Up, CW); (Right, Half); (Up, CCW); (Left, CW); (Up, CCW)]);
   ((DFR, T2), [(Right, Half); (Down, CW); (Back, Half); (Down, CCW); (Back, Half); (Down, CW); (Left, Half); (Down, CCW); (Back, Half); (Up, CW); (Back, Half); (Up, CCW); (Right, Half); (Right, CCW); (Down, CW); (Left, Half); (Down, CCW); (Right, CW); (Up, CCW)]);
   ((DLF, T0), [(Up, CCW); (Left, Half); (Up, CCW); (Left, Half); (Down, CW); (Front, Half); (Down, CCW); (Front, Half); (Up, CW); (Front, Half); (Up, CCW); (Front, Half); (Up, CW)]);
   ((DLF, T1), [(Up, CW); (Left, Half); (Down, CCW); (Back, Half); (Down, CW); (Back, Half); (Down, CCW); (Right, Half); (Down, CW); (Back, Half); (Up, CCW); (Back, Half); (Up, CW); (Left, CCW); (Down, CCW); (Right, Half); (Down, CW); (Left, CCW)]);
   ((DLF, T2), [(Front, Half); (Up, CCW); (Left, Half); (Front, Half); (Up, CCW); (Front, Half); (Down, CCW); (Front, Half); (Up, Half); (Left, Half); (Down, CW); (Front, Half); (Up, CCW); (Right, Half); (Up, Half); (Right, CCW); (Up, CCW); (Left, Half); (Up, CW); (Right, CCW)]);
   ((DBL, T0), [(Back, Half); (Up, CCW); (Back, Half); (Down, CW); (Left, Half); (Down, CCW); (Left, Half); (Up, CW); (Left, Half); (Up, CCW); (Left, Half)]);
   ((DBL, T1), [(Up, Half); (Back, Half); (Down, CCW); (Right, Half); (Down, CW); (Right, Half); (Down, CCW); (Front, Half); (Down, CW); (Right, Half); (Up, CCW); (Right, Half); (Up, CW); (Back, CCW); (Down, CCW); (Front, Half); (Down, CW); (Back, CCW); (Up, CCW)]);
   ((DBL, T2), [(Left, Half); (Up, CW); (Left, Half); (Back, Half); (Up, CW); (Front, Half); (Right, Half); (Down, Half); (Right, Half); (Down, CW); (Right, Half); (Down, CW); (Right, Half); (Down, Half); (Front, CCW); (Up, CCW); (Back, Half); (Up, CW); (Front, CCW); (Up, CCW)]);
   ((DRB, T0), [(Up, CW); (Back, Half); (Up, CW); (Back, Half); (Down, CCW); (Right, Half); (Down, CW); (Right, Half); (Up, CCW); (Right, Half); (Up, CW); (Right, Half); (Up, CCW)]);
   ((DRB, T1), [(Right, Half); (Left, Half); (Down, CCW); (Front, Half); (Down, CCW); (Front, Half); (Right, Half); (Down, Half); (Left, Half); (Up, CCW); (Back, Half); (Up, Half); (Right, Half); (Up, CW); (Right, Half); (Up, CCW); (Front, CCW); (Up, CW); (Back, Half); (Up, CCW); (Front, CW)]);
   ((DRB, T2), [(Back, Half); (Up, CCW); (Back, Half); (Down, CW); (Left, Half); (Down, CCW); (Left, Half); (Down, CW); (Front, Half); (Down, CCW); (Left, Half); (Up, CW); (Left, Half); (Up, CCW); (Back, CCW); (Down, CW); (Front, Half); (Down, CCW); (Back, CW)])].

(** Finishing the UFL slot, with 1 corners already finished. *)
Definition ufl_table : ctable :=
  [((UFL, T0), []);
   ((UFL, T1), [(Front, Half); (Right, Half); (Up, CW); (Front, Half); (Up, CCW); (Left, Half); (Up, CW); (Front, Half); (Up, CCW); (Right, Half); (Up, CW); (Front, Half); (Front, CCW); (Down, CCW); (Back, Half); (Down, CW); (Front, CCW); (Up, CCW); (Front, Half)]);
   ((UFL, T2), [(Down, CCW); (Front, Half); (Down, CW); (Back, Half); (Down, CCW); (Front, Half); (Down, CW); (Right, Half); (Right, CCW); (Front, Half); (Right, CCW); (Back, Half); (Right, CW); (Front, Half); (Right, CCW)]);
   ((ULB, T0), [(Right, Half); (Up, CW); (Left, Half); (Front, Half); (Down, CW); (Right, Half); (Front, Half); (Left, Half); (Front, Half); (Up, CW); (Back, Half); (Up, CCW); (Front, Half); (Right, Half); (Up, CCW)]);
   ((ULB, T1), [(Up, Half); (Right, Half); (Back, Half); (Up, CCW); (Back, Half); (Up, Half); (Right, Half); (Up, CW); (Back, Half); (Up, Half); (Right, Half); (Up, CCW); (Right, CCW); (Front, Half); (Right, CCW); (Back, Half); (Right, CW); (Front, Half); (Right, CCW)]);
   ((ULB, T2), [(Down, CW); (Front, Half); (Up, CW); (Back, Half); (Up, Half); (Right, Half); (Up, CCW); (Left, Half); (Up, CW); (Back, Half); (Up, CCW); (Right, Half); (Left, Half); (Up, CCW); (Front, CCW); (Down, CCW); (Back, Half); (Down, CW); (Front, CCW); (Up, CCW); (Front, Half)]);
   ((UBR, T0), [(Front, Half); (Up, CW); (Right, Half); (Down, Half); (Left, Half); (Back, Half); (Down, CW); (Left, Half); (Down, CW); (Right, Half); (Up, Half); (Front, Half); (Up, CCW); (Front, Half); (Up, CCW)]);
   ((UBR, T1), [(Up, Half); (Front, Half); (Down, CW); (Right, Half); (Down, CCW); (Right, Half); (Up, Half); (Front, Half); (Up, CW); (Left, Half); (Up, CW); (Right, Half); (Up, CCW); (Left, CCW); (Down, CW); (Right, Half); (Down, CCW); (Left, CCW)]);
   ((UBR, T2), [(Down, CW); (Back, Half); (Right, Half); (Down, CW); (Left, Half); (Front, Half); (Down, CCW); (Right, Half); (Up, CW); (Back, Half); (Down, CCW); (Back, Half); (Up, CW); (Right, Half); (Up, CCW); (Right, CCW); (Down, CW); (Left, Half); (Down, CCW); (Right, CCW)]);
   ((DFR, T0), [(Right, Half); (Down, CCW); (Front, Half); (Up, Half); (Front, Half); (Right, Half); (Down, CW); (Back, Half); (Right, Half); (Up, Half); (Right, Half); (Up, CCW); (Back, Half); (Up, Half)]);
   ((DFR, T1), [(Up, CCW); (Front, Half); (Right, Half); (Up, CCW); (Right, Half); (Up, Half); (Front, Half); (Up, CW); (Right, Half); (Up, Half); (Front, Half); (Up, CCW); (Front, Half); (Up, CCW); (Left, CCW); (Up, CW); (Right, Half); (Up, CCW); (Left, CW)]);
   ((DFR, T2), [(Right, Half); (Left, Half); (Down, CCW); (Front, Half); (Up, CCW); (Right, Half); (Back, Half); (Down, Half); (Front, Half); (Down, CW); (Left, Half); (Down, Half); (Back, Half); (Up, CCW); (Right, Half); (Up, CCW); (Right, CCW); (Down, CW); (Left, Half); (Down, CCW); (Right, CW)]);
   ((DLF, T0), [(Up, CCW); (Right, Half); (Up, CW); (Front, Half); (Up, Half); (Right, Half); (Up, CCW); (Right, Half); (Front, Half); (Up, Half); (Front, Half); (Up, CW); (Front, Half); (Right, Half); (Up, CCW)]);
   ((DLF, T1), [(Left, Half); (Front, Half); (Up, CCW); (Front, Half); (Up, Half); (Left, Half); (Up, CW); (Front, Half); (Up, Half); (Left, Half); (Up, CCW); (Left, Half); (Up, CCW); (Back, CCW); (Up, CW); (Front, Half); (Up, CCW); (Back, CW); (Up, CCW)]);
   ((DLF, T2), [(Back, Half); (Right, Half); (Down, CCW); (Front, Half); (Up, Half); (Front, Half); (Right, Half); (Up, CW); (Right, Half); (Down, Half); (Back, Half); (Down, CCW); (Back, Half); (Right, Half); (Up, CCW); (Front, CCW); (Down, CW); (Back, Half); (Down, CCW); (Front, CW); (Up, CCW)]);
   ((DBL, T0), [(Front, Half); (Up, CW); (Left, Half); (Up, Half); (Front, Half); (Up, CCW); (Front, Half); (Left, Half); (Up, Half); (Left, Half); (Up, CW); (Left, Half); (Front, Half); (Up, Half)]);
   ((DBL, T1), [(Down, CW); (Back, Half); (Down, CCW); (Right, Half); (Down, CCW); (Right, Half); (Up, Half); (Front, Half); (Down, CW); (Right, Half); (Up, CCW); (Right, Half); (Up, Half); (Back, CCW); (Down, CCW); (Front, Half); (Down, CW); (Back, CCW)]);
   ((DBL, T2), [(Down, CW); (Front, Half); (Down, CCW); (Front, Half); (Up, CCW); (Back, Half); (Up, CW); (Right, Half); (Down, CCW); (Right, Half); (Up, CW); (Front, Half); (Up, CCW); (Front, CCW); (Up, CCW); (Back, Half); (Up, CW); (Front, CCW)]);
   ((DRB, T0), [(Right, Half); (Front, Half); (Down, CW); (Front, Half); (Left, Half); (Down, CW); (Left, Half); (Down, CCW); (Left, Half); (Up, CW); (Left, Half); (Up, CCW); (Right, Half)]);
   ((DRB, T1), [(Down, Half); (Back, Half); (Up, CCW); (Back, Half); (Up, CW); (Back, Half); (Up, Half); (Left, Half); (Down, CCW); (Right, Half); (Down, CCW); (Front, Half); (Up, Half); (Right, CCW); (Down, CCW); (Left, Half); (Down, CW); (Right, CCW); (Up, CCW)]);
   ((DRB, T2), [(Down, Half); (Front, Half); (Down, CCW); (Front, Half); (Down, CCW); (Right, Half); (Up, CW); (Front, Half); (Down, CCW); (Front, Half); (Up, CW); (Left, Half); (Up, CCW); (Left, CCW); (Up, CCW); (Right, Half); (Up, CW); (Left, CCW); (Up, CCW)])].

(** Finishing the ULB slot, with 2 corners already finished. *)
Definition ulb_table : ctable :=
  [((ULB, T0), []);
   ((ULB, T1), [(Back, Half); (Down, CW); (Back, Half); (Down, CCW); (Right, Half); (Up, CW); (Right, CCW); (Up, CCW); (Back, Half); (Up, CCW); (Back, Half); (Up, CW); (Right, CCW)]);
   ((ULB, T2), [(Right, Half); (Up, CCW); (Front, Half); (Up, CW); (Back, Half); (Up, CCW); (Front, Half); (Up, CW); (Back, Half); (Down, CW); (Right, CCW); (Up, CW); (Right, CW); (Down, CCW); (Right, CCW); (Up, CCW); (Right, CCW)]);
   ((UBR, T0), [(Right, Half); (Up, Half); (Front, Half); (Down, CW); (Left, Half); (Down, CCW); (Front, Half); (Right, Half); (Up, CW); (Back, Half); (Up, Half); (Right, Half); (Up, CCW); (Right, Half); (Up, CCW)]);
   ((UBR, T1), [(Up, CW); (Right, Half); (Back, Half); (Down, CW); (Left, Half); (Up, CCW); (Left, Half); (Up, CW); (Back, Half); (Right, CCW); (Up, CW); (Right, CW); (Down, CCW); (Right, CCW); (Up, CCW); (Right, CCW)]);
   ((UBR, T2), [(Up, CW); (Front, Half); (Up, Half); (Front, Half); (Right, Half); (Up, CW); (Front, Half); (Up, Half); (Back, Half); (Up, CCW); (Front, Half); (Up, CCW); (Back, Half); (Right, CCW); (Up, CCW); (Back, Half); (Up, CCW); (Back, Half); (Up, CW); (Right, CCW)]);
   ((DFR, T0), [(Up, CCW); (Front, Half); (Right, Half); (Up, CCW); (Right, Half); (Up, Half); (Front, Half); (Up, CW); (Right, Half); (Up, Half); (Front, Half); (Up, CCW); (Front, Half); (Right, Half); (Up, CCW)]);
   ((DFR, T1), [(Front, Half); (Down, CCW); (Left, Half); (Down, Half); (Front, Half); (Up, CW); (Right, Half); (Up, Half); (Front, Half); (Down, CCW); (Left, Half); (Front, Half); (Up, CCW); (Front, Half); (Front, CCW); (Down, CCW); (Back, Half); (Down, CW); (Front, CCW); (Up, CCW)]);
   ((DFR, T2), [(Left, Half); (Back, Half); (Down, CCW); (Right, Half); (Back, Half); (Up, CCW); (Front, Half); (Up, CW); (Left, Half); (Down, CCW); (Back, Half); (Up, CW); (Right, Half); (Up, CCW); (Back, CCW); (Up, CCW); (Front, Half); (Up, CW); (Back, CCW); (Up, CCW)]);
   ((DLF, T0), [(Left, Half); (Front, Half); (Up, CCW); (Front, Half); (Up, Half); (Left, Half); (Up, CW); (Front, Half); (Up, Half); (Left, Half); (Up, CCW); (Left, Half); (Front, Half); (Up, Half)]);
   ((DLF, T1), [(Left, Half); (Up, Half); (Front, Half); (Up, CW); (Front, Half); (Down, CW); (Right, Half); (Up, Half); (Back, Half); (Down, CCW); (Left, Half); (Up, CW); (Right, Half); (Up, CCW); (Back, CCW); (Up, CW); (Front, Half); (Up, CCW); (Back, CW)]);
   ((DLF, T2), [(Down, CCW); (Left, Half); (Front, Half); (Up, CW); (Left, Half); (Down, Half); (Back, Half); (Down, CCW); (Right, Half); (Up, Half); (Front, Half); (Up, CCW); (Front, Half); (Up, CCW); (Front, CCW); (Down, CW); (Back, Half); (Down, CCW); (Front, CW)]);
   ((DBL, T0), [(Down, CCW); (Back, Half); (Right, Half); (Down, CCW); (Right, Half); (Down, Half); (Left, Half); (Back, Half); (Up, CCW); (Left, Half); (Up, Half); (Back, Half); (Up, CCW); (Left, Half); (Up, CCW)]);
   ((DBL, T1), [(Left, Half); (Up, CW); (Left, Half); (Up, CCW); (Left, Half); (Up, Half); (Back, Half); (Up, CW); (Left, Half); (Up, CW); (Left, Half); (Up, Half); (Back, Half); (Right, CCW); (Up, CW); (Left, Half); (Up, CCW); (Right, CW); (Up, CCW)]);
   ((DBL, T2), [(Left, Half); (Front, Half); (Down, CCW); (Left, Half); (Up, Half); (Back, Half); (Up, CW); (Left, Half); (Down, Half); (Front, Half); (Down, CCW); (Left, Half); (Up, CCW); (Left, CCW); (Down, CW); (Right, Half); (Down, CCW); (Left, CW); (Up, CCW)]);
   ((DRB, T0), [(Back, Half); (Right, Half); (Up, CW); (Right, Half); (Up, Half); (Back, Half); (Up, CCW); (Right, Half); (Up, Half); (Back, Half); (Up, CW); (Back, Half); (Right, Half); (Up, Half)]);
   ((DRB, T1), [(Down, CW); (Back, Half); (Left, Half); (Up, CW); (Left, Half); (Down, CCW); (Back, Half); (Right, Half); (Down, CCW); (Left, Half); (Down, CW); (Right, Half); (Up, CW); (Right, Half); (Up, CCW); (Right, CCW); (Down, CCW); (Left, Half); (Down, CW); (Right, CCW)]);
   ((DRB, T2), [(Down, Half); (Back, Half); (Down, CW); (Left, Half); (Up, CW); (Front, Half); (Left, Half); (Down, Half); (Back, Half); (Right, Half); (Down, CCW); (Left, Half); (Up, CW); (Right, Half); (Up, CCW); (Left, CCW); (Up, CCW); (Right, Half); (Up, CW); (Left, CCW)])].

(** Finishing the UBR slot, with 3 corners already finished. *)
Definition ubr_table : ctable :=
  [((UBR, T0), []);
   ((UBR, T1), [(Back, Half); (Down, Half); (Back, Half); (Down, CW); (Back, Half); (Down, CW); (Left, Half); (Up, CCW); (Left, Half); (Up, CCW); (Front, Half); (Up, Half); (Back, CCW); (Up, CCW); (Front, Half); (Up, CW); (Back, CCW)]);
   ((UBR, T2), [(Front, Half); (Down, Half); (Back, Half); (Down, CW); (Left, Half); (Down, CW); (Left, Half); (Up, CCW); (Front, Half); (Up, CCW); (Front, Half); (Up, Half); (Front, CCW); (Down, CCW); (Back, Half); (Down, CW); (Front, CCW)]);
   ((DFR, T0), [(Front, Half); (Down, CW); (Right, Half); (Up, Half); (Right, Half); (Front, Half); (Down, CCW); (Left, Half); (Front, Half); (Up, Half); (Front, Half); (Up, CW); (Left, Half); (Up, Half)]);
   ((DFR, T1), [(Down, CW); (Front, Half); (Down, CCW); (Front, Half); (Back, Half); (Right, Half); (Down, CW); (Right, Half); (Up, CCW); (Back, Half); (Up, CW); (Back, Half); (Up, CW); (Front, Half); (Up, CCW); (Front, CCW); (Down, CCW); (Back, Half); (Down, CW); (Front, CCW)]);
   ((DFR, T2), [(Back, Half); (Up, CCW); (Right, Half); (Up, CCW); (Right, Half); (Up, Half); (Front, Half); (Up, CW); (Right, Half); (Up, Half); (Front, Half); (Up, CCW); (Front, Half); (Right, Half); (Up, CCW); (Back, CCW); (Up, CCW); (Front, Half); (Up, CW); (Back, CCW)]);
   ((DLF, T0), [(Front, Half); (Right, Half); (Down, CCW); (Right, Half); (Back, Half); (Down, CCW); (Back, Half); (Down, CW); (Back, Half); (Up, CCW); (Back, Half); (Up, CW); (Front, Half)]);
   ((DLF, T1), [(Left, Half); (Up, CW); (Left, Half); (Up, Half); (Back, Half); (Up, CCW); (Right, Half); (Up, Half); (Right, Half); (Back, Half); (Up, CCW); (Left, Half); (Up, CCW); (Right, Half); (Left, CCW); (Down, CCW); (Right, Half); (Down, CW); (Left, CCW); (Up, CCW)]);
   ((DLF, T2), [(Front, Half); (Up, CCW); (Front, Half); (Up, Half); (Left, Half); (Up, CW); (Front, Half); (Up, Half); (Left, Half); (Up, CCW); (Left, Half); (Front, Half); (Up, CCW); (Right, Half); (Right, CCW); (Up, CCW); (Left, Half); (Up, CW); (Right, CCW); (Up, CCW)]);
   ((DBL, T0), [(Right, Half); (Up, CCW); (Back, Half); (Up, Half); (Right, Half); (Up, CW); (Right, Half); (Back, Half); (Up, Half); (Back, Half); (Up, CCW); (Back, Half); (Right, Half); (Up, Half)]);
   ((DBL, T1), [(Back, Half); (Up, CCW); (Back, Half); (Down, CW); (Left, Half); (Down, CCW); (Left, Half); (Up, CW); (Left, Half); (Up, CCW); (Left, Half); (Up, CW); (Left, Half); (Up, CCW); (Right, CCW); (Up, CW); (Left, Half); (Up, CCW); (Right, CW)]);
   ((DBL, T2), [(Left, Half); (Up, Half); (Front, Half); (Down, CW); (Right, Half); (Down, CCW); (Right, Half); (Up, Half); (Front, Half); (Up, CW); (Left, Half); (Up, CW); (Right, Half); (Up, CCW); (Left, CCW); (Down, CW); (Right, Half); (Down, CCW); (Left, CW)]);
   ((DRB, T0), [(Down, CCW); (Front, Half); (Down, CW); (Right, Half); (Up, Half); (Right, Half); (Front, Half); (Up, CCW); (Front, Half); (Right, Half); (Up, Half); (Right, Half); (Up, CW); (Front, Half); (Up, CCW)]);
   ((DRB, T1), [(Right, Half); (Down, CW); (Back, Half); (Down, CCW); (Back, Half); (Up, CW); (Back, Half); (Down, CCW); (Right, Half); (Down, CW); (Back, Half); (Up, CCW); (Right, Half); (Front, CCW); (Up, CW); (Back, Half); (Up, CCW); (Front, CW); (Up, CCW)]);
   ((DRB, T2), [(Left, Half); (Up, CW); (Left, Half); (Up, CCW); (Left, Half); (Up, Half); (Back, Half); (Down, CW); (Front, Half); (Down, CW); (Right, Half); (Down, Half); (Back, Half); (Back, CCW); (Down, CW); (Front, Half); (Down, CCW); (Back, CW); (Up, CCW)])].

(** Finishing the DFR slot, with 4 corners already finished. *)
Definition dfr_table : ctable :=
  [((DFR, T0), []);
   ((DFR, T1), [(Up, CCW); (Right, Half); (Up, CW); (Right, Half); (Down, Half); (Right, Half); (Up, CCW); (Right, Half); (Up, CW); (Right, Half); (Right, CCW); (Up, CCW); (Right, CW); (Down, Half); (Right, CCW); (Up, CW); (Right, CCW)]);
   ((DFR, T2), [(Front, Half); (Up, CW); (Front, Half); (Up, CCW); (Right, Half); (Down, CW); (Right, CCW); (Up, CCW); (Right, Half); (Down, CCW); (Right, Half); (Up, CW); (Right, CCW)]);
   ((DLF, T0), [(Left, Half); (Back, Half); (Up, CCW); (Left, Half); (Front, Half); (Back, Half); (Up, CW); (Back, Half); (Down, CCW); (Front, Half); (Right, Half); (Up, CCW); (Front, Half); (Right, Half); (Up, CCW)]);
   ((DLF, T1), [(Right, Half); (Down, CW); (Right, Half); (Down, CW); (Left, Half); (Down, CCW); (Back, Half); (Up, CW); (Back, Half); (Right, Half); (Down, Half); (Left, Half); (Down, Half); (Right, CCW); (Up, CCW); (Right, Half); (Down, CCW); (Right, Half); (Up, CW); (Right, CCW)]);
   ((DLF, T2), [(Up, Half); (Back, Half); (Up, CW); (Right, Half); (Up, Half); (Left, Half); (Front, Half); (Down, CCW); (Left, Half); (Front, Half); (Down, Half); (Front, Half); (Up, CCW); (Right, CCW); (Up, CCW); (Right, CW); (Down, Half); (Right, CCW); (Up, CW); (Right, CCW)]);
   ((DBL, T0), [(Back, Half); (Up, Half); (Back, Half); (Right, Half); (Up, CCW); (Right, Half); (Back, Half); (Right, Half); (Back, Half); (Up, Half); (Right, Half); (Up, CW); (Back, Half); (Up, Half); (Right, Half); (Up, CCW)]);
   ((DBL, T1), [(Down, CCW); (Right, Half); (Down, CW); (Right, Half); (Up, CW); (Left, Half); (Up, CCW); (Front, Half); (Down, CW); (Front, Half); (Up, CCW); (Right, Half); (Up, CW); (Right, CCW); (Up, CW); (Left, Half); (Up, CCW); (Right, CCW)]);
   ((DBL, T2), [(Back, Half); (Up, CCW); (Back, Half); (Down, CW); (Left, Half); (Down, CCW); (Left, Half); (Up, CW); (Left, Half); (Up, CCW); (Left, Half); (Up, CCW); (Back, Half); (Up, CW); (Front, CCW); (Up, CCW); (Back, Half); (Up, CW); (Front, CW)]);
   ((DRB, T0), [(Back, Half); (Up, Half); (Right, Half); (Up, CW); (Right, Half); (Front, Half); (Up, CW); (Back, Half); (Up, CCW); (Front, Half); (Up, Half); (Right, Half); (Up, CW); (Right, Half); (Up, CCW)]);
   ((DRB, T1), [(Right, Half); (Up, CCW); (Front, Half); (Up, Half); (Back, Half); (Left, Half); (Down, CW); (Left, Half); (Down, Half); (Back, Half); (Up, CCW); (Left, Half); (Down, Half); (Front, Half); (Right, CCW); (Up, Half); (Right, CCW); (Back, Half); (Right, CW); (Up, Half); (Right, CCW)]);
   ((DRB, T2), [(Front, Half); (Back, Half); (Up, CW); (Left, Half); (Down, CCW); (Right, Half); (Down, Half); (Front, Half); (Down, CW); (Front, Half); (Down, CW); (Front, Half); (Down, Half); (Left, CCW); (Up, CCW); (Right, Half); (Up, CW); (Left, CCW); (Up, CCW); (Front, Half)])].

(** Finishing the DLF slot, with 5 corners already finished. *)
Definition dlf_table : ctable :=
  [((DLF, T0), []);
   ((DLF, T1), [(Right, Half); (Up, CW); (Front, Half); (Up, CCW); (Back, Half); (Up, CW); (Front, Half); (Up, CCW); (Right, CCW); (Front, Half); (Right, CW); (Back, Half); (Right, CCW); (Front, Half); (Right, CCW)]);
   ((DLF, T2), [(Left, Half); (Up, CW); (Left, Half); (Up, CCW); (Front, Half); (Down, CW); (Front, CCW); (Up, CCW); (Front, Half); (Down, CCW); (Front, Half); (Up, CW); (Front, CCW)]);
   ((DBL, T0), [(Right, Half); (Down, CW); (Right, Half); (Front, Half); (Up, CW); (Front, Half); (Left, Half); (Front, Half); (Right, Half); (Up, CW); (Back, Half); (Up, CCW); (Right, Half); (Front, Half); (Up, CCW)]);
   ((DBL, T1), [(Back, Half); (Down, CCW); (Front, Half); (Right, Half); (Up, CW); (Front, Half); (Left, Half); (Up, CW); (Front, Half); (Down, CCW); (Right, Half); (Up, Half); (Front, CCW); (Up, CCW); (Front, Half); (Down, CCW); (Front, Half); (Up, CW); (Front, CCW)]);
   ((DBL, T2), [(Up, Half); (Right, Half); (Left, Half); (Down, CCW); (Right, Half); (Down, Half); (Front, Half); (Down, CCW); (Left, Half); (Up, Half); (Back, Half); (Up, CCW); (Back, Half); (Right, Half); (Up, Half); (Right, CCW); (Front, Half); (Right, CW); (Back, Half); (Right, CCW); (Front, Half); (Right, CCW)]);
   ((DRB, T0), [(Back, Half); (Up, Half); (Back, Half); (Right, Half); (Up, CW); (Right, Half); (Down, Half); (Front, Half); (Right, Half); (Front, Half); (Right, Half); (Up, CCW); (Front, Half); (Down, Half); (Right, Half); (Up, CCW)]);
   ((DRB, T1), [(Front, Half); (Up, CCW); (Left, Half); (Down, CW); (Right, Half); (Back, Half); (Up, CW); (Back, Half); (Down, CCW); (Back, Half); (Up, CW); (Back, Half); (Up, CCW); (Back, Half); (Right, Half); (Up, CCW); (Right, CCW); (Up, CCW); (Left, Half); (Up, CW); (Right, CW)]);
   ((DRB, T2), [(Down, CCW); (Right, Half); (Down, CCW); (Right, Half); (Down, Half); (Right, Half); (Front, Half); (Down, CCW); (Front, Half); (Up, Half); (Left, Half); (Up, CCW); (Left, Half); (Up, CCW); (Left, CCW); (Up, CCW); (Right, Half); (Up, CW); (Left, CW)])].

(** Finishing the DBL slot, with 6 corners already finished. *)
Definition dbl_table : ctable :=
  [((DBL, T0), []);
   ((DBL, T1), [(Up, CW); (Right, Half); (Up, CW); (Right, Half); (Up, CCW); (Back, Half); (Up, CCW); (Left, Half); (Down, CCW); (Right, Half); (Front, Half); (Left, Half); (Up, CCW); (Right, CCW); (Back, CCW); (Left, CW); (Front, Half); (Left, CCW); (Back, CW); (Right, CCW)]);
   ((DBL, T2), [(Right, Half); (Front, Half); (Up, CW); (Front, Half); (Up, CCW); (Back, Half); (Up, CW); (Front, Half); (Up, CCW); (Front, Half); (Up, CW); (Front, Half); (Front, CCW); (Up, CCW); (Back, Half); (Up, CW); (Front, CCW); (Up, CCW); (Right, Half)]);
   ((DRB, T0), [(Back, Half); (Up, Half); (Right, Half); (Down, CW); (Left, Half); (Front, Half); (Down, CCW); (Right, Half); (Up, CW); (Left, Half); (Up, Half); (Back, Half); (Up, CCW); (Back, Half); (Up, CCW)]);
   ((DRB, T1), [(Down, CCW); (Back, Half); (Up, CW); (Left, Half); (Up, CCW); (Front, Half); (Up, CCW); (Back, Half); (Down, Half); (Back, Half); (Left, Half); (Up, CW); (Front, Half); (Up, CW); (Front, CCW); (Up, CCW); (Back, Half); (Up, CW); (Front, CCW); (Up, CCW); (Right, Half)]);
   ((DRB, T2), [(Down, Half); (Front, Half); (Down, CCW); (Right, Half); (Down, Half); (Back, Half); (Up, CCW); (Left, Half); (Up, Half); (Front, Half); (Up, CW); (Front, Half); (Back, Half); (Right, CCW); (Back, CCW); (Left, CW); (Front, Half); (Left, CCW); (Back, CW); (Right, CCW)])].

(** Finishing the UR slot, with all eight corners already finished. *)
Definition ur_table : etable :=
  [((UR, F0), []);
   ((UR, F1), [(Right, Half); (Down, CCW); (Right, Half); (Up, CCW); (Back, Half); (Up, CW); (Front, Half); (Up, CCW); (Back, Half); (Up, CW); (Right, Half); (Down, CW); (Right, CCW); (Back, CW); (Left, CCW); (Up, Half); (Left, CW); (Back, CCW); (Right, CCW)]);
   ((UF, F0), [(Right, Half); (Up, CCW); (Front, Half); (Left, Half); (Back, Half); (Down, CW); (Back, Half); (Left, Half); (Front, Half); (Up, Half); (Right, Half)]);
   ((UF, F1), [(Front, Half); (Down, CCW); (Front, Half); (Right, Half); (Back, Half); (Right, Half); (Up, CCW); (Left, Half); (Up, CW); (Right, Half); (Up, CCW); (Back, Half); (Right, CCW); (Back, CW); (Left, CCW); (Up, Half); (Left, CW); (Back, CCW); (Right, CCW)]);
   ((UL, F0), [(Right, Half); (Up, Half); (Front, Half); (Left, Half); (Back, Half); (Down, CCW); (Back, Half); (Left, Half); (Front, Half); (Up, CW); (Right, Half)]);
   ((UL, F1), [(Front, Half); (Up, Half); (Front, Half); (Right, Half); (Front, Half); (Up, Half); (Front, Half); (Right, Half); (Up, Half); (Back, CCW); (Up, CCW); (Right, CW); (Up, CW); (Right, Half); (Back, CW); (Right, CW); (Up, CCW); (Right, CCW)]);
   ((UB, F0), [(Right, Half); (Up, CW); (Front, Half); (Right, Half); (Front, Half); (Up, Half); (Front, Half); (Right, Half); (Front, Half); (Up, CW); (Right, Half)]);
   ((UB, F1), [(Right, Half); (Front, Half); (Up, CCW); (Back, Half); (Right, Half); (Up, CCW); (Front, Half); (Up, CW); (Right, Half); (Back, Half); (Up, CW); (Front, Half); (Right, Half); (Right, CCW); (Front, CCW); (Left, CW); (Up, Half); (Left, CCW); (Front, CW); (Right, CW)]);
   ((DR, F0), [(Left, Half); (Back, Half); (Down, CCW); (Right, Half); (Back, Half); (Left, Half); (Up, CCW); (Front, Half)]);
   ((DR, F1), [(Up, CCW); (Front, Half); (Down, CW); (Left, Half); (Down, CCW); (Right, Half); (Down, CW); (Left, Half); (Down, CCW); (Front, Half); (Up, Half); (Right, CCW); (Back, CW); (Left, CCW); (Up, Half); (Left, CW); (Back, CCW); (Right, CW); (Up, CCW)]);
   ((DF, F0), [(Right, Half); (Back, Half); (Left, Half); (Down, CCW); (Left, Half); (Back, Half); (Right, Half); (Up, CCW)]);
   ((DF, F1), [(Front, Half); (Down, CCW); (Front, Half); (Down, CW); (Right, Half); (Front, Half); (Up, CW); (Front, Half); (Up, CCW); (Front, Half); (Right, CCW); (Back, CCW); (Left, CW); (Down, Half); (Left, CCW); (Back, CW); (Right, CCW)]);
   ((DL, F0), [(Up, CW); (Front, Half); (Right, Half); (Back, Half); (Down, CCW); (Back, Half); (Right, Half); (Front, Half); (Up, Half)]);
   ((DL, F1), [(Down, CW); (Right, Half); (Back, Half); (Up, CW); (Right, Half); (Up, CCW); (Front, Half); (Up, CW); (Right, Half); (Down, CCW); (Right, Half); (Front, CCW); (Right, CCW); (Back, CW); (Down, Half); (Back, CCW); (Right, CW); (Front, CCW); (Up, CCW)]);
   ((DB, F0), [(Up, Half); (Right, Half); (Front, Half); (Left, Half); (Down, CCW); (Left, Half); (Front, Half); (Right, Half); (Up, CW)]);
   ((DB, F1), [(Up, Half); (Right, Half); (Front, Half); (Up, CCW); (Front, Half); (Up, CW); (Back, Half); (Up, CCW); (Front, Half); (Up, CW); (Front, Half); (Right, Half); (Up, Half); (Right, CCW); (Front, CW); (Left, CCW); (Down, Half); (Left, CW); (Front, CCW); (Right, CW)]);
   ((FR, F0), [(Down, CW); (Front, Half); (Left, Half); (Up, CW); (Right, Half); (Back, Half); (Left, Half); (Up, CW); (Front, Half); (Up, Half); (Front, Half); (Up, Half); (Right, CCW); (Front, Half); (Up, Half); (Front, Half); (Right, CCW); (Up, CCW)]);
   ((FR, F1), [(Right, Half); (Back, Half); (Up, CW); (Left, Half); (Up, CCW); (Front, Half); (Down, CW); (Back, Half); (Right, Half); (Up, Half); (Back, Half); (Left, Half); (Front, Half); (Back, CCW); (Left, Half); (Front, CCW); (Left, CCW); (Up, CW); (Left, CCW); (Up, CCW); (Back, CCW); (Up, Half)]);
   ((FL, F0), [(Right, Half); (Up, CW); (Front, Half); (Back, Half); (Up, CCW); (Front, Half); (Up, CW); (Back, Half); (Up, Half); (Right, Half); (Right, CCW); (Up, Half); (Front, Half); (Up, Half); (Right, CW); (Up, CW)]);
   ((FL, F1), [(Right, Half); (Down, CCW); (Left, Half); (Up, CCW); (Left, Half); (Up, CCW); (Front, Half); (Down, CW); (Front, Half); (Up, Half); (Right, Half); (Up, Half); (Left, CCW); (Front, CCW); (Up, CW); (Front, CW); (Up, Half); (Left, CW); (Up, CW); (Front, CW); (Up, CCW)]);
   ((BL, F0), [(Up, CW); (Front, Half); (Down, CW); (Left, Half); (Front, Half); (Up, Half); (Back, Half); (Right, Half); (Up, Half); (Front, Half); (Down, CCW); (Left, CCW); (Down, Half); (Front, Half); (Up, Half); (Right, CCW); (Up, CW)]);
   ((BL, F1), [(Front, Half); (Up, CW); (Front, Half); (Up, CCW); (Down, CCW); (Left, Half); (Front, Half); (Left, Half); (Up, CCW); (Front, Half); (Down, CCW); (Left, Half); (Back, CCW); (Down, Half); (Front, CCW); (Right, CCW); (Up, CW); (Right, CCW); (Up, CCW); (Front, CCW)]);
   ((BR, F0), [(Up, CCW); (Front, Half); (Up, CCW); (Right, Half); (Back, Half); (Right, Half); (Down, CW); (Left, Half); (Down, CCW); (Right, Half); (Back, Half); (Right, Half); (Up, CCW); (Right, CCW); (Front, Half); (Up, Half); (Front, Half); (Right, CW); (Up, CCW)]);
   ((BR, F1), [(Up, CW); (Front, Half); (Right, Half); (Up, CCW); (Left, Half); (Back, Half); (Down, CCW); (Front, Half); (Up, CW); (Left, Half); (Front, Half); (Up, CW); (Right, Half); (Up, Half); (Front, CCW); (Left, CW); (Back, CCW); (Down, Half); (Front, Half); (Back, CCW); (Right, CCW); (Front, CCW); (Up, CCW)])].

(** Finishing the UF slot, with all eight corners and 1 edges already finished. *)
Definition uf_table : etable :=
  [((UF, F0), []);
   ((UF, F1), [(Front, Half); (Down, CCW); (Front, Half); (Up, CW); (Left, Half); (Up, CCW); (Back, Half); (Right, Half); (Up, CCW); (Left, Half); (Front, Half); (Left, Half); (Back, Half); (Right, Half); (Left, CCW); (Front, CW); (Left, CCW); (Front, Half); (Right, CW); (Front, CCW); (Right, CCW)]);
   ((UL, F0), [(Front, Half); (Up, CCW); (Right, Half); (Back, Half); (Left, Half); (Down, CW); (Left, Half); (Back, Half); (Right, Half); (Up, Half); (Front, Half)]);
   ((UL, F1), [(Front, Half); (Left, Half); (Up, Half); (Left, Half); (Down, CCW); (Front, Half); (Down, CW); (Front, Half); (Up, CCW); (Front, Half); (Up, CW); (Front, Half); (Left, Half); (Up, Half); (Left, CCW); (Front, CW); (Left, CCW); (Front, Half); (Right, CW); (Front, CCW); (Right, CCW)]);
   ((UB, F0), [(Front, Half); (Up, Half); (Right, Half); (Back, Half); (Left, Half); (Down, CCW); (Left, Half); (Back, Half); (Right, Half); (Up, CW); (Front, Half)]);
   ((UB, F1), [(Right, Half); (Front, Half); (Down, CW); (Front, Half); (Left, Half); (Up, CW); (Left, Half); (Down, CCW); (Back, Half); (Down, CCW); (Front, Half); (Back, Half); (Up, CW); (Left, CCW); (Up, CW); (Front, CCW); (Down, Half); (Right, CCW); (Back, Half); (Down, CCW); (Front, CCW); (Right, CCW)]);
   ((DR, F0), [(Up, Half); (Front, Half); (Left, Half); (Back, Half); (Down, CCW); (Back, Half); (Left, Half); (Front, Half); (Up, CW)]);
   ((DR, F1), [(Up, Half); (Front, Half); (Down, CW); (Left, Half); (Down, CCW); (Right, Half); (Down, CW); (Left, Half); (Down, CCW); (Front, Half); (Up, Half); (Right, CCW); (Back, CW); (Left, CCW); (Up, Half); (Left, CW); (Back, CCW); (Right, CW)]);
   ((DF, F0), [(Down, CCW); (Front, Half); (Right, Half); (Back, Half); (Up, CCW); (Left, Half); (Back, Half); (Right, Half)]);
   ((DF, F1), [(Up, CCW); (Left, Half); (Down, CW); (Back, Half); (Down, CCW); (Front, Half); (Down, CW); (Back, Half); (Down, CCW); (Left, Half); (Up, Half); (Front, CCW); (Right, CW); (Back, CCW); (Up, Half); (Back, CW); (Right, CCW); (Front, CW); (Up, CCW)]);
   ((DL, F0), [(Front, Half); (Right, Half); (Back, Half); (Down, CCW); (Back, Half); (Right, Half); (Front, Half); (Up, CCW)]);
   ((DL, F1), [(Front, Half); (Right, Half); (Down, CW); (Right, Half); (Down, CCW); (Left, Half); (Down, CW); (Right, Half); (Down, CCW); (Right, Half); (Front, CCW); (Right, CCW); (Back, CW); (Down, Half); (Back, CCW); (Right, CW); (Front, CCW)]);
   ((DB, F0), [(Up, CW); (Right, Half); (Front, Half); (Left, Half); (Down, CCW); (Left, Half); (Front, Half); (Right, Half); (Up, Half)]);
   ((DB, F1), [(Up, CW); (Front, Half); (Right, Half); (Up, CW); (Right, Half); (Front, Half); (Left, Half); (Back, Half); (Down, CW); (Right, Half); (Right, CCW); (Left, CCW); (Front, CCW); (Down, Half); (Front, CW); (Right, CCW); (Left, CCW); (Up, CCW)]);
   ((FR, F0), [(Up, CCW); (Down, CW); (Front, Half); (Left, Half); (Up, CW); (Right, Half); (Back, Half); (Left, Half); (Up, CW); (Front, Half); (Up, Half); (Front, Half); (Up, Half); (Right, CCW); (Front, Half); (Up, Half); (Front, Half); (Right, CCW)]);
   ((FR, F1), [(Down, CW); (Left, Half); (Front, Half); (Right, Half); (Down, Half); (Front, Half); (Down, CW); (Right, Half); (Down, CCW); (Right, Half); (Up, CW); (Left, Half); (Down, Half); (Back, CCW); (Left, Half); (Front, CCW); (Left, CCW); (Up, CW); (Left, CCW); (Up, CCW); (Back, CCW); (Up, CCW)]);
   ((FL, F0), [(Up, CCW); (Right, Half); (Up, CW); (Front, Half); (Back, Half); (Up, CCW); (Front, Half); (Up, CW); (Back, Half); (Up, Half); (Right, Half); (Right, CCW); (Up, Half); (Front, Half); (Up, Half); (Right, CW); (Up, Half)]);
   ((FL, F1), [(Right, Half); (Left, Half); (Back, Half); (Down, CCW); (Right, Half); (Down, Half); (Back, Half); (Left, Half); (Front, Half); (Up, Half); (Right, Half); (Left, CCW); (Front, CCW); (Up, CW); (Front, CW); (Up, Half); (Left, CW); (Up, CW); (Front, CW)]);
   ((BL, F0), [(Front, Half); (Down, CW); (Left, Half); (Front, Half); (Up, Half); (Back, Half); (Right, Half); (Up, Half); (Front, Half); (Down, CCW); (Left, CCW); (Down, Half); (Front, Half); (Up, Half); (Right, CCW); (Up, Half)]);
   ((BL, F1), [(Front, Half); (Down, Half); (Left, Half); (Down, CCW); (Left, Half); (Up, CCW); (Right, Half); (Back, Half); (Up, CW); (Left, Half); (Up, Half); (Back, Half); (Back, CCW); (Left, CCW); (Back, CCW); (Left, CW); (Down, CCW); (Right, CCW); (Up, Half); (Right, CCW)]);
   ((BR, F0), [(Up, Half); (Front, Half); (Up, CCW); (Right, Half); (Back, Half); (Right, Half); (Down, CW); (Left, Half); (Down, CCW); (Right, Half); (Back, Half); (Right, Half); (Up, CCW); (Right, CCW); (Front, Half); (Up, Half); (Front, Half); (Right, CW)]);
   ((BR, F1), [(Front, Half); (Right, Half); (Up, CCW); (Left, Half); (Back, Half); (Down, CCW); (Front, Half); (Up, CW); (Left, Half); (Front, Half); (Up, CW); (Right, Half); (Up, Half); (Front, CCW); (Left, CW); (Back, CCW); (Down, Half); (Front, Half); (Back, CCW); (Right, CCW); (Front, CCW)])].

(** Finishing the UL slot, with all eight corners and 2 edges already finished. *)
Definition ul_table : etable :=
  [((UL, F0), []);
   ((UL, F1), [(Front, Half); (Down, CCW); (Front, Half); (Down, CW); (Back, Half); (Up, CCW); (Back, Half); (Up, CW); (Right, Half); (Front, Half); (Up, CW); (Front, Half); (Back, Half); (Up, CCW); (Left, CCW); (Back, CCW); (Left, CW); (Back, Half); (Right, CCW); (Back, CW); (Right, CCW)]);
   ((UB, F0), [(Up, Half); (Front, Half); (Left, Half); (Back, Half); (Down, CW); (Back, Half); (Left, Half); (Front, Half); (Up, CCW)]);
   ((UB, F1), [(Front, Half); (Up, CCW); (Front, Half); (Back, Half); (Left, Half); (Up, CW); (Back, Half); (Right, Half); (Down, CW); (Front, Half); (Up, CCW); (Back, Half); (Left, CCW); (Back, CCW); (Left, CW); (Back, Half); (Right, CCW); (Back, CW); (Right, CCW)]);
   ((DR, F0), [(Up, CW); (Front, Half); (Left, Half); (Back, Half); (Down, CCW); (Back, Half); (Left, Half); (Front, Half); (Up, Half)]);
   ((DR, F1), [(Up, CW); (Back, Half); (Down, CCW); (Left, Half); (Down, CW); (Right, Half); (Down, CCW); (Left, Half); (Down, CW); (Back, Half); (Right, Half); (Right, CCW); (Front, CCW); (Left, CW); (Up, Half); (Left, CCW); (Front, CW); (Right, CCW); (Up, CCW)]);
   ((DF, F0), [(Up, Half); (Right, Half); (Back, Half); (Left, Half); (Down, CCW); (Left, Half); (Back, Half); (Right, Half); (Up, CW)]);
   ((DF, F1), [(Up, Half); (Left, Half); (Down, CW); (Back, Half); (Down, CCW); (Front, Half); (Down, CW); (Back, Half); (Down, CCW); (Left, Half); (Up, Half); (Front, CCW); (Right, CW); (Back, CCW); (Up, Half); (Back, CW); (Right, CCW); (Front, CW)]);
   ((DL, F0), [(Front, Half); (Down, CCW); (Left, Half); (Front, Half); (Right, Half); (Up, CCW); (Back, Half); (Right, Half)]);
   ((DL, F1), [(Right, Half); (Back, Half); (Left, Half); (Up, CCW); (Down, CCW); (Left, Half); (Up, CCW); (Front, Half); (Down, CCW); (Right, Half); (Front, Half); (Left, Half); (Up, CCW); (Right, CCW); (Left, CCW); (Front, CCW); (Up, Half); (Front, CCW); (Right, CCW); (Left, CW); (Up, CCW)]);
   ((DB, F0), [(Right, Half); (Front, Half); (Left, Half); (Down, CCW); (Left, Half); (Front, Half); (Right, Half); (Up, CCW)]);
   ((DB, F1), [(Front, Half); (Right, Half); (Up, CW); (Right, Half); (Front, Half); (Left, Half); (Back, Half); (Down, CW); (Right, Half); (Right, CCW); (Left, CCW); (Front, CCW); (Down, Half); (Front, CW); (Right, CCW); (Left, CCW)]);
   ((FR, F0), [(Down, CW); (Right, Half); (Up, CCW); (Down, CCW); (Left, Half); (Back, Half); (Down, CW); (Right, Half); (Back, Half); (Left, Half); (Up, CW); (Front, Half); (Right, CCW); (Front, Half); (Up, Half); (Front, Half); (Right, CCW); (Up, CW)]);
   ((FR, F1), [(Back, Half); (Left, Half); (Front, Half); (Down, Half); (Left, Half); (Up, CW); (Left, Half); (Up, CCW); (Front, Half); (Down, CW); (Left, Half); (Down, Half); (Back, CCW); (Left, Half); (Front, CCW); (Left, CCW); (Up, CW); (Left, CCW); (Up, CCW); (Back, CCW)]);
   ((FL, F0), [(Up, Half); (Right, Half); (Up, CW); (Front, Half); (Back, Half); (Up, CCW); (Front, Half); (Up, CW); (Back, Half); (Up, Half); (Right, Half); (Right, CCW); (Up, Half); (Front, Half); (Up, Half); (Right, CW); (Up, CCW)]);
   ((FL, F1), [(Up, CCW); (Back, Half); (Up, CCW); (Right, Half); (Front, Half); (Up, CCW); (Right, Half); (Down, CW); (Left, Half); (Front, Half); (Up, CW); (Back, Half); (Right, CCW); (Back, CW); (Right, Half); (Left, CW); (Down, Half); (Left, CW); (Front, CCW); (Right, CW); (Up, CCW)]);
   ((BL, F0), [(Up, CCW); (Front, Half); (Down, CW); (Left, Half); (Front, Half); (Up, Half); (Back, Half); (Right, Half); (Up, Half); (Front, Half); (Down, CCW); (Left, CCW); (Down, Half); (Front, Half); (Up, Half); (Right, CCW); (Up, CCW)]);
   ((BL, F1), [(Right, Half); (Front, Half); (Down, CW); (Back, Half); (Down, CCW); (Front, Half); (Right, Half); (Down, CCW); (Front, Half); (Left, Half); (Up, CCW); (Down, CCW); (Back, CCW); (Down, Half); (Front, CCW); (Right, CCW); (Up, CW); (Right, CCW); (Up, CCW); (Front, CCW); (Up, Half)]);
   ((BR, F0), [(Right, Half); (Back, Half); (Right, Half); (Down, CW); (Left, Half); (Down, CCW); (Right, Half); (Back, Half); (Right, Half); (Up, CW); (Front, Half); (Up, Half); (Right, CCW); (Front, Half); (Up, Half); (Front, Half); (Right, CW); (Up, CW)]);
   ((BR, F1), [(Left, Half); (Down, CCW); (Right, Half); (Up, CCW); (Right, Half); (Up, CCW); (Back, Half); (Down, CW); (Back, Half); (Up, Half); (Left, Half); (Up, Half); (Right, CCW); (Back, CCW); (Up, CW); (Back, CW); (Up, Half); (Right, CW); (Up, CW); (Back, CW); (Up, CCW)])].

(** Finishing the UB slot, with all eight corners and 3 edges already finished. *)
Definition ub_table : etable :=
  [((UB, F0), []);
   ((UB, F1), [(Down, CW); (Right, Half); (Up, CW); (Front, Half); (Up, CCW); (Back, Half); (Up, CW); (Front, Half); (Up, CCW); (Right, Half); (Down, CCW); (Right, Half); (Right, CCW); (Front, CCW); (Left, CW); (Up, Half); (Left, CCW); (Front, CW); (Right, CCW)]);
   ((DR, F0), [(Up, CW); (Back, Half); (Left, Half); (Front, Half); (Down, CCW); (Left, Half); (Back, Half); (Right, Half); (Up, Half)]);
   ((DR, F1), [(Front, Half); (Up, CCW); (Right, Half); (Up, CW); (Left, Half); (Up, CCW); (Right, Half); (Back, Half); (Left, Half); (Front, Half); (Down, CCW); (Back, Half); (Right, CCW); (Front, CCW); (Left, CW); (Up, Half); (Left, CCW); (Front, CW); (Right, CCW)]);
   ((DF, F0), [(Up, Half); (Left, Half); (Back, Half); (Right, Half); (Down, CW); (Back, Half); (Left, Half); (Front, Half); (Up, CCW)]);
   ((DF, F1), [(Up, Half); (Left, Half); (Up, CW); (Right, Half); (Back, Half); (Down, CW); (Right, Half); (Down, CCW); (Back, Half); (Right, Half); (Up, CCW); (Left, Half); (Up, CCW); (Right, Half); (Right, CCW); (Back, CCW); (Left, CW); (Down, Half); (Left, CCW); (Back, CW); (Right, CCW); (Up, CCW)]);
   ((DL, F0), [(Up, CCW); (Back, Half); (Left, Half); (Back, Half); (Up, Half); (Front, Half); (Right, Half); (Front, Half); (Up, CCW)]);
   ((DL, F1), [(Down, CW); (Front, Half); (Right, Half); (Front, Half); (Right, Half); (Down, CCW); (Right, Half); (Front, Half); (Right, CCW); (Left, CCW); (Front, CCW); (Up, Half); (Front, CCW); (Right, CCW); (Left, CW)]);
   ((DB, F0), [(Right, Half); (Front, Half); (Left, Half); (Down, CCW); (Back, Half); (Left, Half); (Front, Half); (Up, CCW)]);
   ((DB, F1), [(Left, Half); (Up, CCW); (Right, Half); (Front, Half); (Down, CCW); (Right, Half); (Down, CW); (Front, Half); (Right, Half); (Up, CW); (Left, Half); (Up, CW); (Right, CCW); (Front, CW); (Left, CCW); (Down, Half); (Left, CW); (Front, CCW); (Right, CW); (Up, CCW)]);
   ((FR, F0), [(Up, CW); (Front, Half); (Left, Half); (Back, Half); (Up, CW); (Right, Half); (Up, CCW); (Down, CW); (Left, Half); (Up, Half); (Front, Half); (Up, Half); (Right, CCW); (Up, Half); (Front, Half); (Up, Half); (Right, CCW); (Front, Half)]);
   ((FR, F1), [(Right, Half); (Down, CCW); (Right, Half); (Up, CCW); (Front, Half); (Up, CCW); (Front, Half); (Right, Half); (Up, CW); (Back, Half); (Left, Half); (Up, CCW); (Right, CCW); (Front, CCW); (Left, CCW); (Up, Half); (Front, CCW); (Right, CCW); (Front, CW); (Left, CCW)]);
   ((FL, F0), [(Up, Half); (Front, Half); (Down, CCW); (Right, Half); (Back, Half); (Up, CCW); (Left, Half); (Back, Half); (Right, Half); (Up, CCW); (Right, Half); (Up, CCW); (Right, CCW); (Up, Half); (Front, Half); (Up, Half); (Right, CCW)]);
   ((FL, F1), [(Right, Half); (Front, Half); (Down, CCW); (Back, Half); (Left, Half); (Up, CCW); (Right, Half); (Down, CW); (Back, Half); (Right, Half); (Down, CW); (Front, Half); (Down, Half); (Right, CCW); (Back, CW); (Right, Half); (Left, CW); (Down, Half); (Left, CW); (Front, CCW); (Right, CCW)]);
   ((BL, F0), [(Front, Half); (Up, CCW); (Front, Half); (Right, Half); (Front, Half); (Down, Half); (Back, Half); (Right, Half); (Front, Half); (Down, CW); (Front, Half); (Right, Half); (Left, CCW); (Down, Half); (Front, Half); (Up, Half); (Right, CW)]);
   ((BL, F1), [(Down, CW); (Back, Half); (Down, Half); (Right, Half); (Front, Half); (Left, Half); (Up, Half); (Left, Half); (Front, Half); (Right, CCW); (Back, CW); (Down, CCW); (Back, CCW); (Down, Half); (Right, CCW); (Down, CCW); (Back, CW)]);
   ((BR, F0), [(Front, Half); (Up, CW); (Front, Half); (Down, Half); (Left, Half); (Back, Half); (Down, Half); (Front, Half); (Right, Half); (Up, CCW); (Left, CCW); (Back, Half); (Up, Half); (Front, Half); (Right, CCW); (Down, Half)]);
   ((BR, F1), [(Front, Half); (Up, CCW); (Front, Half); (Down, CW); (Right, Half); (Down, CCW); (Right, CCW); (Back, CW); (Up, CW); (Back, CCW); (Up, CW); (Right, CW); (Up, Half); (Right, CCW)])].

(** Finishing the DR slot, with all eight corners and 4 edges already finished. *)
Definition dr_table : etable :=
  [((DR, F0), []);
   ((DR, F1), [(Front, Half); (Up, CW); (Back, Half); (Up, CCW); (Front, Half); (Down, CW); (Right, Half); (Down, CCW); (Right, Half); (Up, CW); (Front, Half); (Back, Half); (Up, CCW); (Right, CCW); (Back, CCW); (Left, CW); (Down, Half); (Left, CCW); (Back, CW); (Right, CW)]);
   ((DF, F0), [(Right, Half); (Up, CW); (Right, Half); (Back, Half); (Left, Half); (Down, CCW); (Back, Half); (Right, Half); (Front, Half); (Up, Half); (Right, Half)]);
   ((DF, F1), [(Down, CCW); (Front, Half); (Up, CCW); (Right, Half); (Back, Half); (Up, CCW); (Left, Half); (Down, CW); (Left, Half); (Back, Half); (Up, CW); (Right, Half); (Up, CW); (Right, CCW); (Back, CCW); (Left, CW); (Down, Half); (Left, CCW); (Back, CW); (Right, CW)]);
   ((DL, F0), [(Right, Half); (Up, Half); (Front, Half); (Right, Half); (Back, Half); (Down, CW); (Left, Half); (Back, Half); (Right, Half); (Up, CCW); (Right, Half)]);
   ((DL, F1), [(Front, Half); (Back, Half); (Up, CCW); (Front, Half); (Left, Half); (Front, Half); (Up, CW); (Back, Half); (Right, Half); (Front, Half); (Front, CCW); (Down, CCW); (Right, CW); (Down, CW); (Right, Half); (Front, CW); (Right, CW); (Down, CCW); (Right, CCW)]);
   ((DB, F0), [(Right, Half); (Up, CCW); (Left, Half); (Back, Half); (Left, Half); (Up, Half); (Right, Half); (Front, Half); (Right, Half); (Up, CCW); (Right, Half)]);
   ((DB, F1), [(Right, Half); (Front, Half); (Down, CW); (Back, Half); (Right, Half); (Up, CW); (Left, Half); (Down, CCW); (Front, Half); (Right, Half); (Up, CCW); (Front, Half); (Right, CCW); (Front, CW); (Left, CCW); (Down, Half); (Left, CW); (Front, CCW); (Right, CCW)]);
   ((FR, F0), [(Right, Half); (Up, CCW); (Right, Half); (Left, Half); (Down, CW); (Right, CCW); (Down, CCW); (Right, Half); (Left, Half); (Up, CW); (Right, CCW)]);
   ((FR, F1), [(Right, Half); (Up, Half); (Left, Half); (Down, CCW); (Back, Half); (Back, CCW); (Down, CW); (Left, CW); (Up, CCW); (Left, CW); (Up, CCW); (Right, CCW); (Front, CCW); (Right, CCW)]);
   ((FL, F0), [(Right, Half); (Down, CCW); (Front, Half); (Back, Half); (Down, CW); (Front, Half); (Up, Half); (Down, CW); (Back, Half); (Up, Half); (Right, CCW); (Up, Half); (Front, Half); (Up, Half); (Right, CCW); (Down, CCW)]);
   ((FL, F1), [(Down, CCW); (Front, Half); (Front, CCW); (Down, CW); (Right, CW); (Up, CW); (Left, CW); (Front, CCW); (Left, CCW); (Up, CCW); (Right, CCW)]);
   ((BL, F0), [(Down, Half); (Back, Half); (Down, CW); (Back, Half); (Right, Half); (Front, Half); (Up, CW); (Left, Half); (Up, CW); (Left, Half); (Down, Half); (Back, Half); (Left, CCW); (Down, Half); (Front, Half); (Up, Half); (Right, CW); (Down, CCW)]);
   ((BL, F1), [(Front, Half); (Down, CCW); (Front, Half); (Up, CW); (Front, Half); (Right, Half); (Down, CW); (Back, Half); (Up, CW); (Right, Half); (Back, Half); (Right, Half); (Up, CW); (Back, CCW); (Up, Half); (Front, CW); (Right, CW); (Down, CCW); (Right, CW); (Down, CW); (Front, CW)]);
   ((BR, F0), [(Right, Half); (Up, CCW); (Right, Half); (Left, Half); (Down, CW); (Right, Half); (Right, CCW); (Down, CCW); (Right, Half); (Left, Half); (Up, CW); (Right, CW)]);
   ((BR, F1), [(Right, Half); (Up, CW); (Left, Half); (Left, CCW); (Down, CW); (Front, CW); (Down, CCW); (Left, CCW); (Up, CCW); (Right, CCW); (Front, CCW); (Right, CCW)])].

(** Finishing the DF slot, with all eight corners and 5 edges already finished. *)
Definition df_table : etable :=
  [((DF, F0), []);
   ((DF, F1), [(Back, Half); (Down, CCW); (Right, Half); (Up, CW); (Left, Half); (Up, CCW); (Front, Half); (Down, CW); (Right, Half); (Back, Half); (Up, CW); (Right, Half); (Left, Half); (Up, CCW); (Left, CCW); (Front, CCW); (Left, CW); (Front, Half); (Right, CCW); (Front, CW); (Right, CCW)]);
   ((DL, F0), [(Front, Half); (Up, CW); (Back, Half); (Right, Half); (Front, Half); (Down, CCW); (Left, Half); (Front, Half); (Right, Half); (Up, Half); (Front, Half)]);
   ((DL, F1), [(Left, Half); (Back, Half); (Down, CW); (Back, Half); (Down, CCW); (Back, Half); (Up, CW); (Back, Half); (Up, CCW); (Right, Half); (Left, Half); (Front, Half); (Left, CCW); (Front, CCW); (Left, CW); (Front, Half); (Right, CCW); (Front, CW); (Right, CCW)]);
   ((DB, F0), [(Front, Half); (Up, Half); (Left, Half); (Front, Half); (Right, Half); (Down, CW); (Back, Half); (Right, Half); (Front, Half); (Up, CCW); (Front, Half)]);
   ((DB, F1), [(Left, Half); (Back, Half); (Down, CW); (Left, Half); (Up, CCW); (Down, CW); (Left, Half); (Down, CW); (Right, Half); (Up, CCW); (Back, Half); (Left, CCW); (Down, CCW); (Front, CW); (Up, Half); (Right, CW); (Back, Half); (Up, CW); (Front, CW); (Right, CCW)]);
   ((FR, F0), [(Front, Half); (Up, CCW); (Back, Half); (Left, Half); (Front, Half); (Down, Half); (Back, Half); (Right, Half); (Front, Half); (Up, CW); (Back, Half); (Left, Half); (Left, CCW); (Back, Half); (Up, Half); (Front, Half); (Right, CW)]);
   ((FR, F1), [(Down, Half); (Right, Half); (Front, Half); (Up, CCW); (Left, Half); (Down, CW); (Right, Half); (Back, Half); (Down, CW); (Left, Half); (Up, Half); (Right, Half); (Front, CCW); (Right, CW); (Front, CW); (Right, CCW); (Up, CCW); (Down, Half); (Right, CW); (Down, Half); (Right, CCW)]);
   ((FL, F0), [(Up, Half); (Right, Half); (Down, CW); (Right, Half); (Down, CCW); (Right, Half); (Back, Half); (Left, Half); (Up, CCW); (Front, Half); (Up, CW); (Left, CCW); (Back, Half); (Up, Half); (Front, Half); (Right, CW); (Front, Half)]);
   ((FL, F1), [(Right, Half); (Left, Half); (Back, Half); (Up, CW); (Left, Half); (Down, Half); (Front, Half); (Left, Half); (Back, Half); (Up, Half); (Left, CCW); (Front, CW); (Down, CCW); (Front, CCW); (Down, Half); (Left, CCW); (Down, CCW); (Front, CCW)]);
   ((BL, F0), [(Front, Half); (Right, Half); (Back, Half); (Up, CW); (Back, Half); (Right, Half); (Front, Half); (Down, CCW); (Right, Half); (Front, Half); (Down, Half); (Back, Half); (Left, CCW); (Down, Half); (Front, Half); (Up, Half); (Right, CW); (Down, Half)]);
   ((BL, F1), [(Right, Half); (Front, Half); (Left, Half); (Up, Half); (Left, Half); (Down, CCW); (Front, Half); (Down, CW); (Right, Half); (Up, CCW); (Right, Half); (Up, Half); (Left, CCW); (Back, CCW); (Up, CCW); (Back, CW); (Up, CCW); (Right, CCW); (Front, Half); (Right, CCW)]);
   ((BR, F0), [(Front, Half); (Up, CCW); (Back, Half); (Left, Half); (Front, Half); (Down, Half); (Back, Half); (Right, Half); (Front, Half); (Up, CW); (Back, Half); (Left, CCW); (Back, Half); (Up, Half); (Front, Half); (Right, CCW)]);
   ((BR, F1), [(Front, Half); (Right, Half); (Down, CW); (Left, Half); (Back, Half); (Up, CW); (Front, Half); (Down, CCW); (Left, Half); (Front, Half); (Down, CCW); (Right, Half); (Down, Half); (Front, Half); (Front, CCW); (Left, CCW); (Back, CW); (Up, Half); (Front, Half); (Back, CW); (Right, CW); (Front, CW)])].

(** Finishing the DL slot, with all eight corners and 6 edges already finished. *)
Definition dl_table : etable :=
  [((DL, F0), []);
   ((DL, F1), [(Back, Half); (Down, CCW); (Right, Half); (Up, CW); (Right, Half); (Up, CCW); (Left, Half); (Front, Half); (Up, CCW); (Left, Half); (Back, Half); (Left, Half); (Front, Half); (Right, Half); (Left, CCW); (Back, CW); (Left, CCW); (Back, Half); (Right, CW); (Back, CCW); (Right, CCW)]);
   ((DB, F0), [(Right, Half); (Down, Half); (Front, Half); (Up, CW); (Left, Half); (Back, Half); (Up, Half); (Front, Half); (Right, Half); (Down, Half); (Front, Half); (Up, CCW); (Left, CCW); (Back, Half); (Up, Half); (Front, Half); (Right, CW)]);
   ((DB, F1), [(Left, Half); (Back, Half); (Right, Half); (Up, Half); (Back, Half); (Down, CW); (Back, Half); (Down, CCW); (Right, Half); (Up, CW); (Back, Half); (Up, Half); (Left, CCW); (Back, Half); (Right, CCW); (Back, CCW); (Down, CW); (Back, CCW); (Down, CCW); (Left, CCW)]);
   ((FR, F0), [(Right, Half); (Down, Half); (Right, Half); (Up, CCW); (Right, Half); (Left, Half); (Down, CW); (Right, Half); (Up, Half); (Right, CCW); (Down, CW); (Right, Half); (Left, Half); (Up, CCW); (Right, CCW)]);
   ((FR, F1), [(Back, Half); (Up, Half); (Left, Half); (Front, Half); (Up, CW); (Front, Half); (Down, CW); (Right, Half); (Down, CW); (Front, Half); (Left, Half); (Up, Half); (Right, Half); (Back, CCW); (Left, Half); (Front, CW); (Left, CW); (Down, CCW); (Left, CW); (Down, CW); (Back, CW)]);
   ((FL, F0), [(Up, Half); (Left, Half); (Up, CCW); (Right, Half); (Left, Half); (Up, CW); (Back, Half); (Down, CCW); (Back, Half); (Up, Half); (Right, CCW); (Up, Half); (Front, Half); (Up, Half); (Right, CCW); (Down, CW)]);
   ((FL, F1), [(Up, CW); (Left, Half); (Down, CW); (Front, Half); (Down, CW); (Front, Half); (Up, CCW); (Front, Half); (Right, Half); (Front, Half); (Up, CW); (Left, CCW); (Up, CW); (Back, Half); (Up, Half); (Right, CW); (Front, CW); (Down, CCW); (Front, CW); (Right, CCW)]);
   ((BL, F0), [(Back, Half); (Down, CW); (Back, Half); (Right, Half); (Front, Half); (Up, CW); (Left, Half); (Up, CW); (Left, Half); (Down, Half); (Back, Half); (Left, CCW); (Down, Half); (Front, Half); (Up, Half); (Right, CW); (Down, CW)]);
   ((BL, F1), [(Down, Half); (Front, Half); (Up, CW); (Back, Half); (Left, Half); (Back, Half); (Up, Half); (Front, Half); (Right, Half); (Front, Half); (Up, CW); (Front, CCW); (Down, CW); (Left, CW); (Front, CW); (Left, Half); (Front, CCW); (Down, CCW); (Left, CCW); (Front, CCW)]);
   ((BR, F0), [(Down, Half); (Right, Half); (Up, CCW); (Right, Half); (Left, Half); (Down, CW); (Right, Half); (Up, Half); (Right, CCW); (Down, CW); (Right, Half); (Left, Half); (Up, CCW); (Right, CW)]);
   ((BR, F1), [(Right, Half); (Up, CW); (Right, Half); (Front, Half); (Left, Half); (Down, Half); (Left, Half); (Front, Half); (Right, Half); (Up, CW); (Right, CCW); (Front, Half); (Back, CCW); (Left, CCW); (Front, CCW); (Back, CW); (Down, CW); (Front, CCW); (Right, CCW)])].

(** Finishing the DB slot, with all eight corners and 7 edges already finished. *)
Definition db_table : etable :=
  [((DB, F0), []);
   ((DB, F1), [(Up, Half); (Front, Half); (Left, Half); (Down, Half); (Left, Half); (Front, Half); (Up, CCW); (Right, Half); (Up, CCW); (Back, CCW); (Right, CCW); (Up, CCW); (Back, Half); (Up, CW); (Back, CW); (Right, CCW)]);
   ((FR, F0), [(Down, CW); (Front, Half); (Down, Half); (Front, Half); (Down, CW); (Right, Half); (Up, CCW); (Back, Half); (Down, CCW); (Right, Half); (Up, CCW); (Front, Half); (Up, CCW); (Right, CCW); (Down, CW); (Right, Half); (Left, Half); (Up, CCW); (Right, CCW)]);
   ((FR, F1), [(Down, CCW); (Front, Half); (Up, CW); (Down, CCW); (Left, Half); (Up, CCW); (Right, Half); (Up, Half); (Back, CCW); (Left, Half); (Up, Half); (Right, Half); (Front, CCW)]);
   ((FL, F0), [(Back, Half); (Down, CW); (Back, Half); (Down, CW); (Front, Half); (Down, CW); (Right, Half); (Up, CW); (Front, Half); (Up, CCW); (Front, Half); (Right, CCW); (Up, Half); (Front, Half); (Up, Half); (Right, CCW); (Down, CW)]);
   ((FL, F1), [(Up, CW); (Down, CCW); (Left, Half); (Up, CCW); (Down, CCW); (Right, Half); (Up, Half); (Back, CCW); (Left, Half); (Up, Half); (Right, Half); (Front, CW)]);
   ((BL, F0), [(Down, CCW); (Right, Half); (Up, Half); (Front, Half); (Down, Half); (Left, CCW); (Down, Half); (Front, Half); (Up, Half); (Right, CW); (Down, CW)]);
   ((BL, F1), [(Down, Half); (Back, Half); (Down, Half); (Left, Half); (Up, Half); (Front, Half); (Back, CCW); (Down, Half); (Right, Half); (Up, Half); (Front, CCW); (Down, Half)]);
   ((BR, F0), [(Up, CCW); (Right, Half); (Up, Half); (Right, Half); (Left, Half); (Front, Half); (Right, Half); (Down, Half); (Right, Half); (Front, Half); (Down, CCW); (Right, CCW); (Down, CW); (Right, Half); (Left, Half); (Up, CCW); (Right, CW)]);
   ((BR, F1), [(Right, Half); (Up, Half); (Left, Half); (Down, Half); (Back, CCW); (Left, Half); (Up, Half); (Right, Half); (Front, CCW); (Right, Half)])].

(** Finishing the FR slot, with all eight corners and 8 edges already finished. *)
Definition fr_table : etable :=
  [((FR, F0), []);
   ((FR, F1), [(Front, Half); (Up, CCW); (Right, Half); (Back, Half); (Down, CCW); (Left, Half); (Down, CW); (Back, Half); (Right, Half); (Up, CW); (Front, Half); (Right, Half); (Right, CCW); (Up, CCW); (Front, CW); (Up, Half); (Front, CCW); (Up, CW); (Right, CCW)]);
   ((FL, F0), [(Down, CCW); (Left, Half); (Up, CCW); (Down, CW); (Front, Half); (Up, CW)]);
   ((FL, F1), [(Front, Half); (Down, CCW); (Front, Half); (Right, Half); (Up, CCW); (Left, Half); (Up, CW); (Right, Half); (Front, Half); (Down, CW); (Front, Half); (Right, Half); (Right, CCW); (Up, CCW); (Front, CW); (Up, Half); (Front, CCW); (Up, CW); (Right, CCW)]);
   ((BL, F0), [(Down, CW); (Front, Half); (Up, CW); (Down, CCW); (Left, Half); (Up, CCW)]);
   ((BL, F1), [(Front, Half); (Up, CCW); (Front, Half); (Up, CW); (Left, Half); (Up, CCW); (Front, Half); (Up, CW); (Front, Half); (Right, Half); (Right, CCW); (Up, CW); (Front, CCW); (Left, Half); (Front, CW); (Up, CCW); (Right, CCW)]);
   ((BR, F0), [(Down, CW); (Right, Half); (Up, CW); (Down, CCW); (Front, Half); (Up, CCW)]);
   ((BR, F1), [(Right, Half); (Down, CCW); (Front, Half); (Down, CW); (Front, Half); (Right, Half); (Up, CW); (Front, Half); (Up, CCW); (Right, Half); (Front, CCW); (Right, CCW); (Down, CW); (Right, Half); (Down, CCW); (Right, CW); (Front, CCW)])].

(** Finishing the FL slot, with all eight corners and 9 edges already finished. *)
Definition fl_table : etable :=
  [((FL, F0), []);
   ((FL, F1), [(Front, Half); (Right, Half); (Down, CW); (Back, Half); (Down, CCW); (Back, Half); (Down, CW); (Back, Half); (Down, CCW); (Right, Half); (Front, CCW); (Up, CCW); (Right, CW); (Back, Half); (Right, CCW); (Up, CW); (Front, CCW)]);
   ((BL, F0), [(Down, CCW); (Back, Half); (Up, CCW); (Down, CW); (Left, Half); (Up, CW)]);
   ((BL, F1), [(Front, Half); (Right, Half); (Up, CW); (Right, Half); (Up, CCW); (Back, Half); (Up, CW); (Right, Half); (Up, CCW); (Right, Half); (Front, CCW); (Up, CCW); (Right, CW); (Back, Half); (Right, CCW); (Up, CW); (Front, CCW)]);
   ((BR, F0), [(Down, CW); (Left, Half); (Up, CW); (Down, CCW); (Back, Half); (Up, CCW)]);
   ((BR, F1), [(Front, Half); (Down, CCW); (Back, Half); (Up, CW); (Left, Half); (Up, Half); (Down, CW); (Left, Half); (Up, CW); (Front, Half); (Right, Half); (Right, CCW); (Front, CW); (Down, CCW); (Front, Half); (Down, CW); (Front, CCW); (Right, CCW)])].

(** Finishing the BL slot, with all eight corners and 10 edges already finished. *)
Definition bl_table : etable :=
  [((BL, F0), []);
   ((BL, F1), [(Right, Half); (Front, Half); (Up, CW); (Left, Half); (Up, CCW); (Left, Half); (Up, CW); (Left, Half); (Up, CCW); (Front, Half); (Right, CCW); (Down, CCW); (Front, CW); (Left, Half); (Front, CCW); (Down, CW); (Right, CCW)])].

(** The stages in the order they run. *)
(** The corner stages in the order they run. *)
Definition corner_stages : list stage := [Cstage URF urf_table 22; Cstage UFL ufl_table 21; Cstage ULB ulb_table 20; Cstage UBR ubr_table 20; Cstage DFR dfr_table 21; Cstage DLF dlf_table 22; Cstage DBL dbl_table 21].
(** And the edge stages. *)
Definition edge_stages : list stage := [Estage UR ur_table 23; Estage UF uf_table 22; Estage UL ul_table 21; Estage UB ub_table 22; Estage DR dr_table 21; Estage DF df_table 22; Estage DL dl_table 21; Estage DB db_table 19; Estage FR fr_table 19; Estage FL fl_table 18].

(** The tables answer for every reading still possible, leave the finished
    slots alone, and bring their own slot home. *)
Lemma corner_stages_ok : chain_ok plain [] [] corner_stages = true.
Proof. vm_compute; reflexivity. Qed.

(** The corner slots they finish, newest first. *)
Lemma corner_stages_slots :
  stagesc corner_stages = [DBL; DLF; DFR; UBR; ULB; UFL; URF].
Proof. vm_compute; reflexivity. Qed.

(** The edge stages check out too, given the corners are done. *)
Lemma edge_stages_ok : chain_ok plain all_corner_slots [] edge_stages = true.
Proof. vm_compute; reflexivity. Qed.

(** The edge slots they finish, newest first. *)
Lemma edge_stages_slots : stagese edge_stages = [FL; FR; DB; DL; DF; DR; UB; UL; UF; UR].
Proof. vm_compute; reflexivity. Qed.

(** They finish no corner slot. *)
Lemma edge_stages_corners : stagesc edge_stages = [].
Proof. vm_compute; reflexivity. Qed.

(** The eleventh edge holds its own piece, so its table answers only for the
    two flips it can show. *)
Lemma bl_table_ok : etable_ok bl_table all_corner_slots [FL; FR; DB; DL; DF; DR; UB; UL; UF; UR] BL = true.
Proof. vm_compute; reflexivity. Qed.

(** It answers when that edge is unflipped, *)
Lemma bl_table_covers_0 : ecovers bl_table (BL, F0) = true.
Proof. vm_compute; reflexivity. Qed.

(** and when it is flipped. *)
Lemma bl_table_covers_1 : ecovers bl_table (BL, F1) = true.
Proof. vm_compute; reflexivity. Qed.

(** And its answers are short. *)
Lemma bl_table_bounded : etable_bounded bl_table 17 = true.
Proof. vm_compute; reflexivity. Qed.

(** The longest answer the tables allow, added up over the stages. *)
Definition full_bound : nat := 372.

(** Which is what the stages add up to. *)
Lemma full_bound_ok :
  17 + (chain_bound edge_stages + chain_bound corner_stages)
  = full_bound.
Proof. vm_compute; reflexivity. Qed.
