From Stdlib Require Import Arith Bool Lia List.
Import ListNotations.

(** * Sticker representation *)

(** The six outward faces also name the colors of their solved stickers. *)
Inductive face := Up | Right | Front | Down | Left | Back.

(** A sticker color is named after the face it occupies in the solved cube. *)
Definition color := face.

(** Three entries share one shape, reused for rows, grids, and face groups. *)
Inductive triple (A : Type) := Triple (a b c : A).
Arguments Triple {A} _ _ _.

(** Three rows of three colors form a face viewed from outside the cube. *)
Definition grid := triple (triple color).

(** The 54 stickers are grouped as U/R/F and D/L/B, with row-major grids. *)
Definition state := (triple grid * triple grid)%type.

(** Filling a grid with one color describes a solved face. *)
Definition solid (c : color) : grid :=
  Triple (Triple c c c) (Triple c c c) (Triple c c c).

(** The solved cube places every sticker on the face matching its color. *)
Definition init_state : state :=
  (Triple (solid Up) (solid Right) (solid Front),
   Triple (solid Down) (solid Left) (solid Back)).

(** * Decidable equality *)

(** Face equality is decidable by comparing the six constructors. *)
Definition face_eq_dec (x y : face) : {x = y} + {x <> y}.
Proof.
  decide equality.
Defined.

(** Deciding equality entry by entry lifts an equality test to triples. *)
Definition triple_eq_dec {A} (eq_dec : forall x y : A, {x = y} + {x <> y})
  (x y : triple A) : {x = y} + {x <> y}.
Proof.
  decide equality.
Defined.

(** Comparing all 54 stickers decides whether two cube states coincide. *)
Definition state_eq_dec (x y : state) : {x = y} + {x <> y}.
Proof.
  decide equality; repeat apply triple_eq_dec; apply face_eq_dec.
Defined.

(** A boolean view of state equality is convenient for computations. *)
Definition state_eq (x y : state) : bool :=
  if state_eq_dec x y then true else false.

(** The boolean comparison recognizes exactly equal states. *)
Lemma state_eq_correct x y : state_eq x y = true <-> x = y.
Proof.
  unfold state_eq; destruct (state_eq_dec x y); intuition discriminate.
Qed.

(** * Finite enumeration *)

(** A fixed face order makes enumeration and search results deterministic. *)
Definition faces : list face := [Up; Right; Front; Down; Left; Back].

(** The face enumeration omits none of the six directions. *)
Lemma faces_complete f : In f faces.
Proof.
  destruct f; simpl; tauto.
Qed.

(** Choosing each entry independently enumerates all triples over a list. *)
Definition triples {A} (xs : list A) : list (triple A) :=
  flat_map (fun a => flat_map (fun b => map (Triple a b) xs) xs) xs.

(** An exhaustive entry list gives an exhaustive triple list. *)
Lemma triples_complete {A} (xs : list A) :
  (forall x, In x xs) -> forall t, In t (triples xs).
Proof.
  intros H [a b c]; unfold triples.
  apply in_flat_map; exists a; split; auto.
  apply in_flat_map; exists b; split; auto.
  apply in_map; auto.
Qed.

(** Independent color choices enumerate every 54-sticker assignment, legal or
    not. *)
Definition all_states : list state :=
  list_prod (triples (triples (triples faces))) (triples (triples (triples faces))).

(** Every representable cube occurs in the finite search space. *)
Lemma all_states_complete s : In s all_states.
Proof.
  destruct s; apply in_prod; repeat apply triples_complete; apply faces_complete.
Qed.

(** Three independent choices cube the number of available entries. *)
Lemma triples_length {A} (xs : list A) : length (triples xs) = length xs ^ 3.
Proof.
  unfold triples.
  rewrite flat_map_constant_length with (c := length xs * length xs).
  - simpl Nat.pow; lia.
  - intros a _; apply flat_map_constant_length; intros b _; apply length_map.
Qed.

(** A cube has 54 independent sticker slots over any choice of colors. *)
Lemma states_length {A} (xs : list A) :
  length (list_prod (triples (triples (triples xs)))
                   (triples (triples (triples xs)))) = length xs ^ 54.
Proof.
  rewrite length_prod; repeat rewrite triples_length.
  repeat rewrite <- Nat.pow_mul_r.
  rewrite <- Nat.pow_add_r; reflexivity.
Qed.

(** Six colors across 54 slots give a conservative finite-state bound. *)
Lemma all_states_length : length all_states = 6 ^ 54.
Proof.
  exact (states_length faces).
Qed.

(** * Face turns *)

(* BEGIN GENERATED MOVES *)
(* Generated by scripts/generate_moves.py; checked against Geometry.v. *)
(** A clockwise outer-layer turn permutes stickers while keeping centers fixed. *)
Definition quarter (f : face) (s : state) : state :=
  match s with
  | (Triple
       (Triple (Triple u0 u1 u2) (Triple u3 u4 u5) (Triple u6 u7 u8))
       (Triple (Triple r0 r1 r2) (Triple r3 r4 r5) (Triple r6 r7 r8))
       (Triple (Triple f0 f1 f2) (Triple f3 f4 f5) (Triple f6 f7 f8)),
     Triple
       (Triple (Triple d0 d1 d2) (Triple d3 d4 d5) (Triple d6 d7 d8))
       (Triple (Triple l0 l1 l2) (Triple l3 l4 l5) (Triple l6 l7 l8))
       (Triple (Triple b0 b1 b2) (Triple b3 b4 b5) (Triple b6 b7 b8))) =>
    match f with
    | Up =>
      (Triple
         (Triple (Triple u6 u3 u0) (Triple u7 u4 u1) (Triple u8 u5 u2))
         (Triple (Triple b0 b1 b2) (Triple r3 r4 r5) (Triple r6 r7 r8))
         (Triple (Triple r0 r1 r2) (Triple f3 f4 f5) (Triple f6 f7 f8)),
       Triple
         (Triple (Triple d0 d1 d2) (Triple d3 d4 d5) (Triple d6 d7 d8))
         (Triple (Triple f0 f1 f2) (Triple l3 l4 l5) (Triple l6 l7 l8))
         (Triple (Triple l0 l1 l2) (Triple b3 b4 b5) (Triple b6 b7 b8)))
    | Right =>
      (Triple
         (Triple (Triple u0 u1 f2) (Triple u3 u4 f5) (Triple u6 u7 f8))
         (Triple (Triple r6 r3 r0) (Triple r7 r4 r1) (Triple r8 r5 r2))
         (Triple (Triple f0 f1 d2) (Triple f3 f4 d5) (Triple f6 f7 d8)),
       Triple
         (Triple (Triple d0 d1 b6) (Triple d3 d4 b3) (Triple d6 d7 b0))
         (Triple (Triple l0 l1 l2) (Triple l3 l4 l5) (Triple l6 l7 l8))
         (Triple (Triple u8 b1 b2) (Triple u5 b4 b5) (Triple u2 b7 b8)))
    | Front =>
      (Triple
         (Triple (Triple u0 u1 u2) (Triple u3 u4 u5) (Triple l8 l5 l2))
         (Triple (Triple u6 r1 r2) (Triple u7 r4 r5) (Triple u8 r7 r8))
         (Triple (Triple f6 f3 f0) (Triple f7 f4 f1) (Triple f8 f5 f2)),
       Triple
         (Triple (Triple r6 r3 r0) (Triple d3 d4 d5) (Triple d6 d7 d8))
         (Triple (Triple l0 l1 d0) (Triple l3 l4 d1) (Triple l6 l7 d2))
         (Triple (Triple b0 b1 b2) (Triple b3 b4 b5) (Triple b6 b7 b8)))
    | Down =>
      (Triple
         (Triple (Triple u0 u1 u2) (Triple u3 u4 u5) (Triple u6 u7 u8))
         (Triple (Triple r0 r1 r2) (Triple r3 r4 r5) (Triple f6 f7 f8))
         (Triple (Triple f0 f1 f2) (Triple f3 f4 f5) (Triple l6 l7 l8)),
       Triple
         (Triple (Triple d6 d3 d0) (Triple d7 d4 d1) (Triple d8 d5 d2))
         (Triple (Triple l0 l1 l2) (Triple l3 l4 l5) (Triple b6 b7 b8))
         (Triple (Triple b0 b1 b2) (Triple b3 b4 b5) (Triple r6 r7 r8)))
    | Left =>
      (Triple
         (Triple (Triple b8 u1 u2) (Triple b5 u4 u5) (Triple b2 u7 u8))
         (Triple (Triple r0 r1 r2) (Triple r3 r4 r5) (Triple r6 r7 r8))
         (Triple (Triple u0 f1 f2) (Triple u3 f4 f5) (Triple u6 f7 f8)),
       Triple
         (Triple (Triple f0 d1 d2) (Triple f3 d4 d5) (Triple f6 d7 d8))
         (Triple (Triple l6 l3 l0) (Triple l7 l4 l1) (Triple l8 l5 l2))
         (Triple (Triple b0 b1 d6) (Triple b3 b4 d3) (Triple b6 b7 d0)))
    | Back =>
      (Triple
         (Triple (Triple r2 r5 r8) (Triple u3 u4 u5) (Triple u6 u7 u8))
         (Triple (Triple r0 r1 d8) (Triple r3 r4 d7) (Triple r6 r7 d6))
         (Triple (Triple f0 f1 f2) (Triple f3 f4 f5) (Triple f6 f7 f8)),
       Triple
         (Triple (Triple d0 d1 d2) (Triple d3 d4 d5) (Triple l0 l3 l6))
         (Triple (Triple u2 l1 l2) (Triple u1 l4 l5) (Triple u0 l7 l8))
         (Triple (Triple b6 b3 b0) (Triple b7 b4 b1) (Triple b8 b5 b2)))
    end
  end.

(** A half turn, tabulated directly rather than as two clockwise turns. *)
Definition half (f : face) (s : state) : state :=
  match s with
  | (Triple
       (Triple (Triple u0 u1 u2) (Triple u3 u4 u5) (Triple u6 u7 u8))
       (Triple (Triple r0 r1 r2) (Triple r3 r4 r5) (Triple r6 r7 r8))
       (Triple (Triple f0 f1 f2) (Triple f3 f4 f5) (Triple f6 f7 f8)),
     Triple
       (Triple (Triple d0 d1 d2) (Triple d3 d4 d5) (Triple d6 d7 d8))
       (Triple (Triple l0 l1 l2) (Triple l3 l4 l5) (Triple l6 l7 l8))
       (Triple (Triple b0 b1 b2) (Triple b3 b4 b5) (Triple b6 b7 b8))) =>
    match f with
    | Up =>
      (Triple
         (Triple (Triple u8 u7 u6) (Triple u5 u4 u3) (Triple u2 u1 u0))
         (Triple (Triple l0 l1 l2) (Triple r3 r4 r5) (Triple r6 r7 r8))
         (Triple (Triple b0 b1 b2) (Triple f3 f4 f5) (Triple f6 f7 f8)),
       Triple
         (Triple (Triple d0 d1 d2) (Triple d3 d4 d5) (Triple d6 d7 d8))
         (Triple (Triple r0 r1 r2) (Triple l3 l4 l5) (Triple l6 l7 l8))
         (Triple (Triple f0 f1 f2) (Triple b3 b4 b5) (Triple b6 b7 b8)))
    | Right =>
      (Triple
         (Triple (Triple u0 u1 d2) (Triple u3 u4 d5) (Triple u6 u7 d8))
         (Triple (Triple r8 r7 r6) (Triple r5 r4 r3) (Triple r2 r1 r0))
         (Triple (Triple f0 f1 b6) (Triple f3 f4 b3) (Triple f6 f7 b0)),
       Triple
         (Triple (Triple d0 d1 u2) (Triple d3 d4 u5) (Triple d6 d7 u8))
         (Triple (Triple l0 l1 l2) (Triple l3 l4 l5) (Triple l6 l7 l8))
         (Triple (Triple f8 b1 b2) (Triple f5 b4 b5) (Triple f2 b7 b8)))
    | Front =>
      (Triple
         (Triple (Triple u0 u1 u2) (Triple u3 u4 u5) (Triple d2 d1 d0))
         (Triple (Triple l8 r1 r2) (Triple l5 r4 r5) (Triple l2 r7 r8))
         (Triple (Triple f8 f7 f6) (Triple f5 f4 f3) (Triple f2 f1 f0)),
       Triple
         (Triple (Triple u8 u7 u6) (Triple d3 d4 d5) (Triple d6 d7 d8))
         (Triple (Triple l0 l1 r6) (Triple l3 l4 r3) (Triple l6 l7 r0))
         (Triple (Triple b0 b1 b2) (Triple b3 b4 b5) (Triple b6 b7 b8)))
    | Down =>
      (Triple
         (Triple (Triple u0 u1 u2) (Triple u3 u4 u5) (Triple u6 u7 u8))
         (Triple (Triple r0 r1 r2) (Triple r3 r4 r5) (Triple l6 l7 l8))
         (Triple (Triple f0 f1 f2) (Triple f3 f4 f5) (Triple b6 b7 b8)),
       Triple
         (Triple (Triple d8 d7 d6) (Triple d5 d4 d3) (Triple d2 d1 d0))
         (Triple (Triple l0 l1 l2) (Triple l3 l4 l5) (Triple r6 r7 r8))
         (Triple (Triple b0 b1 b2) (Triple b3 b4 b5) (Triple f6 f7 f8)))
    | Left =>
      (Triple
         (Triple (Triple d0 u1 u2) (Triple d3 u4 u5) (Triple d6 u7 u8))
         (Triple (Triple r0 r1 r2) (Triple r3 r4 r5) (Triple r6 r7 r8))
         (Triple (Triple b8 f1 f2) (Triple b5 f4 f5) (Triple b2 f7 f8)),
       Triple
         (Triple (Triple u0 d1 d2) (Triple u3 d4 d5) (Triple u6 d7 d8))
         (Triple (Triple l8 l7 l6) (Triple l5 l4 l3) (Triple l2 l1 l0))
         (Triple (Triple b0 b1 f6) (Triple b3 b4 f3) (Triple b6 b7 f0)))
    | Back =>
      (Triple
         (Triple (Triple d8 d7 d6) (Triple u3 u4 u5) (Triple u6 u7 u8))
         (Triple (Triple r0 r1 l6) (Triple r3 r4 l3) (Triple r6 r7 l0))
         (Triple (Triple f0 f1 f2) (Triple f3 f4 f5) (Triple f6 f7 f8)),
       Triple
         (Triple (Triple d0 d1 d2) (Triple d3 d4 d5) (Triple u2 u1 u0))
         (Triple (Triple r8 l1 l2) (Triple r5 l4 l5) (Triple r2 l7 l8))
         (Triple (Triple b8 b7 b6) (Triple b5 b4 b3) (Triple b2 b1 b0)))
    end
  end.

(** A counterclockwise turn, tabulated directly rather than as three clockwise
    turns. *)
Definition quarter_inv (f : face) (s : state) : state :=
  match s with
  | (Triple
       (Triple (Triple u0 u1 u2) (Triple u3 u4 u5) (Triple u6 u7 u8))
       (Triple (Triple r0 r1 r2) (Triple r3 r4 r5) (Triple r6 r7 r8))
       (Triple (Triple f0 f1 f2) (Triple f3 f4 f5) (Triple f6 f7 f8)),
     Triple
       (Triple (Triple d0 d1 d2) (Triple d3 d4 d5) (Triple d6 d7 d8))
       (Triple (Triple l0 l1 l2) (Triple l3 l4 l5) (Triple l6 l7 l8))
       (Triple (Triple b0 b1 b2) (Triple b3 b4 b5) (Triple b6 b7 b8))) =>
    match f with
    | Up =>
      (Triple
         (Triple (Triple u2 u5 u8) (Triple u1 u4 u7) (Triple u0 u3 u6))
         (Triple (Triple f0 f1 f2) (Triple r3 r4 r5) (Triple r6 r7 r8))
         (Triple (Triple l0 l1 l2) (Triple f3 f4 f5) (Triple f6 f7 f8)),
       Triple
         (Triple (Triple d0 d1 d2) (Triple d3 d4 d5) (Triple d6 d7 d8))
         (Triple (Triple b0 b1 b2) (Triple l3 l4 l5) (Triple l6 l7 l8))
         (Triple (Triple r0 r1 r2) (Triple b3 b4 b5) (Triple b6 b7 b8)))
    | Right =>
      (Triple
         (Triple (Triple u0 u1 b6) (Triple u3 u4 b3) (Triple u6 u7 b0))
         (Triple (Triple r2 r5 r8) (Triple r1 r4 r7) (Triple r0 r3 r6))
         (Triple (Triple f0 f1 u2) (Triple f3 f4 u5) (Triple f6 f7 u8)),
       Triple
         (Triple (Triple d0 d1 f2) (Triple d3 d4 f5) (Triple d6 d7 f8))
         (Triple (Triple l0 l1 l2) (Triple l3 l4 l5) (Triple l6 l7 l8))
         (Triple (Triple d8 b1 b2) (Triple d5 b4 b5) (Triple d2 b7 b8)))
    | Front =>
      (Triple
         (Triple (Triple u0 u1 u2) (Triple u3 u4 u5) (Triple r0 r3 r6))
         (Triple (Triple d2 r1 r2) (Triple d1 r4 r5) (Triple d0 r7 r8))
         (Triple (Triple f2 f5 f8) (Triple f1 f4 f7) (Triple f0 f3 f6)),
       Triple
         (Triple (Triple l2 l5 l8) (Triple d3 d4 d5) (Triple d6 d7 d8))
         (Triple (Triple l0 l1 u8) (Triple l3 l4 u7) (Triple l6 l7 u6))
         (Triple (Triple b0 b1 b2) (Triple b3 b4 b5) (Triple b6 b7 b8)))
    | Down =>
      (Triple
         (Triple (Triple u0 u1 u2) (Triple u3 u4 u5) (Triple u6 u7 u8))
         (Triple (Triple r0 r1 r2) (Triple r3 r4 r5) (Triple b6 b7 b8))
         (Triple (Triple f0 f1 f2) (Triple f3 f4 f5) (Triple r6 r7 r8)),
       Triple
         (Triple (Triple d2 d5 d8) (Triple d1 d4 d7) (Triple d0 d3 d6))
         (Triple (Triple l0 l1 l2) (Triple l3 l4 l5) (Triple f6 f7 f8))
         (Triple (Triple b0 b1 b2) (Triple b3 b4 b5) (Triple l6 l7 l8)))
    | Left =>
      (Triple
         (Triple (Triple f0 u1 u2) (Triple f3 u4 u5) (Triple f6 u7 u8))
         (Triple (Triple r0 r1 r2) (Triple r3 r4 r5) (Triple r6 r7 r8))
         (Triple (Triple d0 f1 f2) (Triple d3 f4 f5) (Triple d6 f7 f8)),
       Triple
         (Triple (Triple b8 d1 d2) (Triple b5 d4 d5) (Triple b2 d7 d8))
         (Triple (Triple l2 l5 l8) (Triple l1 l4 l7) (Triple l0 l3 l6))
         (Triple (Triple b0 b1 u6) (Triple b3 b4 u3) (Triple b6 b7 u0)))
    | Back =>
      (Triple
         (Triple (Triple l6 l3 l0) (Triple u3 u4 u5) (Triple u6 u7 u8))
         (Triple (Triple r0 r1 u0) (Triple r3 r4 u1) (Triple r6 r7 u2))
         (Triple (Triple f0 f1 f2) (Triple f3 f4 f5) (Triple f6 f7 f8)),
       Triple
         (Triple (Triple d0 d1 d2) (Triple d3 d4 d5) (Triple r8 r5 r2))
         (Triple (Triple d6 l1 l2) (Triple d7 l4 l5) (Triple d8 l7 l8))
         (Triple (Triple b2 b5 b8) (Triple b1 b4 b7) (Triple b0 b3 b6)))
    end
  end.
(* END GENERATED MOVES *)

(** Expose each sticker so concrete permutation identities reduce directly. *)
Ltac destruct_state s :=
  destruct s as [a b]; unfold grid in *;
  repeat match goal with
  | x : triple _ |- _ => destruct x
  end.

(** Four clockwise quarter turns return every sticker to its original slot. *)
Lemma quarter_four f s : quarter f (quarter f (quarter f (quarter f s))) = s.
Proof.
  destruct f; destruct_state s; reflexivity.
Qed.

(** The half-turn table is exactly two clockwise quarter turns, so the direct
    definition may be unfolded wherever a proof prefers to reason about
    quarter turns. *)
Lemma half_spec f s : half f s = quarter f (quarter f s).
Proof.
  destruct f; destruct_state s; reflexivity.
Qed.

(** The counterclockwise table is exactly three clockwise quarter turns. *)
Lemma quarter_inv_spec f s : quarter_inv f s = quarter f (quarter f (quarter f s)).
Proof.
  destruct f; destruct_state s; reflexivity.
Qed.

(** * Moves and sequences *)

(** Quarter, half, and inverse quarter turns each cost one search step. *)
Inductive turns := CW | Half | CCW.

(** A face together with a turn amount describes one legal move. *)
Definition move := (face * turns)%type.

(** All 18 face turns are tried in a fixed order to break shortest-path ties. *)
Definition Movel : list move := list_prod faces [CW; Half; CCW].

(** Every legal move is available to the search. *)
Lemma moves_complete m : In m Movel.
Proof.
  destruct m as [f t]; apply in_prod.
  - apply faces_complete.
  - destruct t; simpl; auto.
Qed.

(** Each turn amount reads its own table, so a move rebuilds the 54 stickers
    once however far the face is turned. *)
Definition m2f (m : move) (s : state) : state :=
  let (f, t) := m in
  match t with
  | CW => quarter f s
  | Half => half f s
  | CCW => quarter_inv f s
  end.

(** Restate a move as repeated clockwise quarter turns. Proofs about moves
    reduce with this and then argue about [quarter] alone. *)
Ltac unfold_moves := cbn [m2f]; rewrite ?half_spec, ?quarter_inv_spec.

(** Reversing a quarter turn undoes it; a half turn is its own inverse. *)
Definition minv (m : move) : move :=
  let (f, t) := m in
  (f, match t with CW => CCW | Half => Half | CCW => CW end).

(** Following any move by its inverse restores the entire cube. *)
Lemma moves_inv m s : m2f (minv m) (m2f m s) = s.
Proof.
  destruct m as [f t]; destruct t; cbn [minv]; unfold_moves; apply quarter_four.
Qed.

(** Inverting a move twice recovers the original move. *)
Lemma minv_involutive m : minv (minv m) = m.
Proof.
  destruct m as [f []]; reflexivity.
Qed.

(** A sequence acts left to right, passing each resulting cube to the next move. *)
Definition run (s : state) (p : list move) : state :=
  fold_left (fun s m => m2f m s) p s.

(** Executing concatenated sequences is the same as executing them in stages. *)
Lemma run_app s p q : run s (p ++ q) = run (run s p) q.
Proof.
  apply fold_left_app.
Qed.

(** Undoing a sequence requires reversing both its order and its moves. *)
Definition inverse (p : list move) : list move := rev (map minv p).

(** The inverse sequence retraces the original path back to its starting cube. *)
Lemma run_inverse s p : run (run s p) (inverse p) = s.
Proof.
  revert s; induction p as [| m p IH]; intro s; simpl; auto.
  unfold inverse in *; simpl; rewrite run_app, IH.
  simpl; apply moves_inv.
Qed.

(** * Physical validity *)

(** A state is reachable when legal moves can scramble the solved cube into it. *)
Definition reachable (s : state) : Prop := exists p, run init_state p = s.

(** Physical validity is reachability, rather than an algebraic cubie test. *)
Definition valid_state : state -> Prop := reachable.

(** The empty scramble witnesses that the solved cube is physically valid. *)
Lemma valid_state_init : valid_state init_state.
Proof.
  exists []; reflexivity.
Qed.

(** Appending one legal move to a scramble preserves physical validity. *)
Lemma move_valid m s : valid_state s -> valid_state (m2f m s).
Proof.
  intros [p <-]; exists (p ++ [m]); rewrite run_app; reflexivity.
Qed.

(** Reversing legal sequences equates reachability with having a solution. *)
Lemma valid_iff_solvable s : valid_state s <-> exists p, run s p = init_state.
Proof.
  split; intros [p H]; exists (inverse p).
  - subst; apply run_inverse.
  - rewrite <- H; apply run_inverse.
Qed.
