(* Generated by scripts/generate_chain.py. Do not edit: run the script.
   As in ChainTables.v, every entry is rechecked below, including that its
   sequence uses only moves the second phase may make. *)

From Stdlib Require Import Arith List Lia.
From Rubik Require Export Domino.
Import ListNotations.

(** * Tables for solving inside the subgroup

    Seven corner stages, then seven for the outer edges, then two for the
    slice. The eighth corner, the eighth outer edge and the last two slice
    edges have no table; what they must hold is forced. *)

Definition dctab_0 : ctable :=
  [((URF, T0), []);
   ((UFL, T0), [(Front, Half); (Down, CCW); (Front, Half); (Right, Half); (Down, CCW); (Right, Half); (Down, CW); (Right, Half); (Up, CCW); (Back, Half); (Down, Half); (Back, Half); (Right, Half); (Up, Half); (Front, Half); (Up, CCW)]);
   ((ULB, T0), [(Right, Half); (Up, Half); (Front, Half); (Up, CCW); (Right, Half); (Front, Half); (Up, Half); (Left, Half); (Back, Half); (Down, CCW); (Back, Half); (Left, Half); (Up, Half); (Right, Half); (Up, CCW)]);
   ((UBR, T0), [(Right, Half); (Up, CCW); (Right, Half); (Up, CW); (Right, Half); (Back, Half); (Down, CW); (Left, Half); (Down, CCW); (Back, Half); (Right, Half); (Up, Half); (Right, Half); (Up, Half); (Right, Half); (Up, CCW)]);
   ((DFR, T0), [(Up, CCW); (Left, Half); (Back, Half); (Down, CW); (Back, Half); (Down, Half); (Back, Half); (Left, Half); (Up, CCW); (Left, Half); (Down, Half); (Left, Half); (Front, Half); (Up, CCW); (Right, Half); (Up, CCW)]);
   ((DLF, T0), [(Left, Half); (Down, CCW); (Left, Half); (Down, Half); (Front, Half); (Up, CCW); (Front, Half); (Right, Half); (Up, Half); (Back, Half); (Left, Half); (Up, CW); (Back, Half); (Right, Half); (Up, Half)]);
   ((DBL, T0), [(Down, CCW); (Back, Half); (Up, CW); (Right, Half); (Front, Half); (Up, Half); (Back, Half); (Up, CW); (Back, Half); (Right, Half); (Up, Half); (Left, Half); (Up, CCW); (Front, Half); (Right, Half); (Up, CCW)]);
   ((DRB, T0), [(Front, Half); (Down, CCW); (Front, Half); (Left, Half); (Up, Half); (Back, Half); (Right, Half); (Up, CCW); (Back, Half); (Left, Half); (Up, Half); (Right, Half); (Up, CCW); (Right, Half); (Up, Half)])].

Definition dctab_1 : ctable :=
  [((UFL, T0), []);
   ((ULB, T0), [(Left, Half); (Down, CCW); (Back, Half); (Down, CW); (Left, Half); (Front, Half); (Up, CW); (Front, Half); (Up, CCW); (Front, Half); (Right, Half); (Up, Half); (Right, Half); (Up, Half); (Right, Half); (Up, CCW)]);
   ((UBR, T0), [(Front, Half); (Right, Half); (Down, Half); (Back, Half); (Left, Half); (Down, CCW); (Back, Half); (Right, Half); (Up, Half); (Right, Half); (Down, CCW); (Right, Half); (Up, Half); (Front, Half); (Up, CCW)]);
   ((DFR, T0), [(Front, Half); (Right, Half); (Up, CCW); (Right, Half); (Front, Half); (Up, Half); (Front, Half); (Up, CCW); (Right, Half); (Up, Half); (Front, Half); (Up, CCW); (Front, Half); (Right, Half); (Up, Half)]);
   ((DLF, T0), [(Back, Half); (Down, CW); (Left, Half); (Up, CCW); (Left, Half); (Back, Half); (Down, CCW); (Front, Half); (Up, CW); (Front, Half); (Up, CCW); (Front, Half); (Right, Half); (Up, CW); (Right, Half); (Up, CCW)]);
   ((DBL, T0), [(Right, Half); (Back, Half); (Down, CW); (Left, Half); (Back, Half); (Down, Half); (Right, Half); (Front, Half); (Down, CCW); (Front, Half); (Down, Half); (Right, Half); (Up, CCW); (Right, Half); (Up, Half)]);
   ((DRB, T0), [(Up, CCW); (Front, Half); (Down, CCW); (Front, Half); (Left, Half); (Up, Half); (Back, Half); (Right, Half); (Up, CCW); (Back, Half); (Left, Half); (Up, Half); (Right, Half); (Up, CCW); (Right, Half); (Up, CCW)])].

Definition dctab_2 : ctable :=
  [((ULB, T0), []);
   ((UBR, T0), [(Left, Half); (Down, Half); (Right, Half); (Up, Half); (Right, Half); (Back, Half); (Up, CCW); (Back, Half); (Down, CW); (Left, Half); (Front, Half); (Down, CW); (Right, Half); (Up, CCW); (Right, Half); (Up, CCW)]);
   ((DFR, T0), [(Up, CCW); (Front, Half); (Right, Half); (Up, CCW); (Right, Half); (Front, Half); (Up, Half); (Front, Half); (Up, CCW); (Right, Half); (Up, Half); (Front, Half); (Up, CCW); (Front, Half); (Right, Half); (Up, CCW)]);
   ((DLF, T0), [(Front, Half); (Down, CCW); (Front, Half); (Left, Half); (Down, Half); (Back, Half); (Right, Half); (Down, CW); (Back, Half); (Left, Half); (Down, Half); (Right, Half); (Up, CCW); (Right, Half); (Up, Half)]);
   ((DBL, T0), [(Down, CCW); (Front, Half); (Right, Half); (Down, CW); (Back, Half); (Right, Half); (Up, Half); (Back, Half); (Right, Half); (Up, CCW); (Back, Half); (Up, Half); (Right, Half); (Up, CCW); (Right, Half); (Up, CCW)]);
   ((DRB, T0), [(Back, Half); (Left, Half); (Down, CW); (Left, Half); (Back, Half); (Up, Half); (Front, Half); (Up, CCW); (Right, Half); (Up, Half); (Front, Half); (Up, CCW); (Front, Half); (Right, Half); (Up, Half)])].

Definition dctab_3 : ctable :=
  [((UBR, T0), []);
   ((DFR, T0), [(Left, Half); (Back, Half); (Down, CW); (Back, Half); (Down, Half); (Back, Half); (Left, Half); (Up, CCW); (Left, Half); (Down, Half); (Left, Half); (Front, Half); (Up, CCW); (Right, Half); (Up, Half)]);
   ((DLF, T0), [(Down, CCW); (Left, Half); (Down, CCW); (Left, Half); (Down, Half); (Left, Half); (Back, Half); (Down, CW); (Back, Half); (Left, Half); (Up, Half); (Front, Half); (Right, Half); (Up, CCW); (Right, Half); (Up, CCW)]);
   ((DBL, T0), [(Right, Half); (Down, CW); (Back, Half); (Left, Half); (Down, Half); (Right, Half); (Down, CW); (Right, Half); (Back, Half); (Up, Half); (Back, Half); (Up, CCW); (Back, Half); (Right, Half); (Up, Half)]);
   ((DRB, T0), [(Right, Half); (Back, Half); (Down, CW); (Left, Half); (Down, CCW); (Left, Half); (Down, CW); (Front, Half); (Down, CCW); (Left, Half); (Back, Half); (Up, CCW); (Right, Half); (Up, CW); (Right, Half); (Up, CCW)])].

Definition dctab_4 : ctable :=
  [((DFR, T0), []);
   ((DLF, T0), [(Front, Half); (Up, CCW); (Front, Half); (Left, Half); (Down, CCW); (Back, Half); (Down, CW); (Left, Half); (Up, CCW); (Right, Half); (Up, Half); (Right, Half); (Front, Half); (Up, Half); (Right, Half); (Up, CCW)]);
   ((DBL, T0), [(Right, Half); (Back, Half); (Up, Half); (Front, Half); (Up, CW); (Left, Half); (Back, Half); (Up, Half); (Front, Half); (Down, CCW); (Front, Half); (Right, Half); (Down, Half); (Right, Half); (Up, CCW)]);
   ((DRB, T0), [(Front, Half); (Up, Half); (Right, Half); (Front, Half); (Up, Half); (Front, Half); (Down, CCW); (Right, Half); (Down, CW); (Back, Half); (Up, CCW); (Back, Half); (Right, Half); (Up, CCW); (Right, Half); (Up, CCW)])].

Definition dctab_5 : ctable :=
  [((DLF, T0), []);
   ((DBL, T0), [(Left, Half); (Down, CCW); (Back, Half); (Right, Half); (Up, CCW); (Right, Half); (Down, CW); (Back, Half); (Up, CCW); (Front, Half); (Up, Half); (Front, Half); (Left, Half); (Up, Half); (Front, Half); (Up, CCW)]);
   ((DRB, T0), [(Right, Half); (Front, Half); (Up, Half); (Front, Half); (Up, CCW); (Right, Half); (Front, Half); (Up, Half); (Front, Half); (Up, CW); (Front, Half); (Right, Half); (Up, Half); (Right, Half); (Up, CCW)])].

Definition dctab_6 : ctable :=
  [((DBL, T0), []);
   ((DRB, T0), [(Back, Half); (Up, CW); (Right, Half); (Down, CCW); (Left, Half); (Down, Half); (Left, Half); (Front, Half); (Up, Half); (Right, Half); (Up, CCW); (Left, Half); (Up, CCW); (Front, Half); (Right, Half); (Up, CCW)])].

Definition detab_0 : etable :=
  [((UR, F0), []);
   ((UF, F0), [(Front, Half); (Down, CCW); (Right, Half); (Front, Half); (Down, Half); (Front, Half); (Right, Half); (Down, Half); (Front, Half); (Down, CCW); (Front, Half)]);
   ((UL, F0), [(Front, Half); (Up, Half); (Front, Half); (Up, Half); (Front, Half); (Up, Half)]);
   ((UB, F0), [(Back, Half); (Down, CCW); (Front, Half); (Down, Half); (Right, Half); (Front, Half); (Down, Half); (Front, Half); (Right, Half); (Down, CCW); (Back, Half)]);
   ((DR, F0), [(Front, Half); (Up, Half); (Right, Half); (Front, Half); (Up, Half); (Front, Half); (Right, Half); (Up, Half)]);
   ((DF, F0), [(Down, CCW); (Right, Half); (Front, Half); (Down, Half); (Front, Half); (Right, Half); (Down, Half); (Front, Half); (Down, CCW)]);
   ((DL, F0), [(Right, Half); (Back, Half); (Down, Half); (Back, Half); (Right, Half); (Up, Half); (Front, Half); (Up, Half)]);
   ((DB, F0), [(Down, CCW); (Front, Half); (Down, Half); (Right, Half); (Front, Half); (Down, Half); (Front, Half); (Right, Half); (Down, CCW)])].

Definition detab_1 : etable :=
  [((UF, F0), []);
   ((UL, F0), [(Front, Half); (Down, CCW); (Back, Half); (Up, Half); (Left, Half); (Back, Half); (Down, Half); (Front, Half); (Right, Half); (Down, CCW); (Front, Half)]);
   ((UB, F0), [(Up, CCW); (Front, Half); (Up, Half); (Front, Half); (Up, Half); (Front, Half); (Up, CCW)]);
   ((DR, F0), [(Up, CCW); (Front, Half); (Up, Half); (Right, Half); (Front, Half); (Up, Half); (Front, Half); (Right, Half); (Up, CCW)]);
   ((DF, F0), [(Up, CCW); (Down, CCW); (Right, Half); (Back, Half); (Up, CCW); (Down, CCW); (Left, Half); (Back, Half); (Up, Half); (Right, Half)]);
   ((DL, F0), [(Up, CCW); (Right, Half); (Back, Half); (Down, Half); (Back, Half); (Right, Half); (Up, Half); (Front, Half); (Up, CCW)]);
   ((DB, F0), [(Front, Half); (Down, CCW); (Front, Half); (Down, Half); (Front, Half); (Down, Half); (Front, Half); (Down, CCW); (Front, Half)])].

Definition detab_2 : etable :=
  [((UL, F0), []);
   ((UB, F0), [(Back, Half); (Down, CCW); (Right, Half); (Back, Half); (Up, Half); (Back, Half); (Right, Half); (Down, Half); (Front, Half); (Down, CCW); (Back, Half)]);
   ((DR, F0), [(Right, Half); (Front, Half); (Up, Half); (Front, Half); (Right, Half); (Up, Half); (Front, Half); (Up, Half)]);
   ((DF, F0), [(Down, CCW); (Back, Half); (Up, Half); (Left, Half); (Back, Half); (Down, Half); (Front, Half); (Right, Half); (Down, CCW)]);
   ((DL, F0), [(Back, Half); (Down, Half); (Left, Half); (Back, Half); (Up, Half); (Front, Half); (Right, Half); (Up, Half)]);
   ((DB, F0), [(Down, CCW); (Right, Half); (Back, Half); (Up, Half); (Back, Half); (Right, Half); (Down, Half); (Front, Half); (Down, CCW)])].

Definition detab_3 : etable :=
  [((UB, F0), []);
   ((DR, F0), [(Up, CCW); (Right, Half); (Front, Half); (Up, Half); (Front, Half); (Right, Half); (Up, Half); (Front, Half); (Up, CCW)]);
   ((DF, F0), [(Front, Half); (Up, CCW); (Front, Half); (Up, Half); (Front, Half); (Up, Half); (Front, Half); (Up, CCW); (Front, Half)]);
   ((DL, F0), [(Up, CCW); (Back, Half); (Down, Half); (Left, Half); (Back, Half); (Up, Half); (Front, Half); (Right, Half); (Up, CCW)]);
   ((DB, F0), [(Up, CCW); (Down, CCW); (Left, Half); (Back, Half); (Up, CCW); (Down, CCW); (Left, Half); (Front, Half); (Up, Half); (Right, Half)])].

Definition detab_4 : etable :=
  [((DR, F0), []);
   ((DF, F0), [(Front, Half); (Up, CCW); (Front, Half); (Up, Half); (Right, Half); (Front, Half); (Up, Half); (Front, Half); (Right, Half); (Up, CCW); (Front, Half)]);
   ((DL, F0), [(Back, Half); (Down, Half); (Back, Half); (Up, Half); (Front, Half); (Up, Half)]);
   ((DB, F0), [(Back, Half); (Up, CCW); (Right, Half); (Front, Half); (Up, Half); (Front, Half); (Right, Half); (Up, Half); (Front, Half); (Up, CCW); (Back, Half)])].

Definition detab_5 : etable :=
  [((DF, F0), []);
   ((DL, F0), [(Front, Half); (Up, CCW); (Right, Half); (Back, Half); (Down, Half); (Back, Half); (Right, Half); (Up, Half); (Front, Half); (Up, CCW); (Front, Half)]);
   ((DB, F0), [(Down, CCW); (Front, Half); (Down, Half); (Front, Half); (Down, Half); (Front, Half); (Down, CCW)])].

Definition detab_6 : etable :=
  [((DL, F0), []);
   ((DB, F0), [(Back, Half); (Up, CCW); (Back, Half); (Down, Half); (Left, Half); (Back, Half); (Up, Half); (Front, Half); (Right, Half); (Up, CCW); (Back, Half)])].

Definition detab_8 : etable :=
  [((FR, F0), []);
   ((FL, F0), [(Down, CCW); (Left, Half); (Up, CCW); (Down, CW); (Front, Half); (Up, CW)]);
   ((BL, F0), [(Down, CW); (Front, Half); (Up, CW); (Down, CCW); (Left, Half); (Up, CCW)]);
   ((BR, F0), [(Down, CW); (Right, Half); (Up, CW); (Down, CCW); (Front, Half); (Up, CCW)])].

Definition detab_9 : etable :=
  [((FL, F0), []);
   ((BL, F0), [(Down, CCW); (Back, Half); (Up, CCW); (Down, CW); (Left, Half); (Up, CW)]);
   ((BR, F0), [(Down, CW); (Left, Half); (Up, CW); (Down, CCW); (Back, Half); (Up, CCW)])].

(** The stages in the order they run. *)
Definition dcorner_stages : list stage := [Cstage URF dctab_0 16; Cstage UFL dctab_1 16; Cstage ULB dctab_2 16; Cstage UBR dctab_3 16; Cstage DFR dctab_4 16; Cstage DLF dctab_5 16; Cstage DBL dctab_6 16].
Definition dud_stages : list stage := [Estage UR detab_0 11; Estage UF detab_1 11; Estage UL detab_2 11; Estage UB detab_3 10; Estage DR detab_4 11; Estage DF detab_5 11; Estage DL detab_6 11].
Definition dslice_stages : list stage := [Estage FR detab_8 6; Estage FL detab_9 6].

(** The eight outer edge slots, once they are all finished. *)
Definition ud_done : list edge := [DB; DL; DF; DR; UB; UL; UF; UR].

Lemma dcorner_stages_ok : chain2_ok [] [] dcorner_stages = true.
Proof. vm_compute; reflexivity. Qed.

Lemma dcorner_stages_slots :
  stagesc dcorner_stages = [DBL; DLF; DFR; UBR; ULB; UFL; URF].
Proof. vm_compute; reflexivity. Qed.

Lemma dud_stages_ok : chain2_ok all_corner_slots [] dud_stages = true.
Proof. vm_compute; reflexivity. Qed.

Lemma dud_stages_slots : stagese dud_stages = [DL; DF; DR; UB; UL; UF; UR].
Proof. vm_compute; reflexivity. Qed.

Lemma dud_stages_corners : stagesc dud_stages = [].
Proof. vm_compute; reflexivity. Qed.

Lemma dslice_stages_ok : chain2_ok all_corner_slots ud_done dslice_stages = true.
Proof. vm_compute; reflexivity. Qed.

Lemma dslice_stages_slots :
  stagese dslice_stages = [FL; FR].
Proof. vm_compute; reflexivity. Qed.

Lemma dslice_stages_corners : stagesc dslice_stages = [].
Proof. vm_compute; reflexivity. Qed.

(** The longest answer the tables allow, added up over the stages. *)
Definition domino_bound : nat := 200.

Lemma domino_bound_ok :
  chain_bound dslice_stages + (chain_bound dud_stages + chain_bound dcorner_stages)
  = domino_bound.
Proof. vm_compute; reflexivity. Qed.
