(* Generated by scripts/generate_parity.py. Do not edit: run the script.
   The permutations are read from theories/CubieTables.v, so the two files
   cannot drift apart without this one failing to compile. *)

From Stdlib Require Import Arith List Lia Permutation Bool.
From Rubik Require Export Parity.
Import ListNotations.

(** * A quarter turn flips each list's parity

    One lemma per face for the corner slots and one for the edge slots. Each
    turn is a four-cycle, which three exchanges undo, and each exchange flips
    the parity. *)


(** The corner slots after a clockwise turn of Up. *)
Lemma parity_corners_Up r0 r1 r2 r3 r4 r5 r6 r7 :
  NoDup [r0; r1; r2; r3; r4; r5; r6; r7] ->
  parity [r3; r0; r1; r2; r4; r5; r6; r7] = negb (parity [r0; r1; r2; r3; r4; r5; r6; r7]).
Proof.
  intro H0.
  assert (S0 : parity [r0; r1; r2; r3; r4; r5; r6; r7]
            = negb (parity [r3; r1; r2; r0; r4; r5; r6; r7]))
    by (apply (parity_exchange [] r0 [r1; r2] r3 [r4; r5; r6; r7]); exact H0).
  assert (H1 : NoDup [r3; r1; r2; r0; r4; r5; r6; r7])
    by (apply (nodup_exchange [] r0 [r1; r2] r3 [r4; r5; r6; r7]); exact H0).
  assert (S1 : parity [r3; r1; r2; r0; r4; r5; r6; r7]
            = negb (parity [r3; r0; r2; r1; r4; r5; r6; r7]))
    by (apply (parity_exchange [r3] r1 [r2] r0 [r4; r5; r6; r7]); exact H1).
  assert (H2 : NoDup [r3; r0; r2; r1; r4; r5; r6; r7])
    by (apply (nodup_exchange [r3] r1 [r2] r0 [r4; r5; r6; r7]); exact H1).
  assert (S2 : parity [r3; r0; r2; r1; r4; r5; r6; r7]
            = negb (parity [r3; r0; r1; r2; r4; r5; r6; r7]))
    by (apply (parity_exchange [r3; r0] r2 [] r1 [r4; r5; r6; r7]); exact H2).
  assert (E : parity [r0; r1; r2; r3; r4; r5; r6; r7] = negb (parity [r3; r0; r1; r2; r4; r5; r6; r7]))
    by (rewrite S0, S1, S2, !Bool.negb_involutive; reflexivity).
  rewrite E, Bool.negb_involutive; reflexivity.
Qed.

Lemma nodup_corners_Up (r0 r1 r2 r3 r4 r5 r6 r7 : nat) :
  NoDup [r0; r1; r2; r3; r4; r5; r6; r7] -> NoDup [r3; r0; r1; r2; r4; r5; r6; r7].
Proof.
  intro H0.
  assert (H1 : NoDup [r3; r1; r2; r0; r4; r5; r6; r7])
    by (apply (nodup_exchange [] r0 [r1; r2] r3 [r4; r5; r6; r7]); exact H0).
  assert (H2 : NoDup [r3; r0; r2; r1; r4; r5; r6; r7])
    by (apply (nodup_exchange [r3] r1 [r2] r0 [r4; r5; r6; r7]); exact H1).
  assert (H3 : NoDup [r3; r0; r1; r2; r4; r5; r6; r7])
    by (apply (nodup_exchange [r3; r0] r2 [] r1 [r4; r5; r6; r7]); exact H2).
  exact H3.
Qed.

(** And the edge slots. *)
Lemma parity_edges_Up e0 e1 e2 e3 e4 e5 e6 e7 e8 e9 e10 e11 :
  NoDup [e0; e1; e2; e3; e4; e5; e6; e7; e8; e9; e10; e11] ->
  parity [e3; e0; e1; e2; e4; e5; e6; e7; e8; e9; e10; e11] = negb (parity [e0; e1; e2; e3; e4; e5; e6; e7; e8; e9; e10; e11]).
Proof.
  intro H0.
  assert (S0 : parity [e0; e1; e2; e3; e4; e5; e6; e7; e8; e9; e10; e11]
            = negb (parity [e3; e1; e2; e0; e4; e5; e6; e7; e8; e9; e10; e11]))
    by (apply (parity_exchange [] e0 [e1; e2] e3 [e4; e5; e6; e7; e8; e9; e10; e11]); exact H0).
  assert (H1 : NoDup [e3; e1; e2; e0; e4; e5; e6; e7; e8; e9; e10; e11])
    by (apply (nodup_exchange [] e0 [e1; e2] e3 [e4; e5; e6; e7; e8; e9; e10; e11]); exact H0).
  assert (S1 : parity [e3; e1; e2; e0; e4; e5; e6; e7; e8; e9; e10; e11]
            = negb (parity [e3; e0; e2; e1; e4; e5; e6; e7; e8; e9; e10; e11]))
    by (apply (parity_exchange [e3] e1 [e2] e0 [e4; e5; e6; e7; e8; e9; e10; e11]); exact H1).
  assert (H2 : NoDup [e3; e0; e2; e1; e4; e5; e6; e7; e8; e9; e10; e11])
    by (apply (nodup_exchange [e3] e1 [e2] e0 [e4; e5; e6; e7; e8; e9; e10; e11]); exact H1).
  assert (S2 : parity [e3; e0; e2; e1; e4; e5; e6; e7; e8; e9; e10; e11]
            = negb (parity [e3; e0; e1; e2; e4; e5; e6; e7; e8; e9; e10; e11]))
    by (apply (parity_exchange [e3; e0] e2 [] e1 [e4; e5; e6; e7; e8; e9; e10; e11]); exact H2).
  assert (E : parity [e0; e1; e2; e3; e4; e5; e6; e7; e8; e9; e10; e11] = negb (parity [e3; e0; e1; e2; e4; e5; e6; e7; e8; e9; e10; e11]))
    by (rewrite S0, S1, S2, !Bool.negb_involutive; reflexivity).
  rewrite E, Bool.negb_involutive; reflexivity.
Qed.

Lemma nodup_edges_Up (e0 e1 e2 e3 e4 e5 e6 e7 e8 e9 e10 e11 : nat) :
  NoDup [e0; e1; e2; e3; e4; e5; e6; e7; e8; e9; e10; e11] -> NoDup [e3; e0; e1; e2; e4; e5; e6; e7; e8; e9; e10; e11].
Proof.
  intro H0.
  assert (H1 : NoDup [e3; e1; e2; e0; e4; e5; e6; e7; e8; e9; e10; e11])
    by (apply (nodup_exchange [] e0 [e1; e2] e3 [e4; e5; e6; e7; e8; e9; e10; e11]); exact H0).
  assert (H2 : NoDup [e3; e0; e2; e1; e4; e5; e6; e7; e8; e9; e10; e11])
    by (apply (nodup_exchange [e3] e1 [e2] e0 [e4; e5; e6; e7; e8; e9; e10; e11]); exact H1).
  assert (H3 : NoDup [e3; e0; e1; e2; e4; e5; e6; e7; e8; e9; e10; e11])
    by (apply (nodup_exchange [e3; e0] e2 [] e1 [e4; e5; e6; e7; e8; e9; e10; e11]); exact H2).
  exact H3.
Qed.

(** The corner slots after a clockwise turn of Right. *)
Lemma parity_corners_Right r0 r1 r2 r3 r4 r5 r6 r7 :
  NoDup [r0; r1; r2; r3; r4; r5; r6; r7] ->
  parity [r4; r1; r2; r0; r7; r5; r6; r3] = negb (parity [r0; r1; r2; r3; r4; r5; r6; r7]).
Proof.
  intro H0.
  assert (S0 : parity [r0; r1; r2; r3; r4; r5; r6; r7]
            = negb (parity [r4; r1; r2; r3; r0; r5; r6; r7]))
    by (apply (parity_exchange [] r0 [r1; r2; r3] r4 [r5; r6; r7]); exact H0).
  assert (H1 : NoDup [r4; r1; r2; r3; r0; r5; r6; r7])
    by (apply (nodup_exchange [] r0 [r1; r2; r3] r4 [r5; r6; r7]); exact H0).
  assert (S1 : parity [r4; r1; r2; r3; r0; r5; r6; r7]
            = negb (parity [r4; r1; r2; r0; r3; r5; r6; r7]))
    by (apply (parity_exchange [r4; r1; r2] r3 [] r0 [r5; r6; r7]); exact H1).
  assert (H2 : NoDup [r4; r1; r2; r0; r3; r5; r6; r7])
    by (apply (nodup_exchange [r4; r1; r2] r3 [] r0 [r5; r6; r7]); exact H1).
  assert (S2 : parity [r4; r1; r2; r0; r3; r5; r6; r7]
            = negb (parity [r4; r1; r2; r0; r7; r5; r6; r3]))
    by (apply (parity_exchange [r4; r1; r2; r0] r3 [r5; r6] r7 []); exact H2).
  assert (E : parity [r0; r1; r2; r3; r4; r5; r6; r7] = negb (parity [r4; r1; r2; r0; r7; r5; r6; r3]))
    by (rewrite S0, S1, S2, !Bool.negb_involutive; reflexivity).
  rewrite E, Bool.negb_involutive; reflexivity.
Qed.

Lemma nodup_corners_Right (r0 r1 r2 r3 r4 r5 r6 r7 : nat) :
  NoDup [r0; r1; r2; r3; r4; r5; r6; r7] -> NoDup [r4; r1; r2; r0; r7; r5; r6; r3].
Proof.
  intro H0.
  assert (H1 : NoDup [r4; r1; r2; r3; r0; r5; r6; r7])
    by (apply (nodup_exchange [] r0 [r1; r2; r3] r4 [r5; r6; r7]); exact H0).
  assert (H2 : NoDup [r4; r1; r2; r0; r3; r5; r6; r7])
    by (apply (nodup_exchange [r4; r1; r2] r3 [] r0 [r5; r6; r7]); exact H1).
  assert (H3 : NoDup [r4; r1; r2; r0; r7; r5; r6; r3])
    by (apply (nodup_exchange [r4; r1; r2; r0] r3 [r5; r6] r7 []); exact H2).
  exact H3.
Qed.

(** And the edge slots. *)
Lemma parity_edges_Right e0 e1 e2 e3 e4 e5 e6 e7 e8 e9 e10 e11 :
  NoDup [e0; e1; e2; e3; e4; e5; e6; e7; e8; e9; e10; e11] ->
  parity [e8; e1; e2; e3; e11; e5; e6; e7; e4; e9; e10; e0] = negb (parity [e0; e1; e2; e3; e4; e5; e6; e7; e8; e9; e10; e11]).
Proof.
  intro H0.
  assert (S0 : parity [e0; e1; e2; e3; e4; e5; e6; e7; e8; e9; e10; e11]
            = negb (parity [e8; e1; e2; e3; e4; e5; e6; e7; e0; e9; e10; e11]))
    by (apply (parity_exchange [] e0 [e1; e2; e3; e4; e5; e6; e7] e8 [e9; e10; e11]); exact H0).
  assert (H1 : NoDup [e8; e1; e2; e3; e4; e5; e6; e7; e0; e9; e10; e11])
    by (apply (nodup_exchange [] e0 [e1; e2; e3; e4; e5; e6; e7] e8 [e9; e10; e11]); exact H0).
  assert (S1 : parity [e8; e1; e2; e3; e4; e5; e6; e7; e0; e9; e10; e11]
            = negb (parity [e8; e1; e2; e3; e11; e5; e6; e7; e0; e9; e10; e4]))
    by (apply (parity_exchange [e8; e1; e2; e3] e4 [e5; e6; e7; e0; e9; e10] e11 []); exact H1).
  assert (H2 : NoDup [e8; e1; e2; e3; e11; e5; e6; e7; e0; e9; e10; e4])
    by (apply (nodup_exchange [e8; e1; e2; e3] e4 [e5; e6; e7; e0; e9; e10] e11 []); exact H1).
  assert (S2 : parity [e8; e1; e2; e3; e11; e5; e6; e7; e0; e9; e10; e4]
            = negb (parity [e8; e1; e2; e3; e11; e5; e6; e7; e4; e9; e10; e0]))
    by (apply (parity_exchange [e8; e1; e2; e3; e11; e5; e6; e7] e0 [e9; e10] e4 []); exact H2).
  assert (E : parity [e0; e1; e2; e3; e4; e5; e6; e7; e8; e9; e10; e11] = negb (parity [e8; e1; e2; e3; e11; e5; e6; e7; e4; e9; e10; e0]))
    by (rewrite S0, S1, S2, !Bool.negb_involutive; reflexivity).
  rewrite E, Bool.negb_involutive; reflexivity.
Qed.

Lemma nodup_edges_Right (e0 e1 e2 e3 e4 e5 e6 e7 e8 e9 e10 e11 : nat) :
  NoDup [e0; e1; e2; e3; e4; e5; e6; e7; e8; e9; e10; e11] -> NoDup [e8; e1; e2; e3; e11; e5; e6; e7; e4; e9; e10; e0].
Proof.
  intro H0.
  assert (H1 : NoDup [e8; e1; e2; e3; e4; e5; e6; e7; e0; e9; e10; e11])
    by (apply (nodup_exchange [] e0 [e1; e2; e3; e4; e5; e6; e7] e8 [e9; e10; e11]); exact H0).
  assert (H2 : NoDup [e8; e1; e2; e3; e11; e5; e6; e7; e0; e9; e10; e4])
    by (apply (nodup_exchange [e8; e1; e2; e3] e4 [e5; e6; e7; e0; e9; e10] e11 []); exact H1).
  assert (H3 : NoDup [e8; e1; e2; e3; e11; e5; e6; e7; e4; e9; e10; e0])
    by (apply (nodup_exchange [e8; e1; e2; e3; e11; e5; e6; e7] e0 [e9; e10] e4 []); exact H2).
  exact H3.
Qed.

(** The corner slots after a clockwise turn of Front. *)
Lemma parity_corners_Front r0 r1 r2 r3 r4 r5 r6 r7 :
  NoDup [r0; r1; r2; r3; r4; r5; r6; r7] ->
  parity [r1; r5; r2; r3; r0; r4; r6; r7] = negb (parity [r0; r1; r2; r3; r4; r5; r6; r7]).
Proof.
  intro H0.
  assert (S0 : parity [r0; r1; r2; r3; r4; r5; r6; r7]
            = negb (parity [r1; r0; r2; r3; r4; r5; r6; r7]))
    by (apply (parity_exchange [] r0 [] r1 [r2; r3; r4; r5; r6; r7]); exact H0).
  assert (H1 : NoDup [r1; r0; r2; r3; r4; r5; r6; r7])
    by (apply (nodup_exchange [] r0 [] r1 [r2; r3; r4; r5; r6; r7]); exact H0).
  assert (S1 : parity [r1; r0; r2; r3; r4; r5; r6; r7]
            = negb (parity [r1; r5; r2; r3; r4; r0; r6; r7]))
    by (apply (parity_exchange [r1] r0 [r2; r3; r4] r5 [r6; r7]); exact H1).
  assert (H2 : NoDup [r1; r5; r2; r3; r4; r0; r6; r7])
    by (apply (nodup_exchange [r1] r0 [r2; r3; r4] r5 [r6; r7]); exact H1).
  assert (S2 : parity [r1; r5; r2; r3; r4; r0; r6; r7]
            = negb (parity [r1; r5; r2; r3; r0; r4; r6; r7]))
    by (apply (parity_exchange [r1; r5; r2; r3] r4 [] r0 [r6; r7]); exact H2).
  assert (E : parity [r0; r1; r2; r3; r4; r5; r6; r7] = negb (parity [r1; r5; r2; r3; r0; r4; r6; r7]))
    by (rewrite S0, S1, S2, !Bool.negb_involutive; reflexivity).
  rewrite E, Bool.negb_involutive; reflexivity.
Qed.

Lemma nodup_corners_Front (r0 r1 r2 r3 r4 r5 r6 r7 : nat) :
  NoDup [r0; r1; r2; r3; r4; r5; r6; r7] -> NoDup [r1; r5; r2; r3; r0; r4; r6; r7].
Proof.
  intro H0.
  assert (H1 : NoDup [r1; r0; r2; r3; r4; r5; r6; r7])
    by (apply (nodup_exchange [] r0 [] r1 [r2; r3; r4; r5; r6; r7]); exact H0).
  assert (H2 : NoDup [r1; r5; r2; r3; r4; r0; r6; r7])
    by (apply (nodup_exchange [r1] r0 [r2; r3; r4] r5 [r6; r7]); exact H1).
  assert (H3 : NoDup [r1; r5; r2; r3; r0; r4; r6; r7])
    by (apply (nodup_exchange [r1; r5; r2; r3] r4 [] r0 [r6; r7]); exact H2).
  exact H3.
Qed.

(** And the edge slots. *)
Lemma parity_edges_Front e0 e1 e2 e3 e4 e5 e6 e7 e8 e9 e10 e11 :
  NoDup [e0; e1; e2; e3; e4; e5; e6; e7; e8; e9; e10; e11] ->
  parity [e0; e9; e2; e3; e4; e8; e6; e7; e1; e5; e10; e11] = negb (parity [e0; e1; e2; e3; e4; e5; e6; e7; e8; e9; e10; e11]).
Proof.
  intro H0.
  assert (S0 : parity [e0; e1; e2; e3; e4; e5; e6; e7; e8; e9; e10; e11]
            = negb (parity [e0; e9; e2; e3; e4; e5; e6; e7; e8; e1; e10; e11]))
    by (apply (parity_exchange [e0] e1 [e2; e3; e4; e5; e6; e7; e8] e9 [e10; e11]); exact H0).
  assert (H1 : NoDup [e0; e9; e2; e3; e4; e5; e6; e7; e8; e1; e10; e11])
    by (apply (nodup_exchange [e0] e1 [e2; e3; e4; e5; e6; e7; e8] e9 [e10; e11]); exact H0).
  assert (S1 : parity [e0; e9; e2; e3; e4; e5; e6; e7; e8; e1; e10; e11]
            = negb (parity [e0; e9; e2; e3; e4; e8; e6; e7; e5; e1; e10; e11]))
    by (apply (parity_exchange [e0; e9; e2; e3; e4] e5 [e6; e7] e8 [e1; e10; e11]); exact H1).
  assert (H2 : NoDup [e0; e9; e2; e3; e4; e8; e6; e7; e5; e1; e10; e11])
    by (apply (nodup_exchange [e0; e9; e2; e3; e4] e5 [e6; e7] e8 [e1; e10; e11]); exact H1).
  assert (S2 : parity [e0; e9; e2; e3; e4; e8; e6; e7; e5; e1; e10; e11]
            = negb (parity [e0; e9; e2; e3; e4; e8; e6; e7; e1; e5; e10; e11]))
    by (apply (parity_exchange [e0; e9; e2; e3; e4; e8; e6; e7] e5 [] e1 [e10; e11]); exact H2).
  assert (E : parity [e0; e1; e2; e3; e4; e5; e6; e7; e8; e9; e10; e11] = negb (parity [e0; e9; e2; e3; e4; e8; e6; e7; e1; e5; e10; e11]))
    by (rewrite S0, S1, S2, !Bool.negb_involutive; reflexivity).
  rewrite E, Bool.negb_involutive; reflexivity.
Qed.

Lemma nodup_edges_Front (e0 e1 e2 e3 e4 e5 e6 e7 e8 e9 e10 e11 : nat) :
  NoDup [e0; e1; e2; e3; e4; e5; e6; e7; e8; e9; e10; e11] -> NoDup [e0; e9; e2; e3; e4; e8; e6; e7; e1; e5; e10; e11].
Proof.
  intro H0.
  assert (H1 : NoDup [e0; e9; e2; e3; e4; e5; e6; e7; e8; e1; e10; e11])
    by (apply (nodup_exchange [e0] e1 [e2; e3; e4; e5; e6; e7; e8] e9 [e10; e11]); exact H0).
  assert (H2 : NoDup [e0; e9; e2; e3; e4; e8; e6; e7; e5; e1; e10; e11])
    by (apply (nodup_exchange [e0; e9; e2; e3; e4] e5 [e6; e7] e8 [e1; e10; e11]); exact H1).
  assert (H3 : NoDup [e0; e9; e2; e3; e4; e8; e6; e7; e1; e5; e10; e11])
    by (apply (nodup_exchange [e0; e9; e2; e3; e4; e8; e6; e7] e5 [] e1 [e10; e11]); exact H2).
  exact H3.
Qed.

(** The corner slots after a clockwise turn of Down. *)
Lemma parity_corners_Down r0 r1 r2 r3 r4 r5 r6 r7 :
  NoDup [r0; r1; r2; r3; r4; r5; r6; r7] ->
  parity [r0; r1; r2; r3; r5; r6; r7; r4] = negb (parity [r0; r1; r2; r3; r4; r5; r6; r7]).
Proof.
  intro H0.
  assert (S0 : parity [r0; r1; r2; r3; r4; r5; r6; r7]
            = negb (parity [r0; r1; r2; r3; r5; r4; r6; r7]))
    by (apply (parity_exchange [r0; r1; r2; r3] r4 [] r5 [r6; r7]); exact H0).
  assert (H1 : NoDup [r0; r1; r2; r3; r5; r4; r6; r7])
    by (apply (nodup_exchange [r0; r1; r2; r3] r4 [] r5 [r6; r7]); exact H0).
  assert (S1 : parity [r0; r1; r2; r3; r5; r4; r6; r7]
            = negb (parity [r0; r1; r2; r3; r5; r6; r4; r7]))
    by (apply (parity_exchange [r0; r1; r2; r3; r5] r4 [] r6 [r7]); exact H1).
  assert (H2 : NoDup [r0; r1; r2; r3; r5; r6; r4; r7])
    by (apply (nodup_exchange [r0; r1; r2; r3; r5] r4 [] r6 [r7]); exact H1).
  assert (S2 : parity [r0; r1; r2; r3; r5; r6; r4; r7]
            = negb (parity [r0; r1; r2; r3; r5; r6; r7; r4]))
    by (apply (parity_exchange [r0; r1; r2; r3; r5; r6] r4 [] r7 []); exact H2).
  assert (E : parity [r0; r1; r2; r3; r4; r5; r6; r7] = negb (parity [r0; r1; r2; r3; r5; r6; r7; r4]))
    by (rewrite S0, S1, S2, !Bool.negb_involutive; reflexivity).
  rewrite E, Bool.negb_involutive; reflexivity.
Qed.

Lemma nodup_corners_Down (r0 r1 r2 r3 r4 r5 r6 r7 : nat) :
  NoDup [r0; r1; r2; r3; r4; r5; r6; r7] -> NoDup [r0; r1; r2; r3; r5; r6; r7; r4].
Proof.
  intro H0.
  assert (H1 : NoDup [r0; r1; r2; r3; r5; r4; r6; r7])
    by (apply (nodup_exchange [r0; r1; r2; r3] r4 [] r5 [r6; r7]); exact H0).
  assert (H2 : NoDup [r0; r1; r2; r3; r5; r6; r4; r7])
    by (apply (nodup_exchange [r0; r1; r2; r3; r5] r4 [] r6 [r7]); exact H1).
  assert (H3 : NoDup [r0; r1; r2; r3; r5; r6; r7; r4])
    by (apply (nodup_exchange [r0; r1; r2; r3; r5; r6] r4 [] r7 []); exact H2).
  exact H3.
Qed.

(** And the edge slots. *)
Lemma parity_edges_Down e0 e1 e2 e3 e4 e5 e6 e7 e8 e9 e10 e11 :
  NoDup [e0; e1; e2; e3; e4; e5; e6; e7; e8; e9; e10; e11] ->
  parity [e0; e1; e2; e3; e5; e6; e7; e4; e8; e9; e10; e11] = negb (parity [e0; e1; e2; e3; e4; e5; e6; e7; e8; e9; e10; e11]).
Proof.
  intro H0.
  assert (S0 : parity [e0; e1; e2; e3; e4; e5; e6; e7; e8; e9; e10; e11]
            = negb (parity [e0; e1; e2; e3; e5; e4; e6; e7; e8; e9; e10; e11]))
    by (apply (parity_exchange [e0; e1; e2; e3] e4 [] e5 [e6; e7; e8; e9; e10; e11]); exact H0).
  assert (H1 : NoDup [e0; e1; e2; e3; e5; e4; e6; e7; e8; e9; e10; e11])
    by (apply (nodup_exchange [e0; e1; e2; e3] e4 [] e5 [e6; e7; e8; e9; e10; e11]); exact H0).
  assert (S1 : parity [e0; e1; e2; e3; e5; e4; e6; e7; e8; e9; e10; e11]
            = negb (parity [e0; e1; e2; e3; e5; e6; e4; e7; e8; e9; e10; e11]))
    by (apply (parity_exchange [e0; e1; e2; e3; e5] e4 [] e6 [e7; e8; e9; e10; e11]); exact H1).
  assert (H2 : NoDup [e0; e1; e2; e3; e5; e6; e4; e7; e8; e9; e10; e11])
    by (apply (nodup_exchange [e0; e1; e2; e3; e5] e4 [] e6 [e7; e8; e9; e10; e11]); exact H1).
  assert (S2 : parity [e0; e1; e2; e3; e5; e6; e4; e7; e8; e9; e10; e11]
            = negb (parity [e0; e1; e2; e3; e5; e6; e7; e4; e8; e9; e10; e11]))
    by (apply (parity_exchange [e0; e1; e2; e3; e5; e6] e4 [] e7 [e8; e9; e10; e11]); exact H2).
  assert (E : parity [e0; e1; e2; e3; e4; e5; e6; e7; e8; e9; e10; e11] = negb (parity [e0; e1; e2; e3; e5; e6; e7; e4; e8; e9; e10; e11]))
    by (rewrite S0, S1, S2, !Bool.negb_involutive; reflexivity).
  rewrite E, Bool.negb_involutive; reflexivity.
Qed.

Lemma nodup_edges_Down (e0 e1 e2 e3 e4 e5 e6 e7 e8 e9 e10 e11 : nat) :
  NoDup [e0; e1; e2; e3; e4; e5; e6; e7; e8; e9; e10; e11] -> NoDup [e0; e1; e2; e3; e5; e6; e7; e4; e8; e9; e10; e11].
Proof.
  intro H0.
  assert (H1 : NoDup [e0; e1; e2; e3; e5; e4; e6; e7; e8; e9; e10; e11])
    by (apply (nodup_exchange [e0; e1; e2; e3] e4 [] e5 [e6; e7; e8; e9; e10; e11]); exact H0).
  assert (H2 : NoDup [e0; e1; e2; e3; e5; e6; e4; e7; e8; e9; e10; e11])
    by (apply (nodup_exchange [e0; e1; e2; e3; e5] e4 [] e6 [e7; e8; e9; e10; e11]); exact H1).
  assert (H3 : NoDup [e0; e1; e2; e3; e5; e6; e7; e4; e8; e9; e10; e11])
    by (apply (nodup_exchange [e0; e1; e2; e3; e5; e6] e4 [] e7 [e8; e9; e10; e11]); exact H2).
  exact H3.
Qed.

(** The corner slots after a clockwise turn of Left. *)
Lemma parity_corners_Left r0 r1 r2 r3 r4 r5 r6 r7 :
  NoDup [r0; r1; r2; r3; r4; r5; r6; r7] ->
  parity [r0; r2; r6; r3; r4; r1; r5; r7] = negb (parity [r0; r1; r2; r3; r4; r5; r6; r7]).
Proof.
  intro H0.
  assert (S0 : parity [r0; r1; r2; r3; r4; r5; r6; r7]
            = negb (parity [r0; r2; r1; r3; r4; r5; r6; r7]))
    by (apply (parity_exchange [r0] r1 [] r2 [r3; r4; r5; r6; r7]); exact H0).
  assert (H1 : NoDup [r0; r2; r1; r3; r4; r5; r6; r7])
    by (apply (nodup_exchange [r0] r1 [] r2 [r3; r4; r5; r6; r7]); exact H0).
  assert (S1 : parity [r0; r2; r1; r3; r4; r5; r6; r7]
            = negb (parity [r0; r2; r6; r3; r4; r5; r1; r7]))
    by (apply (parity_exchange [r0; r2] r1 [r3; r4; r5] r6 [r7]); exact H1).
  assert (H2 : NoDup [r0; r2; r6; r3; r4; r5; r1; r7])
    by (apply (nodup_exchange [r0; r2] r1 [r3; r4; r5] r6 [r7]); exact H1).
  assert (S2 : parity [r0; r2; r6; r3; r4; r5; r1; r7]
            = negb (parity [r0; r2; r6; r3; r4; r1; r5; r7]))
    by (apply (parity_exchange [r0; r2; r6; r3; r4] r5 [] r1 [r7]); exact H2).
  assert (E : parity [r0; r1; r2; r3; r4; r5; r6; r7] = negb (parity [r0; r2; r6; r3; r4; r1; r5; r7]))
    by (rewrite S0, S1, S2, !Bool.negb_involutive; reflexivity).
  rewrite E, Bool.negb_involutive; reflexivity.
Qed.

Lemma nodup_corners_Left (r0 r1 r2 r3 r4 r5 r6 r7 : nat) :
  NoDup [r0; r1; r2; r3; r4; r5; r6; r7] -> NoDup [r0; r2; r6; r3; r4; r1; r5; r7].
Proof.
  intro H0.
  assert (H1 : NoDup [r0; r2; r1; r3; r4; r5; r6; r7])
    by (apply (nodup_exchange [r0] r1 [] r2 [r3; r4; r5; r6; r7]); exact H0).
  assert (H2 : NoDup [r0; r2; r6; r3; r4; r5; r1; r7])
    by (apply (nodup_exchange [r0; r2] r1 [r3; r4; r5] r6 [r7]); exact H1).
  assert (H3 : NoDup [r0; r2; r6; r3; r4; r1; r5; r7])
    by (apply (nodup_exchange [r0; r2; r6; r3; r4] r5 [] r1 [r7]); exact H2).
  exact H3.
Qed.

(** And the edge slots. *)
Lemma parity_edges_Left e0 e1 e2 e3 e4 e5 e6 e7 e8 e9 e10 e11 :
  NoDup [e0; e1; e2; e3; e4; e5; e6; e7; e8; e9; e10; e11] ->
  parity [e0; e1; e10; e3; e4; e5; e9; e7; e8; e2; e6; e11] = negb (parity [e0; e1; e2; e3; e4; e5; e6; e7; e8; e9; e10; e11]).
Proof.
  intro H0.
  assert (S0 : parity [e0; e1; e2; e3; e4; e5; e6; e7; e8; e9; e10; e11]
            = negb (parity [e0; e1; e10; e3; e4; e5; e6; e7; e8; e9; e2; e11]))
    by (apply (parity_exchange [e0; e1] e2 [e3; e4; e5; e6; e7; e8; e9] e10 [e11]); exact H0).
  assert (H1 : NoDup [e0; e1; e10; e3; e4; e5; e6; e7; e8; e9; e2; e11])
    by (apply (nodup_exchange [e0; e1] e2 [e3; e4; e5; e6; e7; e8; e9] e10 [e11]); exact H0).
  assert (S1 : parity [e0; e1; e10; e3; e4; e5; e6; e7; e8; e9; e2; e11]
            = negb (parity [e0; e1; e10; e3; e4; e5; e9; e7; e8; e6; e2; e11]))
    by (apply (parity_exchange [e0; e1; e10; e3; e4; e5] e6 [e7; e8] e9 [e2; e11]); exact H1).
  assert (H2 : NoDup [e0; e1; e10; e3; e4; e5; e9; e7; e8; e6; e2; e11])
    by (apply (nodup_exchange [e0; e1; e10; e3; e4; e5] e6 [e7; e8] e9 [e2; e11]); exact H1).
  assert (S2 : parity [e0; e1; e10; e3; e4; e5; e9; e7; e8; e6; e2; e11]
            = negb (parity [e0; e1; e10; e3; e4; e5; e9; e7; e8; e2; e6; e11]))
    by (apply (parity_exchange [e0; e1; e10; e3; e4; e5; e9; e7; e8] e6 [] e2 [e11]); exact H2).
  assert (E : parity [e0; e1; e2; e3; e4; e5; e6; e7; e8; e9; e10; e11] = negb (parity [e0; e1; e10; e3; e4; e5; e9; e7; e8; e2; e6; e11]))
    by (rewrite S0, S1, S2, !Bool.negb_involutive; reflexivity).
  rewrite E, Bool.negb_involutive; reflexivity.
Qed.

Lemma nodup_edges_Left (e0 e1 e2 e3 e4 e5 e6 e7 e8 e9 e10 e11 : nat) :
  NoDup [e0; e1; e2; e3; e4; e5; e6; e7; e8; e9; e10; e11] -> NoDup [e0; e1; e10; e3; e4; e5; e9; e7; e8; e2; e6; e11].
Proof.
  intro H0.
  assert (H1 : NoDup [e0; e1; e10; e3; e4; e5; e6; e7; e8; e9; e2; e11])
    by (apply (nodup_exchange [e0; e1] e2 [e3; e4; e5; e6; e7; e8; e9] e10 [e11]); exact H0).
  assert (H2 : NoDup [e0; e1; e10; e3; e4; e5; e9; e7; e8; e6; e2; e11])
    by (apply (nodup_exchange [e0; e1; e10; e3; e4; e5] e6 [e7; e8] e9 [e2; e11]); exact H1).
  assert (H3 : NoDup [e0; e1; e10; e3; e4; e5; e9; e7; e8; e2; e6; e11])
    by (apply (nodup_exchange [e0; e1; e10; e3; e4; e5; e9; e7; e8] e6 [] e2 [e11]); exact H2).
  exact H3.
Qed.

(** The corner slots after a clockwise turn of Back. *)
Lemma parity_corners_Back r0 r1 r2 r3 r4 r5 r6 r7 :
  NoDup [r0; r1; r2; r3; r4; r5; r6; r7] ->
  parity [r0; r1; r3; r7; r4; r5; r2; r6] = negb (parity [r0; r1; r2; r3; r4; r5; r6; r7]).
Proof.
  intro H0.
  assert (S0 : parity [r0; r1; r2; r3; r4; r5; r6; r7]
            = negb (parity [r0; r1; r3; r2; r4; r5; r6; r7]))
    by (apply (parity_exchange [r0; r1] r2 [] r3 [r4; r5; r6; r7]); exact H0).
  assert (H1 : NoDup [r0; r1; r3; r2; r4; r5; r6; r7])
    by (apply (nodup_exchange [r0; r1] r2 [] r3 [r4; r5; r6; r7]); exact H0).
  assert (S1 : parity [r0; r1; r3; r2; r4; r5; r6; r7]
            = negb (parity [r0; r1; r3; r7; r4; r5; r6; r2]))
    by (apply (parity_exchange [r0; r1; r3] r2 [r4; r5; r6] r7 []); exact H1).
  assert (H2 : NoDup [r0; r1; r3; r7; r4; r5; r6; r2])
    by (apply (nodup_exchange [r0; r1; r3] r2 [r4; r5; r6] r7 []); exact H1).
  assert (S2 : parity [r0; r1; r3; r7; r4; r5; r6; r2]
            = negb (parity [r0; r1; r3; r7; r4; r5; r2; r6]))
    by (apply (parity_exchange [r0; r1; r3; r7; r4; r5] r6 [] r2 []); exact H2).
  assert (E : parity [r0; r1; r2; r3; r4; r5; r6; r7] = negb (parity [r0; r1; r3; r7; r4; r5; r2; r6]))
    by (rewrite S0, S1, S2, !Bool.negb_involutive; reflexivity).
  rewrite E, Bool.negb_involutive; reflexivity.
Qed.

Lemma nodup_corners_Back (r0 r1 r2 r3 r4 r5 r6 r7 : nat) :
  NoDup [r0; r1; r2; r3; r4; r5; r6; r7] -> NoDup [r0; r1; r3; r7; r4; r5; r2; r6].
Proof.
  intro H0.
  assert (H1 : NoDup [r0; r1; r3; r2; r4; r5; r6; r7])
    by (apply (nodup_exchange [r0; r1] r2 [] r3 [r4; r5; r6; r7]); exact H0).
  assert (H2 : NoDup [r0; r1; r3; r7; r4; r5; r6; r2])
    by (apply (nodup_exchange [r0; r1; r3] r2 [r4; r5; r6] r7 []); exact H1).
  assert (H3 : NoDup [r0; r1; r3; r7; r4; r5; r2; r6])
    by (apply (nodup_exchange [r0; r1; r3; r7; r4; r5] r6 [] r2 []); exact H2).
  exact H3.
Qed.

(** And the edge slots. *)
Lemma parity_edges_Back e0 e1 e2 e3 e4 e5 e6 e7 e8 e9 e10 e11 :
  NoDup [e0; e1; e2; e3; e4; e5; e6; e7; e8; e9; e10; e11] ->
  parity [e0; e1; e2; e11; e4; e5; e6; e10; e8; e9; e3; e7] = negb (parity [e0; e1; e2; e3; e4; e5; e6; e7; e8; e9; e10; e11]).
Proof.
  intro H0.
  assert (S0 : parity [e0; e1; e2; e3; e4; e5; e6; e7; e8; e9; e10; e11]
            = negb (parity [e0; e1; e2; e11; e4; e5; e6; e7; e8; e9; e10; e3]))
    by (apply (parity_exchange [e0; e1; e2] e3 [e4; e5; e6; e7; e8; e9; e10] e11 []); exact H0).
  assert (H1 : NoDup [e0; e1; e2; e11; e4; e5; e6; e7; e8; e9; e10; e3])
    by (apply (nodup_exchange [e0; e1; e2] e3 [e4; e5; e6; e7; e8; e9; e10] e11 []); exact H0).
  assert (S1 : parity [e0; e1; e2; e11; e4; e5; e6; e7; e8; e9; e10; e3]
            = negb (parity [e0; e1; e2; e11; e4; e5; e6; e10; e8; e9; e7; e3]))
    by (apply (parity_exchange [e0; e1; e2; e11; e4; e5; e6] e7 [e8; e9] e10 [e3]); exact H1).
  assert (H2 : NoDup [e0; e1; e2; e11; e4; e5; e6; e10; e8; e9; e7; e3])
    by (apply (nodup_exchange [e0; e1; e2; e11; e4; e5; e6] e7 [e8; e9] e10 [e3]); exact H1).
  assert (S2 : parity [e0; e1; e2; e11; e4; e5; e6; e10; e8; e9; e7; e3]
            = negb (parity [e0; e1; e2; e11; e4; e5; e6; e10; e8; e9; e3; e7]))
    by (apply (parity_exchange [e0; e1; e2; e11; e4; e5; e6; e10; e8; e9] e7 [] e3 []); exact H2).
  assert (E : parity [e0; e1; e2; e3; e4; e5; e6; e7; e8; e9; e10; e11] = negb (parity [e0; e1; e2; e11; e4; e5; e6; e10; e8; e9; e3; e7]))
    by (rewrite S0, S1, S2, !Bool.negb_involutive; reflexivity).
  rewrite E, Bool.negb_involutive; reflexivity.
Qed.

Lemma nodup_edges_Back (e0 e1 e2 e3 e4 e5 e6 e7 e8 e9 e10 e11 : nat) :
  NoDup [e0; e1; e2; e3; e4; e5; e6; e7; e8; e9; e10; e11] -> NoDup [e0; e1; e2; e11; e4; e5; e6; e10; e8; e9; e3; e7].
Proof.
  intro H0.
  assert (H1 : NoDup [e0; e1; e2; e11; e4; e5; e6; e7; e8; e9; e10; e3])
    by (apply (nodup_exchange [e0; e1; e2] e3 [e4; e5; e6; e7; e8; e9; e10] e11 []); exact H0).
  assert (H2 : NoDup [e0; e1; e2; e11; e4; e5; e6; e10; e8; e9; e7; e3])
    by (apply (nodup_exchange [e0; e1; e2; e11; e4; e5; e6] e7 [e8; e9] e10 [e3]); exact H1).
  assert (H3 : NoDup [e0; e1; e2; e11; e4; e5; e6; e10; e8; e9; e3; e7])
    by (apply (nodup_exchange [e0; e1; e2; e11; e4; e5; e6; e10; e8; e9] e7 [] e3 []); exact H2).
  exact H3.
Qed.
