(* Generated by scripts/generate_moves.py. Do not edit: run the script.
   The tables are checked inside Rocq, against the independent geometric
   account of a turn in Geometry.v and against each other in BasicRubik.v. *)

From Stdlib Require Import List.
From Rubik Require Export Sticker.
Import ListNotations.

(** * Face turn tables

    One table per turn amount, so a move rebuilds the 54 stickers once
    however far the face is turned. *)

(** A clockwise outer-layer turn permutes stickers while keeping centers fixed. *)
Definition quarter (f : face) (s : state) : state :=
  match s with
  | (Triple
       (Triple (Triple u0 u1 u2) (Triple u3 u4 u5) (Triple u6 u7 u8))
       (Triple (Triple r0 r1 r2) (Triple r3 r4 r5) (Triple r6 r7 r8))
       (Triple (Triple f0 f1 f2) (Triple f3 f4 f5) (Triple f6 f7 f8)),
     Triple
       (Triple (Triple d0 d1 d2) (Triple d3 d4 d5) (Triple d6 d7 d8))
       (Triple (Triple l0 l1 l2) (Triple l3 l4 l5) (Triple l6 l7 l8))
       (Triple (Triple b0 b1 b2) (Triple b3 b4 b5) (Triple b6 b7 b8))) =>
    match f with
    | Up =>
      (Triple
         (Triple (Triple u6 u3 u0) (Triple u7 u4 u1) (Triple u8 u5 u2))
         (Triple (Triple b0 b1 b2) (Triple r3 r4 r5) (Triple r6 r7 r8))
         (Triple (Triple r0 r1 r2) (Triple f3 f4 f5) (Triple f6 f7 f8)),
       Triple
         (Triple (Triple d0 d1 d2) (Triple d3 d4 d5) (Triple d6 d7 d8))
         (Triple (Triple f0 f1 f2) (Triple l3 l4 l5) (Triple l6 l7 l8))
         (Triple (Triple l0 l1 l2) (Triple b3 b4 b5) (Triple b6 b7 b8)))
    | Right =>
      (Triple
         (Triple (Triple u0 u1 f2) (Triple u3 u4 f5) (Triple u6 u7 f8))
         (Triple (Triple r6 r3 r0) (Triple r7 r4 r1) (Triple r8 r5 r2))
         (Triple (Triple f0 f1 d2) (Triple f3 f4 d5) (Triple f6 f7 d8)),
       Triple
         (Triple (Triple d0 d1 b6) (Triple d3 d4 b3) (Triple d6 d7 b0))
         (Triple (Triple l0 l1 l2) (Triple l3 l4 l5) (Triple l6 l7 l8))
         (Triple (Triple u8 b1 b2) (Triple u5 b4 b5) (Triple u2 b7 b8)))
    | Front =>
      (Triple
         (Triple (Triple u0 u1 u2) (Triple u3 u4 u5) (Triple l8 l5 l2))
         (Triple (Triple u6 r1 r2) (Triple u7 r4 r5) (Triple u8 r7 r8))
         (Triple (Triple f6 f3 f0) (Triple f7 f4 f1) (Triple f8 f5 f2)),
       Triple
         (Triple (Triple r6 r3 r0) (Triple d3 d4 d5) (Triple d6 d7 d8))
         (Triple (Triple l0 l1 d0) (Triple l3 l4 d1) (Triple l6 l7 d2))
         (Triple (Triple b0 b1 b2) (Triple b3 b4 b5) (Triple b6 b7 b8)))
    | Down =>
      (Triple
         (Triple (Triple u0 u1 u2) (Triple u3 u4 u5) (Triple u6 u7 u8))
         (Triple (Triple r0 r1 r2) (Triple r3 r4 r5) (Triple f6 f7 f8))
         (Triple (Triple f0 f1 f2) (Triple f3 f4 f5) (Triple l6 l7 l8)),
       Triple
         (Triple (Triple d6 d3 d0) (Triple d7 d4 d1) (Triple d8 d5 d2))
         (Triple (Triple l0 l1 l2) (Triple l3 l4 l5) (Triple b6 b7 b8))
         (Triple (Triple b0 b1 b2) (Triple b3 b4 b5) (Triple r6 r7 r8)))
    | Left =>
      (Triple
         (Triple (Triple b8 u1 u2) (Triple b5 u4 u5) (Triple b2 u7 u8))
         (Triple (Triple r0 r1 r2) (Triple r3 r4 r5) (Triple r6 r7 r8))
         (Triple (Triple u0 f1 f2) (Triple u3 f4 f5) (Triple u6 f7 f8)),
       Triple
         (Triple (Triple f0 d1 d2) (Triple f3 d4 d5) (Triple f6 d7 d8))
         (Triple (Triple l6 l3 l0) (Triple l7 l4 l1) (Triple l8 l5 l2))
         (Triple (Triple b0 b1 d6) (Triple b3 b4 d3) (Triple b6 b7 d0)))
    | Back =>
      (Triple
         (Triple (Triple r2 r5 r8) (Triple u3 u4 u5) (Triple u6 u7 u8))
         (Triple (Triple r0 r1 d8) (Triple r3 r4 d7) (Triple r6 r7 d6))
         (Triple (Triple f0 f1 f2) (Triple f3 f4 f5) (Triple f6 f7 f8)),
       Triple
         (Triple (Triple d0 d1 d2) (Triple d3 d4 d5) (Triple l0 l3 l6))
         (Triple (Triple u2 l1 l2) (Triple u1 l4 l5) (Triple u0 l7 l8))
         (Triple (Triple b6 b3 b0) (Triple b7 b4 b1) (Triple b8 b5 b2)))
    end
  end.

(** A half turn, tabulated directly rather than as two clockwise turns. *)
Definition half (f : face) (s : state) : state :=
  match s with
  | (Triple
       (Triple (Triple u0 u1 u2) (Triple u3 u4 u5) (Triple u6 u7 u8))
       (Triple (Triple r0 r1 r2) (Triple r3 r4 r5) (Triple r6 r7 r8))
       (Triple (Triple f0 f1 f2) (Triple f3 f4 f5) (Triple f6 f7 f8)),
     Triple
       (Triple (Triple d0 d1 d2) (Triple d3 d4 d5) (Triple d6 d7 d8))
       (Triple (Triple l0 l1 l2) (Triple l3 l4 l5) (Triple l6 l7 l8))
       (Triple (Triple b0 b1 b2) (Triple b3 b4 b5) (Triple b6 b7 b8))) =>
    match f with
    | Up =>
      (Triple
         (Triple (Triple u8 u7 u6) (Triple u5 u4 u3) (Triple u2 u1 u0))
         (Triple (Triple l0 l1 l2) (Triple r3 r4 r5) (Triple r6 r7 r8))
         (Triple (Triple b0 b1 b2) (Triple f3 f4 f5) (Triple f6 f7 f8)),
       Triple
         (Triple (Triple d0 d1 d2) (Triple d3 d4 d5) (Triple d6 d7 d8))
         (Triple (Triple r0 r1 r2) (Triple l3 l4 l5) (Triple l6 l7 l8))
         (Triple (Triple f0 f1 f2) (Triple b3 b4 b5) (Triple b6 b7 b8)))
    | Right =>
      (Triple
         (Triple (Triple u0 u1 d2) (Triple u3 u4 d5) (Triple u6 u7 d8))
         (Triple (Triple r8 r7 r6) (Triple r5 r4 r3) (Triple r2 r1 r0))
         (Triple (Triple f0 f1 b6) (Triple f3 f4 b3) (Triple f6 f7 b0)),
       Triple
         (Triple (Triple d0 d1 u2) (Triple d3 d4 u5) (Triple d6 d7 u8))
         (Triple (Triple l0 l1 l2) (Triple l3 l4 l5) (Triple l6 l7 l8))
         (Triple (Triple f8 b1 b2) (Triple f5 b4 b5) (Triple f2 b7 b8)))
    | Front =>
      (Triple
         (Triple (Triple u0 u1 u2) (Triple u3 u4 u5) (Triple d2 d1 d0))
         (Triple (Triple l8 r1 r2) (Triple l5 r4 r5) (Triple l2 r7 r8))
         (Triple (Triple f8 f7 f6) (Triple f5 f4 f3) (Triple f2 f1 f0)),
       Triple
         (Triple (Triple u8 u7 u6) (Triple d3 d4 d5) (Triple d6 d7 d8))
         (Triple (Triple l0 l1 r6) (Triple l3 l4 r3) (Triple l6 l7 r0))
         (Triple (Triple b0 b1 b2) (Triple b3 b4 b5) (Triple b6 b7 b8)))
    | Down =>
      (Triple
         (Triple (Triple u0 u1 u2) (Triple u3 u4 u5) (Triple u6 u7 u8))
         (Triple (Triple r0 r1 r2) (Triple r3 r4 r5) (Triple l6 l7 l8))
         (Triple (Triple f0 f1 f2) (Triple f3 f4 f5) (Triple b6 b7 b8)),
       Triple
         (Triple (Triple d8 d7 d6) (Triple d5 d4 d3) (Triple d2 d1 d0))
         (Triple (Triple l0 l1 l2) (Triple l3 l4 l5) (Triple r6 r7 r8))
         (Triple (Triple b0 b1 b2) (Triple b3 b4 b5) (Triple f6 f7 f8)))
    | Left =>
      (Triple
         (Triple (Triple d0 u1 u2) (Triple d3 u4 u5) (Triple d6 u7 u8))
         (Triple (Triple r0 r1 r2) (Triple r3 r4 r5) (Triple r6 r7 r8))
         (Triple (Triple b8 f1 f2) (Triple b5 f4 f5) (Triple b2 f7 f8)),
       Triple
         (Triple (Triple u0 d1 d2) (Triple u3 d4 d5) (Triple u6 d7 d8))
         (Triple (Triple l8 l7 l6) (Triple l5 l4 l3) (Triple l2 l1 l0))
         (Triple (Triple b0 b1 f6) (Triple b3 b4 f3) (Triple b6 b7 f0)))
    | Back =>
      (Triple
         (Triple (Triple d8 d7 d6) (Triple u3 u4 u5) (Triple u6 u7 u8))
         (Triple (Triple r0 r1 l6) (Triple r3 r4 l3) (Triple r6 r7 l0))
         (Triple (Triple f0 f1 f2) (Triple f3 f4 f5) (Triple f6 f7 f8)),
       Triple
         (Triple (Triple d0 d1 d2) (Triple d3 d4 d5) (Triple u2 u1 u0))
         (Triple (Triple r8 l1 l2) (Triple r5 l4 l5) (Triple r2 l7 l8))
         (Triple (Triple b8 b7 b6) (Triple b5 b4 b3) (Triple b2 b1 b0)))
    end
  end.

(** A counterclockwise turn, tabulated directly rather than as three clockwise
    turns. *)
Definition quarter_inv (f : face) (s : state) : state :=
  match s with
  | (Triple
       (Triple (Triple u0 u1 u2) (Triple u3 u4 u5) (Triple u6 u7 u8))
       (Triple (Triple r0 r1 r2) (Triple r3 r4 r5) (Triple r6 r7 r8))
       (Triple (Triple f0 f1 f2) (Triple f3 f4 f5) (Triple f6 f7 f8)),
     Triple
       (Triple (Triple d0 d1 d2) (Triple d3 d4 d5) (Triple d6 d7 d8))
       (Triple (Triple l0 l1 l2) (Triple l3 l4 l5) (Triple l6 l7 l8))
       (Triple (Triple b0 b1 b2) (Triple b3 b4 b5) (Triple b6 b7 b8))) =>
    match f with
    | Up =>
      (Triple
         (Triple (Triple u2 u5 u8) (Triple u1 u4 u7) (Triple u0 u3 u6))
         (Triple (Triple f0 f1 f2) (Triple r3 r4 r5) (Triple r6 r7 r8))
         (Triple (Triple l0 l1 l2) (Triple f3 f4 f5) (Triple f6 f7 f8)),
       Triple
         (Triple (Triple d0 d1 d2) (Triple d3 d4 d5) (Triple d6 d7 d8))
         (Triple (Triple b0 b1 b2) (Triple l3 l4 l5) (Triple l6 l7 l8))
         (Triple (Triple r0 r1 r2) (Triple b3 b4 b5) (Triple b6 b7 b8)))
    | Right =>
      (Triple
         (Triple (Triple u0 u1 b6) (Triple u3 u4 b3) (Triple u6 u7 b0))
         (Triple (Triple r2 r5 r8) (Triple r1 r4 r7) (Triple r0 r3 r6))
         (Triple (Triple f0 f1 u2) (Triple f3 f4 u5) (Triple f6 f7 u8)),
       Triple
         (Triple (Triple d0 d1 f2) (Triple d3 d4 f5) (Triple d6 d7 f8))
         (Triple (Triple l0 l1 l2) (Triple l3 l4 l5) (Triple l6 l7 l8))
         (Triple (Triple d8 b1 b2) (Triple d5 b4 b5) (Triple d2 b7 b8)))
    | Front =>
      (Triple
         (Triple (Triple u0 u1 u2) (Triple u3 u4 u5) (Triple r0 r3 r6))
         (Triple (Triple d2 r1 r2) (Triple d1 r4 r5) (Triple d0 r7 r8))
         (Triple (Triple f2 f5 f8) (Triple f1 f4 f7) (Triple f0 f3 f6)),
       Triple
         (Triple (Triple l2 l5 l8) (Triple d3 d4 d5) (Triple d6 d7 d8))
         (Triple (Triple l0 l1 u8) (Triple l3 l4 u7) (Triple l6 l7 u6))
         (Triple (Triple b0 b1 b2) (Triple b3 b4 b5) (Triple b6 b7 b8)))
    | Down =>
      (Triple
         (Triple (Triple u0 u1 u2) (Triple u3 u4 u5) (Triple u6 u7 u8))
         (Triple (Triple r0 r1 r2) (Triple r3 r4 r5) (Triple b6 b7 b8))
         (Triple (Triple f0 f1 f2) (Triple f3 f4 f5) (Triple r6 r7 r8)),
       Triple
         (Triple (Triple d2 d5 d8) (Triple d1 d4 d7) (Triple d0 d3 d6))
         (Triple (Triple l0 l1 l2) (Triple l3 l4 l5) (Triple f6 f7 f8))
         (Triple (Triple b0 b1 b2) (Triple b3 b4 b5) (Triple l6 l7 l8)))
    | Left =>
      (Triple
         (Triple (Triple f0 u1 u2) (Triple f3 u4 u5) (Triple f6 u7 u8))
         (Triple (Triple r0 r1 r2) (Triple r3 r4 r5) (Triple r6 r7 r8))
         (Triple (Triple d0 f1 f2) (Triple d3 f4 f5) (Triple d6 f7 f8)),
       Triple
         (Triple (Triple b8 d1 d2) (Triple b5 d4 d5) (Triple b2 d7 d8))
         (Triple (Triple l2 l5 l8) (Triple l1 l4 l7) (Triple l0 l3 l6))
         (Triple (Triple b0 b1 u6) (Triple b3 b4 u3) (Triple b6 b7 u0)))
    | Back =>
      (Triple
         (Triple (Triple l6 l3 l0) (Triple u3 u4 u5) (Triple u6 u7 u8))
         (Triple (Triple r0 r1 u0) (Triple r3 r4 u1) (Triple r6 r7 u2))
         (Triple (Triple f0 f1 f2) (Triple f3 f4 f5) (Triple f6 f7 f8)),
       Triple
         (Triple (Triple d0 d1 d2) (Triple d3 d4 d5) (Triple r8 r5 r2))
         (Triple (Triple d6 l1 l2) (Triple d7 l4 l5) (Triple d8 l7 l8))
         (Triple (Triple b2 b5 b8) (Triple b1 b4 b7) (Triple b0 b3 b6)))
    end
  end.
