#!/usr/bin/env python3
"""Generate theories/Cube/ParityTables.v: one proof per face that a quarter turn
flips the parity of the corner list and of the edge list.

A quarter turn is a four-cycle on the corner slots and a four-cycle on the
edge slots. Four-cycles are odd, so each list's parity flips, and the two
flips cancel in the invariant that Parity.v exports. Turning a four-cycle into
three exchanges is mechanical, so the proofs are written out here rather than
by hand.
"""

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import cubelib as L

ROOT = Path(__file__).resolve().parent.parent
TARGET = "theories/Cube/ParityTables.v"

HEADER = '''(* Generated by scripts/generate_parity.py. Do not edit: run the script.
   The permutations are read from theories/CubieTables.v, so the two files
   cannot drift apart without this one failing to compile. *)

From Stdlib Require Import Arith List Lia Permutation Bool.
From Rubik Require Export Cube.Parity.
Import ListNotations.

(** * A quarter turn flips each list's parity

    One lemma per face for the corner slots and one for the edge slots. Each
    turn is a four-cycle, which three exchanges undo, and each exchange flips
    the parity. *)

'''


def sources():
    """For each face, the slot feeding each corner slot and each edge slot."""
    return {face: ([L.CORNERS[i] for i, _ in cs], [L.EDGES[j] for j, _ in es])
            for face, (cs, es) in L.quarter_tables().items()}


def swaps(new, old):
    """Exchanges turning `new` into `old`, one position at a time."""
    cur = list(new)
    steps = []
    for i in range(len(cur)):
        if cur[i] == old[i]:
            continue
        j = cur.index(old[i], i + 1)
        steps.append((list(cur), i, j))
        cur[i], cur[j] = cur[j], cur[i]
    assert cur == old
    return steps, cur


def rocq_list(xs):
    """Any sequence of already-rendered terms as a Rocq list."""
    return "[" + "; ".join(xs) + "]"


def render(name, var, names, sources_for_face):
    """One lemma: the turned list has the opposite parity to the original."""
    old = [f"{var}{i}" for i in range(len(names))]
    index = {n: i for i, n in enumerate(names)}
    new = [old[index[s]] for s in sources_for_face]
    steps, _ = swaps(old, new)
    assert len(steps) % 2 == 1, (name, len(steps))
    lines = [f"Lemma {name} {' '.join(old)} :",
             f"  NoDup {rocq_list(old)} ->",
             f"  parity {rocq_list(new)} = negb (parity {rocq_list(old)}).",
             "Proof.",
             "  intro H0."]
    for k, (state, i, j) in enumerate(steps):
        after = list(state)
        after[i], after[j] = after[j], after[i]
        a, x, b, y, c = state[:i], state[i], state[i + 1:j], state[j], state[j + 1:]
        args = f"{rocq_list(a)} {x} {rocq_list(b)} {y} {rocq_list(c)}"
        lines.append(f"  assert (S{k} : parity {rocq_list(state)}")
        lines.append(f"            = negb (parity {rocq_list(after)}))")
        lines.append(f"    by (apply (parity_exchange {args}); exact H{k}).")
        if k + 1 < len(steps):
            lines.append(f"  assert (H{k + 1} : NoDup {rocq_list(after)})")
            lines.append(f"    by (apply (nodup_exchange {args}); exact H{k}).")
    refs = ", ".join(f"S{k}" for k in range(len(steps)))
    lines.append(f"  assert (E : parity {rocq_list(old)} = negb (parity {rocq_list(new)}))")
    lines.append(f"    by (rewrite {refs}, !Bool.negb_involutive; reflexivity).")
    lines.append("  rewrite E, Bool.negb_involutive; reflexivity.")
    lines.append("Qed.")
    lines.append("")
    lines.append("(** And it keeps them all different, which the next exchange needs. *)")
    lines.append(f"Lemma nodup_{name[len('parity_'):]} ({' '.join(old)} : nat) :")
    lines.append(f"  NoDup {rocq_list(old)} -> NoDup {rocq_list(new)}.")
    lines.append("Proof.")
    lines.append("  intro H0.")
    for k, (state, i, j) in enumerate(steps):
        after = list(state)
        after[i], after[j] = after[j], after[i]
        a, x, b, y, c = state[:i], state[i], state[i + 1:j], state[j], state[j + 1:]
        args = f"{rocq_list(a)} {x} {rocq_list(b)} {y} {rocq_list(c)}"
        lines.append(f"  assert (H{k + 1} : NoDup {rocq_list(after)})")
        lines.append(f"    by (apply (nodup_exchange {args}); exact H{k}).")
    lines.append(f"  exact H{len(steps)}.")
    lines.append("Qed.")
    lines.append("")
    return "\n".join(lines)


def generate():
    """Both lemmas for each of the six faces, as a whole file."""
    src = sources()
    out = [HEADER]
    for face in L.FACES:
        cs, es = src[face]
        out.append(f"(** The corner slots after a clockwise turn of {face}. *)")
        out.append(render(f"parity_corners_{face}", "r", L.CORNERS, cs))
        out.append(f"(** And the edge slots. *)")
        out.append(render(f"parity_edges_{face}", "e", L.EDGES, es))
    return "\n".join(out).rstrip() + "\n"


def main():
    """Rewrite the target, or check that the checked-in one matches."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="fail if the checked-in proofs are stale")
    args = parser.parse_args()
    path = ROOT / TARGET
    updated = generate()
    if args.check:
        if not path.exists() or path.read_text() != updated:
            raise SystemExit(f"{TARGET} is stale; run scripts/generate_parity.py")
    else:
        path.write_text(updated)


if __name__ == "__main__":
    main()
