#!/usr/bin/env python3
"""Generate the cubie tables in theories/Cubie.v from the shared 3D geometry.

The 54 stickers group into 8 corner slots of three facelets, 12 edge slots of
two, and 6 fixed centers. Each slot lists its facelets with the up or down one
first, or the front or back one for a middle-slice edge, then clockwise seen
from outside. A face turn permutes slots and rotates the cubies within them;
the shift recorded here is how far a cubie's own facelets slide around its new
slot, which is exactly the change in its orientation.
"""

import argparse
import importlib.util
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
_spec = importlib.util.spec_from_file_location("gm", ROOT / "scripts" / "generate_moves.py")
gm = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(gm)

FACE_OF = {n: f for f, (n, _, _) in gm.FACES.items()}
NAMES = [f"{face[0].lower()}{i}" for face in gm.FACES for i in range(9)]
STICKERS = gm.facelets()

CORNERS = ["URF", "UFL", "ULB", "UBR", "DFR", "DLF", "DBL", "DRB"]
CORNER_POS = {"URF": (1, 1, 1), "UFL": (-1, 1, 1), "ULB": (-1, 1, -1), "UBR": (1, 1, -1),
              "DFR": (1, -1, 1), "DLF": (-1, -1, 1), "DBL": (-1, -1, -1), "DRB": (1, -1, -1)}
EDGES = ["UR", "UF", "UL", "UB", "DR", "DF", "DL", "DB", "FR", "FL", "BL", "BR"]
EDGE_POS = {"UR": (1, 1, 0), "UF": (0, 1, 1), "UL": (-1, 1, 0), "UB": (0, 1, -1),
            "DR": (1, -1, 0), "DF": (0, -1, 1), "DL": (-1, -1, 0), "DB": (0, -1, -1),
            "FR": (1, 0, 1), "FL": (-1, 0, 1), "BL": (-1, 0, -1), "BR": (1, 0, -1)}

TARGET = "theories/Cube/CubieTables.v"

HEADER = """(* Generated by scripts/generate_cubies.py. Do not edit: run the script.
   The tables are checked inside Rocq: paint_cquarter in Cubie.v proves they
   agree with the sticker tables, move for move. *)

From Stdlib Require Import List.
From Rubik Require Export Cube.CubieDefs.
Import ListNotations.

(** * Cubie tables

    Which piece a turn moves into each slot and how far it rotates there, and
    which colour each slot shows. *)

"""


def det(a, b, c):
    """Orientation of three axes; negative means clockwise seen from outside."""
    return (a[0] * (b[1] * c[2] - b[2] * c[1]) - a[1] * (b[0] * c[2] - b[2] * c[0])
            + a[2] * (b[0] * c[1] - b[1] * c[0]))


def by_position():
    """Group the 54 facelets by the cubie position they sit on."""
    groups = {}
    for name, (pos, normal) in zip(NAMES, STICKERS):
        groups.setdefault(pos, []).append((name, normal))
    return groups


GROUPS = by_position()


def slot_facelets(pos):
    """A slot's facelets: reference first, then clockwise seen from outside."""
    facelets = GROUPS[pos]
    if len(facelets) == 3:
        ref = next(f for f in facelets if f[1][1] != 0)
        a, b = [f for f in facelets if f is not ref]
        return [ref, a, b] if det(ref[1], a[1], b[1]) < 0 else [ref, b, a]
    ref = (next((f for f in facelets if f[1][1] != 0), None)
           or next(f for f in facelets if f[1][2] != 0))
    return [ref, next(f for f in facelets if f is not ref)]


CORNER_SLOTS = {c: slot_facelets(p) for c, p in CORNER_POS.items()}
EDGE_SLOTS = {e: slot_facelets(p) for e, p in EDGE_POS.items()}


def solved_colors(slot):
    """The colors a cubie shows when solved, in its own facelet order."""
    return [FACE_OF[normal] for _, normal in slot]


def shifts(face, slots, positions, order):
    """Per destination slot, the slot it is fed from and the orientation shift."""
    normal = gm.FACES[face][0]
    table = {}
    for dst in order:
        src = next((s for s in order
                    if gm.dot(positions[s], normal) == 1
                    and gm.rotate(positions[s], normal) == positions[dst]), None)
        if src is None:
            table[dst] = (dst, 0)
            continue
        dst_normals = [n for _, n in slots[dst]]
        src_normals = [n for _, n in slots[src]]
        shift = dst_normals.index(gm.rotate(src_normals[0], normal))
        for i, n in enumerate(src_normals):
            assert dst_normals.index(gm.rotate(n, normal)) == (i + shift) % len(dst_normals)
        table[dst] = (src, shift)
    return table


def render_colors(name, kind, slots, order, indices):
    """Render one cubie's solved colors as a two-argument lookup."""
    lines = [f"Definition {name} (x : {kind}) (i : {indices[0][0]}i) : color :=",
             "  match x, i with"]
    for cubie in order:
        for i, color in enumerate(solved_colors(slots[cubie])):
            lines.append(f"  | {cubie}, {indices[i]} => {color}")
    return "\n".join(lines + ["  end.", ""])


def render_lookup(name, kind, slots, order, amounts, letter):
    """Render the inverse reading: which piece shows these colors, and how turned."""
    n = len(amounts)
    args = " ".join(f"({chr(97 + i)} : color)" for i in range(n))
    lines = [f"Definition {name} {args} : {kind} :=",
             "  match " + ", ".join(chr(97 + i) for i in range(n)) + " with"]
    for cubie in order:
        cols = solved_colors(slots[cubie])
        for k, amount in enumerate(amounts):
            # A piece turned by k shows, at position i, the facelet i - k.
            shown = [cols[(i - k) % n] for i in range(n)]
            lines.append("  | " + ", ".join(shown) + f" => ({cubie}, {amount})")
    lines.append(f"  | _, _{', _' * (n - 2)} => ({order[0]}, {amounts[0]})")
    return "\n".join(lines + ["  end.", ""])


def render_to_cubies():
    """Render reading all twenty slots off the 54 stickers."""
    names = []
    for cubie in CORNERS:
        names.append("(corner_of " + " ".join(f[0] for f in CORNER_SLOTS[cubie]) + ")")
    for cubie in EDGES:
        names.append("(edge_of " + " ".join(f[0] for f in EDGE_SLOTS[cubie]) + ")")
    return ("Definition to_cubies (s : state) : cube :=\n"
            "  match s with\n"
            "  | " + gm.pack(NAMES, 4) + " =>\n"
            "    Cube " + " ".join(names[:4]) + "\n"
            "         " + " ".join(names[4:8]) + "\n"
            "         " + " ".join(names[8:14]) + "\n"
            "         " + " ".join(names[14:]) + "\n"
            "  end.\n")


def render_paint():
    """Render the 54 stickers as reads of the cubie occupying each slot."""
    source = {}
    for cubie in CORNERS:
        for i, (name, _) in enumerate(CORNER_SLOTS[cubie]):
            source[name] = f"corner_color x{cubie} C{i}"
    for cubie in EDGES:
        for i, (name, _) in enumerate(EDGE_SLOTS[cubie]):
            source[name] = f"edge_color y{cubie} E{i}"
    for face in gm.FACES:
        source[f"{face[0].lower()}4"] = face
    grids = []
    for g in range(6):
        rows = []
        for r in range(3):
            entries = [source[NAMES[9 * g + 3 * r + c]] for c in range(3)]
            rows.append("      (Triple " + " ".join(f"({e})" for e in entries) + ")")
        grids.append("    (Triple\n" + "\n".join(rows) + ")")
    return ("Definition paint (c : cube) : state :=\n"
            "  match c with\n"
            "  | Cube " + " ".join(f"x{c}" for c in CORNERS) + "\n"
            "           " + " ".join(f"y{e}" for e in EDGES) + " =>\n"
            "    (Triple\n" + "\n".join(grids[:3]) + ",\n"
            "     Triple\n" + "\n".join(grids[3:]) + ")\n"
            "  end.\n")


def render_cquarter():
    """Render the clockwise turn as a slot permutation with orientation shifts."""
    lines = ["Definition cquarter (f : face) (c : cube) : cube :=",
             "  match c with",
             "  | Cube " + " ".join(f"x{c}" for c in CORNERS),
             "           " + " ".join(f"y{e}" for e in EDGES) + " =>",
             "    match f with"]
    for face in gm.FACES:
        corner = shifts(face, CORNER_SLOTS, CORNER_POS, CORNERS)
        edge = shifts(face, EDGE_SLOTS, EDGE_POS, EDGES)
        cs = [f"(cshift T{k} x{src})" for dst in CORNERS for src, k in [corner[dst]]]
        es = [f"(eshift F{k} y{src})" for dst in EDGES for src, k in [edge[dst]]]
        lines.extend([f"    | {face} =>",
                      "      Cube " + " ".join(cs[:4]),
                      "           " + " ".join(cs[4:]),
                      "           " + " ".join(es[:6]),
                      "           " + " ".join(es[6:])])
    return "\n".join(lines + ["    end", "  end.", ""])


def generate():
    """Render every table the cubie model needs, as a whole file."""
    return HEADER + "\n".join([
        "(** The colors a corner shows when solved, read around its own facelets. *)",
        render_colors("ccolors", "corner", CORNER_SLOTS, CORNERS, ["C0", "C1", "C2"]),
        "(** The colors an edge shows when solved. *)",
        render_colors("ecolors", "edge", EDGE_SLOTS, EDGES, ["E0", "E1"]),
        "(** The color a slot shows at one of its facelet positions. *)",
        "Definition corner_color (x : cslot) (i : Ci) : color :=\n"
        "  let (X, t) := x in ccolors X (ci_sub i t).\n",
        "(** And the colour an edge slot shows. *)\n"
        "Definition edge_color (y : eslot) (i : Ei) : color :=\n"
        "  let (Y, f) := y in ecolors Y (ei_sub i f).\n",
        "(** Paint the 54 stickers from the cubies occupying the 20 slots. *)",
        render_paint(),
        "(** A clockwise turn moves cubies between slots and rotates them there. *)",
        render_cquarter(),
        "(** Which corner shows these three colors, and how far it is turned. A\n"
        "    color triple that belongs to no corner cannot arise from a cube, so\n"
        "    the default there is never read. *)",
        render_lookup("corner_of", "cslot", CORNER_SLOTS, CORNERS, ["T0", "T1", "T2"], "C"),
        "(** The same for an edge. *)",
        render_lookup("edge_of", "eslot", EDGE_SLOTS, EDGES, ["F0", "F1"], "E"),
        "(** Read all twenty slots off the stickers. *)",
        render_to_cubies(),
    ]).rstrip() + "\n"


def main():
    """Rewrite the target, or check that the checked-in one is what we would write."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="fail if the checked-in tables are stale")
    args = parser.parse_args()
    path = ROOT / TARGET
    updated = generate()
    if args.check:
        if not path.exists() or path.read_text() != updated:
            raise SystemExit(f"{TARGET} is stale; run scripts/generate_cubies.py")
    else:
        path.write_text(updated)


if __name__ == "__main__":
    main()
