#!/usr/bin/env python3
"""Generate facelet permutations from integer 3D quarter rotations.

Axes: +x right, +y up, +z front. Each face is viewed from outside;
rows run top to bottom, columns left to right. Clockwise is -90 degrees
about the outward normal. Only the outer layer rotates; centers stay fixed.
"""

import argparse
from pathlib import Path

# Each face supplies its outward normal, rightward axis, and downward axis.
FACES = {
    "Up": ((0, 1, 0), (1, 0, 0), (0, 0, 1)),
    "Right": ((1, 0, 0), (0, 0, -1), (0, -1, 0)),
    "Front": ((0, 0, 1), (1, 0, 0), (0, -1, 0)),
    "Down": ((0, -1, 0), (1, 0, 0), (0, 0, -1)),
    "Left": ((-1, 0, 0), (0, 0, 1), (0, -1, 0)),
    "Back": ((0, 0, -1), (-1, 0, 0), (0, -1, 0)),
}
TARGET = "theories/Cube/TurnTables.v"

HEADER = """(* Generated by scripts/generate_moves.py. Do not edit: run the script.
   The tables are checked inside Rocq, against the independent geometric
   account of a turn in Geometry.v and against each other in BasicRubik.v. *)

From Stdlib Require Import List.
From Rubik Require Export Cube.Sticker.
Import ListNotations.

(** * Face turn tables

    One table per turn amount, so a move rebuilds the 54 stickers once
    however far the face is turned. *)

"""


def dot(a, b):
    """Project a position onto a face normal to identify its outer layer."""
    return sum(x * y for x, y in zip(a, b))


def rotate(v, n):
    """Rotate clockwise about the signed unit axis n using the cross product."""
    cross = (
        n[1] * v[2] - n[2] * v[1],
        n[2] * v[0] - n[0] * v[2],
        n[0] * v[1] - n[1] * v[0],
    )
    return tuple(n[i] * dot(n, v) - cross[i] for i in range(3))


def triple(xs):
    """Render three Rocq expressions as one reusable triple constructor."""
    return "(Triple " + " ".join(xs) + ")"


def pack(xs, indent):
    """Lay out the 54 stickers as six aligned grids in the state's face order."""
    grids = [
        triple([triple(xs[i + j:i + j + 3]) for j in (0, 3, 6)])
        for i in range(0, 54, 9)
    ]
    rows = "\n" + " " * (indent + 3)
    return (
        "(Triple" + rows + rows.join(grids[:3]) + ",\n"
        + " " * (indent + 1) + "Triple" + rows + rows.join(grids[3:]) + ")"
    )


def facelets():
    """Enumerate sticker positions and normals in outside-view row-major order."""
    return [
        (
            tuple(normal[i] + col * right[i] + row * down[i] for i in range(3)),
            normal,
        )
        for normal, right, down in FACES.values()
        for row in (-1, 0, 1)
        for col in (-1, 0, 1)
    ]


def permute(stickers, names, normal, times):
    """Name, for every slot, the sticker that lands there after so many turns."""
    output = [None] * len(stickers)
    for name, (position, direction) in zip(names, stickers):
        target = (position, direction)
        if dot(position, normal) == 1:
            for _ in range(times):
                target = (rotate(target[0], normal), rotate(target[1], normal))
        output[stickers.index(target)] = name
    assert sorted(output) == sorted(names)
    return output


def render(stickers, names, definition, doc, times):
    """Render one turn amount as a single documented state-to-state definition."""
    lines = [
        doc,
        f"Definition {definition} (f : face) (s : state) : state :=",
        "  match s with",
        "  | " + pack(names, 4) + " =>",
        "    match f with",
    ]
    for face, (normal, _, _) in FACES.items():
        lines.extend(
            [f"    | {face} =>", "      " + pack(permute(stickers, names, normal, times), 6)]
        )
    return "\n".join([*lines, "    end", "  end.", ""])


# Each turn amount gets its own table, so no move is built from repeated turns.
AMOUNTS = [
    (
        "quarter",
        "(** A clockwise outer-layer turn permutes stickers while keeping centers fixed. *)",
        1,
    ),
    (
        "half",
        "(** A half turn, tabulated directly rather than as two clockwise turns. *)",
        2,
    ),
    (
        "quarter_inv",
        "(** A counterclockwise turn, tabulated directly rather than as three clockwise\n    turns. *)",
        3,
    ),
]


def generate():
    """Derive the six permutations at each turn amount and render their definitions."""
    stickers = facelets()
    names = [f"{face[0].lower()}{i}" for face in FACES for i in range(9)]
    bodies = [render(stickers, names, *amount) for amount in AMOUNTS]
    return HEADER + "\n".join(bodies).rstrip() + "\n"


def main():
    """Rewrite the target, or check that the checked-in one is what we would write."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="fail if the checked-in tables are stale"
    )
    args = parser.parse_args()
    path = Path(__file__).resolve().parent.parent / TARGET
    updated = generate()
    if args.check:
        if not path.exists() or path.read_text() != updated:
            raise SystemExit(f"{TARGET} is stale; run scripts/generate_moves.py")
    else:
        path.write_text(updated)


if __name__ == "__main__":
    main()
